# pytest.ini
[pytest]
norecursedirs = 
    garbage/* another_directory 
    temp_files 
    scripts
tmp_path_retention_policy = failed
tmp_path_retention_count = 3
filterwarnings =
    ignore:cannot collect test class 'TestFunction' because it has a __init__ constructor:pytest.PytestCollectionWarning
    ignore:cannot collect test class 'VectorTestFunction' because it has a __init__ constructor:pytest.PytestCollectionWarning
    ignore:cannot collect test class 'TrialFunction' because it has a __init__ constructor:pytest.PytestCollectionWarning
    ignore:cannot collect test class 'VectorTrialFunction' because it has a __init__ constructor:pytest.PytestCollectionWarning
