from __future__ import annotations

import hashlib
import importlib.util
import os
import sysconfig
from pathlib import Path
from typing import Any

import numpy as np
import scipy.sparse as sp

from pycutfem.core.dofhandler import DofHandler
from pycutfem.fem import transform
from pycutfem.integration.quadrature import gauss_legendre
from pycutfem.jit.cpp_backend.compiler import compile_extension

from .interface import NonMatchingInterface
from .mortar import MortarCoupling
from .nitsche import _field_order


CODEGEN_ABI_NONMATCHING_CPP = "2026-01-26-nonmatching-v1"

_CPP_MODULE: Any | None = None


def _cache_dir() -> Path:
    root = Path(os.environ.get("PYCUTFEM_CACHE_DIR", Path.home() / ".cache" / "pycutfem_jit")).expanduser().resolve()
    d = root / "cpp_nonmatching"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _cpp_source(module_name: str) -> str:
    # Keep this as a single TU to simplify caching and compilation.
    return f"""
// Generated by pycutfem.nonmatching.cpp_backend (ABI {CODEGEN_ABI_NONMATCHING_CPP})
#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>
#include <cstdint>

namespace py = pybind11;

static const char* CODEGEN_ABI = "{CODEGEN_ABI_NONMATCHING_CPP}";

py::tuple poisson_nitsche_triplets(
    py::array_t<std::int64_t, py::array::c_style | py::array::forcecast> gd_pos,
    py::array_t<std::int64_t, py::array::c_style | py::array::forcecast> gd_neg,
    py::array_t<double, py::array::c_style | py::array::forcecast> phi_p,
    py::array_t<double, py::array::c_style | py::array::forcecast> gn_p,
    py::array_t<double, py::array::c_style | py::array::forcecast> phi_n,
    py::array_t<double, py::array::c_style | py::array::forcecast> gn_n,
    py::array_t<double, py::array::c_style | py::array::forcecast> qw,
    py::array_t<double, py::array::c_style | py::array::forcecast> stab,
    double kappa_pos,
    double kappa_neg,
    double k_pos,
    double k_neg
) {{
    auto gdP = gd_pos.unchecked<2>();
    auto gdN = gd_neg.unchecked<2>();
    auto PhiP = phi_p.unchecked<3>();
    auto GnP  = gn_p.unchecked<3>();
    auto PhiN = phi_n.unchecked<3>();
    auto GnN  = gn_n.unchecked<3>();
    auto W    = qw.unchecked<2>();
    auto Stab = stab.unchecked<1>();

    const std::int64_t n_seg = gdP.shape(0);
    const std::int64_t nlp = gdP.shape(1);
    const std::int64_t nln = gdN.shape(1);
    const std::int64_t n_q = W.shape(1);

    const std::int64_t ntrip_per_seg = nlp*nlp + nlp*nln + nln*nlp + nln*nln;
    const std::int64_t ntrip = n_seg * ntrip_per_seg;

    py::array_t<std::int64_t> rows(ntrip);
    py::array_t<std::int64_t> cols(ntrip);
    py::array_t<double> data(ntrip);
    auto R = rows.mutable_unchecked<1>();
    auto C = cols.mutable_unchecked<1>();
    auto D = data.mutable_unchecked<1>();

    std::int64_t out = 0;
    for (std::int64_t s=0; s<n_seg; ++s) {{
        const double st = Stab(s);

        // Local matrices
        std::vector<double> A_pp(nlp*nlp, 0.0);
        std::vector<double> A_pn(nlp*nln, 0.0);
        std::vector<double> A_np(nln*nlp, 0.0);
        std::vector<double> A_nn(nln*nln, 0.0);

        for (std::int64_t q=0; q<n_q; ++q) {{
            const double wq = W(s,q);
            if (wq == 0.0) continue;

            for (std::int64_t i=0; i<nlp; ++i) {{
                const double phi_pi = PhiP(s,q,i);
                const double gn_pi  = GnP(s,q,i);
                // pp
                for (std::int64_t j=0; j<nlp; ++j) {{
                    const double v = kappa_pos * k_pos * (phi_pi * GnP(s,q,j) + gn_pi * PhiP(s,q,j))
                                   + st * phi_pi * PhiP(s,q,j);
                    A_pp[i*nlp + j] += wq * v;
                }}
                // pn
                for (std::int64_t j=0; j<nln; ++j) {{
                    const double v = kappa_neg * k_neg * phi_pi * GnN(s,q,j)
                                   - kappa_pos * k_pos * gn_pi * PhiN(s,q,j)
                                   - st * phi_pi * PhiN(s,q,j);
                    A_pn[i*nln + j] += wq * v;
                }}
            }}

            for (std::int64_t i=0; i<nln; ++i) {{
                const double phi_ni = PhiN(s,q,i);
                const double gn_ni  = GnN(s,q,i);
                // np
                for (std::int64_t j=0; j<nlp; ++j) {{
                    const double v = -kappa_pos * k_pos * phi_ni * GnP(s,q,j)
                                   + kappa_neg * k_neg * gn_ni * PhiP(s,q,j)
                                   - st * phi_ni * PhiP(s,q,j);
                    A_np[i*nlp + j] += wq * v;
                }}
                // nn
                for (std::int64_t j=0; j<nln; ++j) {{
                    const double v = -kappa_neg * k_neg * (phi_ni * GnN(s,q,j) + gn_ni * PhiN(s,q,j))
                                   + st * phi_ni * PhiN(s,q,j);
                    A_nn[i*nln + j] += wq * v;
                }}
            }}
        }}

        // Scatter pp + pn
        for (std::int64_t i=0; i<nlp; ++i) {{
            const std::int64_t gi = gdP(s,i);
            for (std::int64_t j=0; j<nlp; ++j) {{
                R(out)=gi; C(out)=gdP(s,j); D(out)=A_pp[i*nlp + j]; ++out;
            }}
            for (std::int64_t j=0; j<nln; ++j) {{
                R(out)=gi; C(out)=gdN(s,j); D(out)=A_pn[i*nln + j]; ++out;
            }}
        }}
        // Scatter np + nn
        for (std::int64_t i=0; i<nln; ++i) {{
            const std::int64_t gi = gdN(s,i);
            for (std::int64_t j=0; j<nlp; ++j) {{
                R(out)=gi; C(out)=gdP(s,j); D(out)=A_np[i*nlp + j]; ++out;
            }}
            for (std::int64_t j=0; j<nln; ++j) {{
                R(out)=gi; C(out)=gdN(s,j); D(out)=A_nn[i*nln + j]; ++out;
            }}
        }}
    }}

    return py::make_tuple(rows, cols, data);
}}

py::tuple stokes_nitsche_triplets(
    py::array_t<std::int64_t, py::array::c_style | py::array::forcecast> gd_pos,
    py::array_t<std::int64_t, py::array::c_style | py::array::forcecast> gd_neg,
    py::array_t<double, py::array::c_style | py::array::forcecast> Uvec_p,
    py::array_t<double, py::array::c_style | py::array::forcecast> T_p,
    py::array_t<double, py::array::c_style | py::array::forcecast> Uvec_n,
    py::array_t<double, py::array::c_style | py::array::forcecast> T_n,
    py::array_t<double, py::array::c_style | py::array::forcecast> qw,
    py::array_t<double, py::array::c_style | py::array::forcecast> stab,
    double kappa_pos,
    double kappa_neg
) {{
    auto gdP = gd_pos.unchecked<2>();
    auto gdN = gd_neg.unchecked<2>();
    auto UP  = Uvec_p.unchecked<4>(); // (seg,q,lp,2)
    auto TP  = T_p.unchecked<4>();
    auto UN  = Uvec_n.unchecked<4>();
    auto TN  = T_n.unchecked<4>();
    auto W   = qw.unchecked<2>();
    auto St  = stab.unchecked<1>();

    const std::int64_t n_seg = gdP.shape(0);
    const std::int64_t nlp = gdP.shape(1);
    const std::int64_t nln = gdN.shape(1);
    const std::int64_t n_q = W.shape(1);

    const std::int64_t ntrip_per_seg = nlp*nlp + nlp*nln + nln*nlp + nln*nln;
    const std::int64_t ntrip = n_seg * ntrip_per_seg;

    py::array_t<std::int64_t> rows(ntrip);
    py::array_t<std::int64_t> cols(ntrip);
    py::array_t<double> data(ntrip);
    auto R = rows.mutable_unchecked<1>();
    auto C = cols.mutable_unchecked<1>();
    auto D = data.mutable_unchecked<1>();

    std::int64_t out = 0;
    for (std::int64_t s=0; s<n_seg; ++s) {{
        const double st = St(s);
        std::vector<double> A_pp(nlp*nlp, 0.0);
        std::vector<double> A_pn(nlp*nln, 0.0);
        std::vector<double> A_np(nln*nlp, 0.0);
        std::vector<double> A_nn(nln*nln, 0.0);

        for (std::int64_t q=0; q<n_q; ++q) {{
            const double wq = W(s,q);
            if (wq == 0.0) continue;

            // Term 1: avg_traction(u) · (v_neg - v_pos)
            for (std::int64_t i=0; i<nlp; ++i) {{
                const double uxi = UP(s,q,i,0);
                const double uyi = UP(s,q,i,1);
                for (std::int64_t j=0; j<nlp; ++j) {{
                    const double txj = TP(s,q,j,0);
                    const double tyj = TP(s,q,j,1);
                    A_pp[i*nlp + j] += wq * (-kappa_pos) * (uxi*txj + uyi*tyj);
                }}
                for (std::int64_t j=0; j<nln; ++j) {{
                    const double txj = TN(s,q,j,0);
                    const double tyj = TN(s,q,j,1);
                    A_pn[i*nln + j] += wq * (-kappa_neg) * (uxi*txj + uyi*tyj);
                }}
            }}
            for (std::int64_t i=0; i<nln; ++i) {{
                const double uxi = UN(s,q,i,0);
                const double uyi = UN(s,q,i,1);
                for (std::int64_t j=0; j<nlp; ++j) {{
                    const double txj = TP(s,q,j,0);
                    const double tyj = TP(s,q,j,1);
                    A_np[i*nlp + j] += wq * (kappa_pos) * (uxi*txj + uyi*tyj);
                }}
                for (std::int64_t j=0; j<nln; ++j) {{
                    const double txj = TN(s,q,j,0);
                    const double tyj = TN(s,q,j,1);
                    A_nn[i*nln + j] += wq * (kappa_neg) * (uxi*txj + uyi*tyj);
                }}
            }}

            // Term 2: avg_traction(v) · (u_neg - u_pos)
            for (std::int64_t i=0; i<nlp; ++i) {{
                const double txi = TP(s,q,i,0);
                const double tyi = TP(s,q,i,1);
                for (std::int64_t j=0; j<nlp; ++j) {{
                    const double uxj = UP(s,q,j,0);
                    const double uyj = UP(s,q,j,1);
                    A_pp[i*nlp + j] += wq * (-kappa_pos) * (txi*uxj + tyi*uyj);
                }}
                for (std::int64_t j=0; j<nln; ++j) {{
                    const double uxj = UN(s,q,j,0);
                    const double uyj = UN(s,q,j,1);
                    A_pn[i*nln + j] += wq * (kappa_pos) * (txi*uxj + tyi*uyj);
                }}
            }}
            for (std::int64_t i=0; i<nln; ++i) {{
                const double txi = TN(s,q,i,0);
                const double tyi = TN(s,q,i,1);
                for (std::int64_t j=0; j<nlp; ++j) {{
                    const double uxj = UP(s,q,j,0);
                    const double uyj = UP(s,q,j,1);
                    A_np[i*nlp + j] += wq * (-kappa_neg) * (txi*uxj + tyi*uyj);
                }}
                for (std::int64_t j=0; j<nln; ++j) {{
                    const double uxj = UN(s,q,j,0);
                    const double uyj = UN(s,q,j,1);
                    A_nn[i*nln + j] += wq * (kappa_neg) * (txi*uxj + tyi*uyj);
                }}
            }}

            // Penalty
            for (std::int64_t i=0; i<nlp; ++i) {{
                const double uxi = UP(s,q,i,0);
                const double uyi = UP(s,q,i,1);
                for (std::int64_t j=0; j<nlp; ++j) {{
                    const double uxj = UP(s,q,j,0);
                    const double uyj = UP(s,q,j,1);
                    A_pp[i*nlp + j] += wq * st * (uxi*uxj + uyi*uyj);
                }}
                for (std::int64_t j=0; j<nln; ++j) {{
                    const double uxj = UN(s,q,j,0);
                    const double uyj = UN(s,q,j,1);
                    A_pn[i*nln + j] += wq * (-st) * (uxi*uxj + uyi*uyj);
                }}
            }}
            for (std::int64_t i=0; i<nln; ++i) {{
                const double uxi = UN(s,q,i,0);
                const double uyi = UN(s,q,i,1);
                for (std::int64_t j=0; j<nlp; ++j) {{
                    const double uxj = UP(s,q,j,0);
                    const double uyj = UP(s,q,j,1);
                    A_np[i*nlp + j] += wq * (-st) * (uxi*uxj + uyi*uyj);
                }}
                for (std::int64_t j=0; j<nln; ++j) {{
                    const double uxj = UN(s,q,j,0);
                    const double uyj = UN(s,q,j,1);
                    A_nn[i*nln + j] += wq * st * (uxi*uxj + uyi*uyj);
                }}
            }}
        }}

        for (std::int64_t i=0; i<nlp; ++i) {{
            const std::int64_t gi = gdP(s,i);
            for (std::int64_t j=0; j<nlp; ++j) {{
                R(out)=gi; C(out)=gdP(s,j); D(out)=A_pp[i*nlp + j]; ++out;
            }}
            for (std::int64_t j=0; j<nln; ++j) {{
                R(out)=gi; C(out)=gdN(s,j); D(out)=A_pn[i*nln + j]; ++out;
            }}
        }}
        for (std::int64_t i=0; i<nln; ++i) {{
            const std::int64_t gi = gdN(s,i);
            for (std::int64_t j=0; j<nlp; ++j) {{
                R(out)=gi; C(out)=gdP(s,j); D(out)=A_np[i*nlp + j]; ++out;
            }}
            for (std::int64_t j=0; j<nln; ++j) {{
                R(out)=gi; C(out)=gdN(s,j); D(out)=A_nn[i*nln + j]; ++out;
            }}
        }}
    }}

    return py::make_tuple(rows, cols, data);
}}

py::tuple mortar_triplets(
    py::array_t<std::int64_t, py::array::c_style | py::array::forcecast> lam_ids,
    py::array_t<std::int64_t, py::array::c_style | py::array::forcecast> gd_pos,
    py::array_t<std::int64_t, py::array::c_style | py::array::forcecast> gd_neg,
    py::array_t<double, py::array::c_style | py::array::forcecast> mu,
    py::array_t<double, py::array::c_style | py::array::forcecast> phi_p,
    py::array_t<double, py::array::c_style | py::array::forcecast> phi_n,
    py::array_t<double, py::array::c_style | py::array::forcecast> qw
) {{
    auto Lam  = lam_ids.unchecked<2>();
    auto gdP  = gd_pos.unchecked<2>();
    auto gdN  = gd_neg.unchecked<2>();
    auto Mu   = mu.unchecked<3>();   // (seg,q,2)
    auto PhiP = phi_p.unchecked<3>(); // (seg,q,lp)
    auto PhiN = phi_n.unchecked<3>(); // (seg,q,ln)
    auto W    = qw.unchecked<2>();

    const std::int64_t n_seg = gdP.shape(0);
    const std::int64_t nlp = gdP.shape(1);
    const std::int64_t nln = gdN.shape(1);
    const std::int64_t n_q = W.shape(1);

    const std::int64_t ntrip_p = n_seg * (2 * nlp);
    const std::int64_t ntrip_n = n_seg * (2 * nln);

    py::array_t<std::int64_t> rows_p(ntrip_p);
    py::array_t<std::int64_t> cols_p(ntrip_p);
    py::array_t<double> data_p(ntrip_p);
    py::array_t<std::int64_t> rows_n(ntrip_n);
    py::array_t<std::int64_t> cols_n(ntrip_n);
    py::array_t<double> data_n(ntrip_n);
    auto Rp = rows_p.mutable_unchecked<1>();
    auto Cp = cols_p.mutable_unchecked<1>();
    auto Dp = data_p.mutable_unchecked<1>();
    auto Rn = rows_n.mutable_unchecked<1>();
    auto Cn = cols_n.mutable_unchecked<1>();
    auto Dn = data_n.mutable_unchecked<1>();

    std::int64_t out_p = 0;
    std::int64_t out_n = 0;
    for (std::int64_t s=0; s<n_seg; ++s) {{
        std::vector<double> Bp0(nlp, 0.0), Bp1(nlp, 0.0);
        std::vector<double> Bn0(nln, 0.0), Bn1(nln, 0.0);

        for (std::int64_t q=0; q<n_q; ++q) {{
            const double wq = W(s,q);
            if (wq == 0.0) continue;
            const double mu0 = Mu(s,q,0);
            const double mu1 = Mu(s,q,1);
            for (std::int64_t j=0; j<nlp; ++j) {{
                const double val = PhiP(s,q,j);
                Bp0[j] += wq * mu0 * val;
                Bp1[j] += wq * mu1 * val;
            }}
            for (std::int64_t j=0; j<nln; ++j) {{
                const double val = PhiN(s,q,j);
                Bn0[j] += wq * mu0 * val;
                Bn1[j] += wq * mu1 * val;
            }}
        }}

        const std::int64_t lam0 = Lam(s,0);
        const std::int64_t lam1 = Lam(s,1);
        for (std::int64_t j=0; j<nlp; ++j) {{
            Rp(out_p)=lam0; Cp(out_p)=gdP(s,j); Dp(out_p)=Bp0[j]; ++out_p;
        }}
        for (std::int64_t j=0; j<nlp; ++j) {{
            Rp(out_p)=lam1; Cp(out_p)=gdP(s,j); Dp(out_p)=Bp1[j]; ++out_p;
        }}

        for (std::int64_t j=0; j<nln; ++j) {{
            Rn(out_n)=lam0; Cn(out_n)=gdN(s,j); Dn(out_n)=Bn0[j]; ++out_n;
        }}
        for (std::int64_t j=0; j<nln; ++j) {{
            Rn(out_n)=lam1; Cn(out_n)=gdN(s,j); Dn(out_n)=Bn1[j]; ++out_n;
        }}
    }}

    return py::make_tuple(rows_p, cols_p, data_p, rows_n, cols_n, data_n);
}}

PYBIND11_MODULE({module_name}, m) {{
    m.attr(\"CODEGEN_ABI\") = CODEGEN_ABI;
    m.def(\"poisson_nitsche_triplets\", &poisson_nitsche_triplets);
    m.def(\"stokes_nitsche_triplets\", &stokes_nitsche_triplets);
    m.def(\"mortar_triplets\", &mortar_triplets);
}}
"""


def _load_cpp() -> Any:
    global _CPP_MODULE
    if _CPP_MODULE is not None:
        return _CPP_MODULE

    cache_dir = _cache_dir()
    suffix = sysconfig.get_config_var("EXT_SUFFIX") or ".so"

    # Hash by ABI string and source content to keep modules immutable.
    module_stub = "_pycutfem_nonmatching_cpp"
    src_probe = _cpp_source(module_stub)
    h = hashlib.sha256(src_probe.encode("utf-8")).hexdigest()[:16]
    module_name = f"{module_stub}_{h}"
    source_path = cache_dir / f"{module_name}.cpp"
    built_module = cache_dir / f"{module_name}{suffix}"

    if not built_module.exists():
        source_path.write_text(_cpp_source(module_name), encoding="utf-8")
        compile_extension(module_name, source_path, cache_dir)

    spec = importlib.util.spec_from_file_location(module_name, built_module)
    if not spec or not spec.loader:  # pragma: no cover
        raise ImportError(f"Could not load C++ extension at {built_module}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore[arg-type]
    if getattr(mod, "CODEGEN_ABI", None) != CODEGEN_ABI_NONMATCHING_CPP:  # pragma: no cover
        raise RuntimeError("Loaded nonmatching C++ extension has unexpected ABI.")

    _CPP_MODULE = mod
    return mod


def _interface_quadrature(interface: NonMatchingInterface, quad_order: int) -> tuple[np.ndarray, np.ndarray]:
    xi, w_ref = gauss_legendre(int(quad_order))
    xi = np.asarray(xi, dtype=float)
    w_ref = np.asarray(w_ref, dtype=float)

    P0 = np.asarray(interface.P0, dtype=float)
    P1 = np.asarray(interface.P1, dtype=float)
    mid = 0.5 * (P0 + P1)
    half = 0.5 * (P1 - P0)
    seg_J = np.linalg.norm(half, axis=1)
    qpts = mid[:, None, :] + xi[None, :, None] * half[:, None, :]
    qw = w_ref[None, :] * seg_J[:, None]
    return qpts, qw


def assemble_poisson_nitsche_interface_matrix(
    *,
    interface: NonMatchingInterface,
    dh_neg: DofHandler,
    dh_pos: DofHandler,
    field: str = "u",
    k_neg: float = 1.0,
    k_pos: float = 1.0,
    gamma: float = 20.0,
    quad_order: int | None = None,
) -> sp.csr_matrix:
    if interface.n_segments() <= 0:
        n_total = int(dh_pos.total_dofs) + int(dh_neg.total_dofs)
        return sp.csr_matrix((n_total, n_total), dtype=float)

    if quad_order is None:
        p_pos = _field_order(dh_pos, field)
        p_neg = _field_order(dh_neg, field)
        quad_order = int(2 * max(p_pos, p_neg) + 2)

    qpts, qw = _interface_quadrature(interface, int(quad_order))

    k_pos = float(k_pos)
    k_neg = float(k_neg)
    denom = k_pos + k_neg
    if denom <= 0.0:
        raise ValueError("k_pos + k_neg must be > 0 for Nitsche weights.")
    kappa_pos = k_neg / denom
    kappa_neg = k_pos / denom

    n_pos = int(dh_pos.total_dofs)
    n_neg = int(dh_neg.total_dofs)
    n_total = n_pos + n_neg

    me_pos = dh_pos.mixed_element
    me_neg = dh_neg.mixed_element
    mesh_pos = interface.mesh_pos
    mesh_neg = interface.mesh_neg

    n_seg = interface.n_segments()
    gd_pos0 = np.asarray(dh_pos.get_elemental_dofs(int(interface.pos_elem_ids[0])), dtype=np.int64)
    gd_neg0 = np.asarray(dh_neg.get_elemental_dofs(int(interface.neg_elem_ids[0])), dtype=np.int64)
    nlp = int(gd_pos0.size)
    nln = int(gd_neg0.size)

    gd_pos = np.empty((n_seg, nlp), dtype=np.int64)
    gd_neg = np.empty((n_seg, nln), dtype=np.int64)
    stab = np.empty(n_seg, dtype=np.float64)

    phi_p = np.zeros((n_seg, qpts.shape[1], nlp), dtype=np.float64)
    gn_p = np.zeros_like(phi_p)
    phi_n = np.zeros((n_seg, qpts.shape[1], nln), dtype=np.float64)
    gn_n = np.zeros_like(phi_n)

    for s in range(n_seg):
        pos_eid = int(interface.pos_elem_ids[s])
        neg_eid = int(interface.neg_elem_ids[s])
        gd_p = np.asarray(dh_pos.get_elemental_dofs(pos_eid), dtype=np.int64)
        gd_n = np.asarray(dh_neg.get_elemental_dofs(neg_eid), dtype=np.int64)
        if gd_p.size != nlp or gd_n.size != nln:
            raise ValueError("C++ backend currently requires constant local DOF counts per segment.")
        gd_pos[s, :] = gd_p
        gd_neg[s, :] = gd_n + n_pos

        h = float(min(interface.h_pos[s], interface.h_neg[s]) or 0.0)
        if h <= 0.0:
            h = 1.0
        stab[s] = float(gamma) * (k_pos + k_neg) / h

        n_vec = np.asarray(interface.n[s], dtype=float)
        for q in range(qpts.shape[1]):
            xq = np.asarray(qpts[s, q], dtype=float)
            wq = float(qw[s, q])
            if wq == 0.0:
                continue

            xi_p, eta_p = transform.inverse_mapping(mesh_pos, pos_eid, xq)
            Jp = transform.jacobian(mesh_pos, pos_eid, (float(xi_p), float(eta_p)))
            Jip = np.linalg.inv(Jp)
            phi = np.asarray(me_pos.basis(field, float(xi_p), float(eta_p)), dtype=float).ravel()
            grad = np.asarray(me_pos.grad_basis(field, float(xi_p), float(eta_p)), dtype=float) @ Jip
            phi_p[s, q, :] = phi
            gn_p[s, q, :] = grad @ n_vec

            xi_nq, eta_nq = transform.inverse_mapping(mesh_neg, neg_eid, xq)
            Jn = transform.jacobian(mesh_neg, neg_eid, (float(xi_nq), float(eta_nq)))
            Jin = np.linalg.inv(Jn)
            phi = np.asarray(me_neg.basis(field, float(xi_nq), float(eta_nq)), dtype=float).ravel()
            grad = np.asarray(me_neg.grad_basis(field, float(xi_nq), float(eta_nq)), dtype=float) @ Jin
            phi_n[s, q, :] = phi
            gn_n[s, q, :] = grad @ n_vec

    mod = _load_cpp()
    rows, cols, data = mod.poisson_nitsche_triplets(gd_pos, gd_neg, phi_p, gn_p, phi_n, gn_n, qw, stab, kappa_pos, kappa_neg, k_pos, k_neg)
    K = sp.coo_matrix((np.asarray(data, float), (np.asarray(rows, np.int64), np.asarray(cols, np.int64))), shape=(n_total, n_total))
    K.sum_duplicates()
    return K.tocsr()


def assemble_stokes_nitsche_interface_matrix(
    *,
    interface: NonMatchingInterface,
    dh_neg: DofHandler,
    dh_pos: DofHandler,
    mu_neg: float,
    mu_pos: float,
    gamma: float = 20.0,
    quad_order: int | None = None,
    u_fields: tuple[str, str] = ("ux", "uy"),
    p_field: str = "p",
) -> sp.csr_matrix:
    if interface.n_segments() <= 0:
        n_total = int(dh_pos.total_dofs) + int(dh_neg.total_dofs)
        return sp.csr_matrix((n_total, n_total), dtype=float)

    mu_pos = float(mu_pos)
    mu_neg = float(mu_neg)
    denom = mu_pos + mu_neg
    if denom <= 0.0:
        raise ValueError("mu_pos + mu_neg must be > 0.")
    kappa_pos = mu_neg / denom
    kappa_neg = mu_pos / denom

    if quad_order is None:
        p_u = max(_field_order(dh_pos, u_fields[0]), _field_order(dh_neg, u_fields[0]))
        quad_order = int(2 * p_u + 2)

    qpts, qw = _interface_quadrature(interface, int(quad_order))

    n_pos = int(dh_pos.total_dofs)
    n_neg = int(dh_neg.total_dofs)
    n_total = n_pos + n_neg

    me_pos = dh_pos.mixed_element
    me_neg = dh_neg.mixed_element
    mesh_pos = interface.mesh_pos
    mesh_neg = interface.mesh_neg

    n_seg = interface.n_segments()
    gd_pos0 = np.asarray(dh_pos.get_elemental_dofs(int(interface.pos_elem_ids[0])), dtype=np.int64)
    gd_neg0 = np.asarray(dh_neg.get_elemental_dofs(int(interface.neg_elem_ids[0])), dtype=np.int64)
    nlp = int(gd_pos0.size)
    nln = int(gd_neg0.size)

    gd_pos = np.empty((n_seg, nlp), dtype=np.int64)
    gd_neg = np.empty((n_seg, nln), dtype=np.int64)
    stab = np.empty(n_seg, dtype=np.float64)

    Uvec_p = np.zeros((n_seg, qpts.shape[1], nlp, 2), dtype=np.float64)
    Uvec_n = np.zeros((n_seg, qpts.shape[1], nln, 2), dtype=np.float64)
    T_p = np.zeros((n_seg, qpts.shape[1], nlp, 2), dtype=np.float64)
    T_n = np.zeros((n_seg, qpts.shape[1], nln, 2), dtype=np.float64)

    for s in range(n_seg):
        pos_eid = int(interface.pos_elem_ids[s])
        neg_eid = int(interface.neg_elem_ids[s])
        gd_p = np.asarray(dh_pos.get_elemental_dofs(pos_eid), dtype=np.int64)
        gd_n = np.asarray(dh_neg.get_elemental_dofs(neg_eid), dtype=np.int64)
        if gd_p.size != nlp or gd_n.size != nln:
            raise ValueError("C++ backend currently requires constant local DOF counts per segment.")
        gd_pos[s, :] = gd_p
        gd_neg[s, :] = gd_n + n_pos

        h = float(min(interface.h_pos[s], interface.h_neg[s]) or 0.0)
        if h <= 0.0:
            h = 1.0
        stab[s] = float(gamma) * (mu_pos + mu_neg) / h

        n_vec = np.asarray(interface.n[s], dtype=float)
        nx, ny = float(n_vec[0]), float(n_vec[1])
        for q in range(qpts.shape[1]):
            xq = np.asarray(qpts[s, q], dtype=float)
            wq = float(qw[s, q])
            if wq == 0.0:
                continue

            # POS
            xi_p, eta_p = transform.inverse_mapping(mesh_pos, pos_eid, xq)
            Jp = transform.jacobian(mesh_pos, pos_eid, (float(xi_p), float(eta_p)))
            Jip = np.linalg.inv(Jp)
            phi_ux_p = np.asarray(me_pos.basis(u_fields[0], float(xi_p), float(eta_p)), dtype=float).ravel()
            phi_uy_p = np.asarray(me_pos.basis(u_fields[1], float(xi_p), float(eta_p)), dtype=float).ravel()
            phi_p_p = np.asarray(me_pos.basis(p_field, float(xi_p), float(eta_p)), dtype=float).ravel()
            g_ux_p = np.asarray(me_pos.grad_basis(u_fields[0], float(xi_p), float(eta_p)), dtype=float) @ Jip
            g_uy_p = np.asarray(me_pos.grad_basis(u_fields[1], float(xi_p), float(eta_p)), dtype=float) @ Jip

            Uvec_p[s, q, :, 0] = phi_ux_p
            Uvec_p[s, q, :, 1] = phi_uy_p

            dux_dx = g_ux_p[:, 0]
            dux_dy = g_ux_p[:, 1]
            duy_dx = g_uy_p[:, 0]
            duy_dy = g_uy_p[:, 1]
            tp_x = np.zeros(nlp, dtype=np.float64)
            tp_y = np.zeros(nlp, dtype=np.float64)
            tp_x += 2.0 * mu_pos * (dux_dx * nx + 0.5 * dux_dy * ny)
            tp_y += 2.0 * mu_pos * (0.5 * dux_dy * nx)
            tp_x += 2.0 * mu_pos * (0.5 * duy_dx * ny)
            tp_y += 2.0 * mu_pos * (0.5 * duy_dx * nx + duy_dy * ny)
            tp_x += -phi_p_p * nx
            tp_y += -phi_p_p * ny
            T_p[s, q, :, 0] = tp_x
            T_p[s, q, :, 1] = tp_y

            # NEG
            xi_nq, eta_nq = transform.inverse_mapping(mesh_neg, neg_eid, xq)
            Jn = transform.jacobian(mesh_neg, neg_eid, (float(xi_nq), float(eta_nq)))
            Jin = np.linalg.inv(Jn)
            phi_ux_n = np.asarray(me_neg.basis(u_fields[0], float(xi_nq), float(eta_nq)), dtype=float).ravel()
            phi_uy_n = np.asarray(me_neg.basis(u_fields[1], float(xi_nq), float(eta_nq)), dtype=float).ravel()
            phi_p_n = np.asarray(me_neg.basis(p_field, float(xi_nq), float(eta_nq)), dtype=float).ravel()
            g_ux_n = np.asarray(me_neg.grad_basis(u_fields[0], float(xi_nq), float(eta_nq)), dtype=float) @ Jin
            g_uy_n = np.asarray(me_neg.grad_basis(u_fields[1], float(xi_nq), float(eta_nq)), dtype=float) @ Jin

            Uvec_n[s, q, :, 0] = phi_ux_n
            Uvec_n[s, q, :, 1] = phi_uy_n

            dux_dx = g_ux_n[:, 0]
            dux_dy = g_ux_n[:, 1]
            duy_dx = g_uy_n[:, 0]
            duy_dy = g_uy_n[:, 1]
            tn_x = np.zeros(nln, dtype=np.float64)
            tn_y = np.zeros(nln, dtype=np.float64)
            tn_x += 2.0 * mu_neg * (dux_dx * nx + 0.5 * dux_dy * ny)
            tn_y += 2.0 * mu_neg * (0.5 * dux_dy * nx)
            tn_x += 2.0 * mu_neg * (0.5 * duy_dx * ny)
            tn_y += 2.0 * mu_neg * (0.5 * duy_dx * nx + duy_dy * ny)
            tn_x += -phi_p_n * nx
            tn_y += -phi_p_n * ny
            T_n[s, q, :, 0] = tn_x
            T_n[s, q, :, 1] = tn_y

    mod = _load_cpp()
    rows, cols, data = mod.stokes_nitsche_triplets(gd_pos, gd_neg, Uvec_p, T_p, Uvec_n, T_n, qw, stab, kappa_pos, kappa_neg)
    K = sp.coo_matrix((np.asarray(data, float), (np.asarray(rows, np.int64), np.asarray(cols, np.int64))), shape=(n_total, n_total))
    K.sum_duplicates()
    return K.tocsr()


def assemble_poisson_mortar_coupling(
    *,
    interface: NonMatchingInterface,
    dh_neg: DofHandler,
    dh_pos: DofHandler,
    field: str = "u",
    p_lambda: int | None = None,
    master: str = "auto",
    quad_order: int | None = None,
) -> MortarCoupling:
    if interface.n_segments() <= 0:
        n_lambda = 0
        return MortarCoupling(
            B_pos=sp.csr_matrix((n_lambda, int(dh_pos.total_dofs))),
            B_neg=sp.csr_matrix((n_lambda, int(dh_neg.total_dofs))),
            p_lambda=int(p_lambda or 0),
        )

    if p_lambda is None:
        p_lambda = 1
    p_lambda = int(p_lambda)
    if p_lambda != 1:
        raise NotImplementedError("Mortar coupling currently supports p_lambda=1 only.")

    master = str(master).strip().lower()
    if master not in {"auto", "pos", "neg"}:
        raise ValueError("master must be 'auto', 'pos', or 'neg'")

    if quad_order is None:
        p_pos = _field_order(dh_pos, field)
        p_neg = _field_order(dh_neg, field)
        quad_order = int(2 * max(p_pos, p_neg, p_lambda) + 2)

    qpts, qw = _interface_quadrature(interface, int(quad_order))

    n_pos = int(dh_pos.total_dofs)
    n_neg = int(dh_neg.total_dofs)
    n_seg = interface.n_segments()
    mesh_pos = interface.mesh_pos
    mesh_neg = interface.mesh_neg

    def _edge_nodes(mesh, edge_ids: np.ndarray) -> np.ndarray:
        nodes: set[int] = set()
        for gid in np.unique(np.asarray(edge_ids, dtype=int)):
            e = mesh.edge(int(gid))
            nodes.update(int(n) for n in e.nodes)
        node_ids = np.fromiter(nodes, dtype=int)
        d0 = np.asarray(interface.P1[0] - interface.P0[0], dtype=float)
        t = d0 / max(float(np.linalg.norm(d0)), 1.0e-16)
        s = mesh.nodes_x_y_pos[node_ids] @ t
        return node_ids[np.argsort(s)]

    neg_nodes = _edge_nodes(mesh_neg, interface.neg_edge_ids)
    pos_nodes = _edge_nodes(mesh_pos, interface.pos_edge_ids)
    if master == "auto":
        master = "neg" if neg_nodes.size <= pos_nodes.size else "pos"

    if master == "neg":
        mesh_master = mesh_neg
        master_edge_ids = interface.neg_edge_ids
        master_nodes = neg_nodes
    else:
        mesh_master = mesh_pos
        master_edge_ids = interface.pos_edge_ids
        master_nodes = pos_nodes

    node_to_lam = {int(n): i for i, n in enumerate(master_nodes.tolist())}
    n_lambda = int(master_nodes.size)

    me_pos = dh_pos.mixed_element
    me_neg = dh_neg.mixed_element

    gd_pos0 = np.asarray(dh_pos.get_elemental_dofs(int(interface.pos_elem_ids[0])), dtype=np.int64)
    gd_neg0 = np.asarray(dh_neg.get_elemental_dofs(int(interface.neg_elem_ids[0])), dtype=np.int64)
    nlp = int(gd_pos0.size)
    nln = int(gd_neg0.size)

    gd_pos = np.empty((n_seg, nlp), dtype=np.int64)
    gd_neg = np.empty((n_seg, nln), dtype=np.int64)
    lam_ids = np.empty((n_seg, 2), dtype=np.int64)

    phi_p = np.zeros((n_seg, qpts.shape[1], nlp), dtype=np.float64)
    phi_n = np.zeros((n_seg, qpts.shape[1], nln), dtype=np.float64)
    mu = np.zeros((n_seg, qpts.shape[1], 2), dtype=np.float64)

    for s in range(n_seg):
        pos_eid = int(interface.pos_elem_ids[s])
        neg_eid = int(interface.neg_elem_ids[s])
        gd_p = np.asarray(dh_pos.get_elemental_dofs(pos_eid), dtype=np.int64)
        gd_n = np.asarray(dh_neg.get_elemental_dofs(neg_eid), dtype=np.int64)
        if gd_p.size != nlp or gd_n.size != nln:
            raise ValueError("C++ backend currently requires constant local DOF counts per segment.")
        gd_pos[s, :] = gd_p
        gd_neg[s, :] = gd_n

        e_master = mesh_master.edge(int(master_edge_ids[s]))
        n0 = int(e_master.nodes[0])
        n1 = int(e_master.nodes[1])
        lam_ids[s, 0] = int(node_to_lam[n0])
        lam_ids[s, 1] = int(node_to_lam[n1])

        p0m = np.asarray(mesh_master.nodes_x_y_pos[n0], dtype=float)
        p1m = np.asarray(mesh_master.nodes_x_y_pos[n1], dtype=float)
        d = p1m - p0m
        L2 = float(np.dot(d, d)) or 1.0

        for q in range(qpts.shape[1]):
            xq = np.asarray(qpts[s, q], dtype=float)
            wq = float(qw[s, q])
            if wq == 0.0:
                continue
            r = float(np.dot(xq - p0m, d) / L2)
            r = min(1.0, max(0.0, r))
            xi_edge = 2.0 * r - 1.0
            mu[s, q, 0] = 0.5 * (1.0 - xi_edge)
            mu[s, q, 1] = 0.5 * (1.0 + xi_edge)

            xi_p, eta_p = transform.inverse_mapping(mesh_pos, pos_eid, xq)
            phi_p[s, q, :] = np.asarray(me_pos.basis(field, float(xi_p), float(eta_p)), dtype=float).ravel()

            xi_nq, eta_nq = transform.inverse_mapping(mesh_neg, neg_eid, xq)
            phi_n[s, q, :] = np.asarray(me_neg.basis(field, float(xi_nq), float(eta_nq)), dtype=float).ravel()

    mod = _load_cpp()
    rows_p, cols_p, data_p, rows_n, cols_n, data_n = mod.mortar_triplets(lam_ids, gd_pos, gd_neg, mu, phi_p, phi_n, qw)

    B_pos = sp.coo_matrix((np.asarray(data_p, float), (np.asarray(rows_p, np.int64), np.asarray(cols_p, np.int64))), shape=(n_lambda, n_pos))
    B_pos.sum_duplicates()
    B_neg = sp.coo_matrix((np.asarray(data_n, float), (np.asarray(rows_n, np.int64), np.asarray(cols_n, np.int64))), shape=(n_lambda, n_neg))
    B_neg.sum_duplicates()
    return MortarCoupling(B_pos=B_pos.tocsr(), B_neg=B_neg.tocsr(), p_lambda=p_lambda)
