# This file is auto-generated by pycutfem JIT – DO NOT EDIT
import numpy as np
import numba

CODEGEN_ABI = "2026-04-07-abi-dot-product-ghost-layout-v14"

import numba
import numpy as np
from pycutfem.jit.numba_helpers import (
    dot_grad_grad_mixed,
    contract_last_first,
    dot_mixed_const,
    dot_const_mixed,
    dot_vector_trial_grad_test,
    dot_mass_test_trial,
    dot_mass_trial_test,
    dot_grad_func_trial_vec,
    dot_trial_vec_grad_func,
    dot_vec_vec,
    dot_grad_grad_value,
    mul_scalar,
    dot_grad_basis_vector,
    vector_dot_grad_basis,
    vector_dot_grad_value,
    dot_grad_basis_with_grad_value,
    dot_grad_value_with_grad_basis,
    basis_dot_const_vector,
        const_vector_dot_basis,
        const_vector_dot_basis_1d,
        scalar_basis_times_vector,
        scalar_basis_times_vector_as_grad_tensor,
        matrix_times_scalar_basis,
        scalar_vector_outer_product,
        vector_trial_times_scalar_test,
        vector_test_times_scalar_trial,
        vector_vector_outer_product,
    dot_vec_grad_components,
    scalar_trial_times_grad_test,
    scalar_trial_times_basis_test,
    grad_trial_times_scalar_test,
    basis_trial_times_scalar_test,
    scale_mixed_basis_with_coeffs,
    trace_times_identity,
    identity_times_trace_matrix,
    columnwise_dot,
    hessian_dot_vector,
    vector_dot_hessian_basis,
    vector_dot_hessian_value,
    inner_rank2_value_rank2_basis,
    inner_rank2_basis_rank2_value,
    inner_grad_grad,
    inner_hessian_hessian,
    inner_grad_function_grad_test,
    inner_hessian_function_hessian_test,
    inner_mixed_grad_const,
    inner_grad_const_mixed,
    inner_grad_basis_grad_const,
    trace_matrix_value,
    trace_basis_tensor,
    trace_mixed_tensor,
    transpose_grad_tensor,
    transpose_mixed_grad_tensor,
    transpose_hessian_tensor,
    transpose_matrix,
    swap_mixed_basis_tensor,
    dot_value_with_grad,
    dot_grad_with_value,
    pushforward_d3,
    pushforward_d4,
    compute_physical_hessian,
    compute_physical_laplacian,
    load_variable_qp,
    gradient_qp,
    laplacian_qp,
    hessian_qp,
    ghost_grad_jump_penalty_scalar,
    ghost_grad_jump_penalty_vector,
    binary_add_generic,
    binary_add_3_4,
    binary_add_4_3,
    binary_sub_generic,
    binary_sub_3_4,
    binary_sub_4_3,
    scatter_tensor_to_union,
    pad_basis_to_union,
    pushforward_grad_to_union,
    contract_first_first
)
PARAM_ORDER = ['gdofs_map', 'node_coords', 'qp_phys', 'qw', 'detJ', 'J_inv', 'normals', 'b_ux', 'b_uy', 'g_p', 'g_ux', 'g_uy', 'jit_const_0', 'jit_const_1', 'jit_const_2', 'jit_const_3', 'jit_const_4', 'jit_const_5', 'jit_const_6', 'u_p_k_loc']
@numba.njit(parallel=True, fastmath=True, cache=True)
def kernel(
        gdofs_map, node_coords, qp_phys, qw, detJ, J_inv, normals, b_ux, b_uy, g_p, g_ux, g_uy, jit_const_0, jit_const_1, jit_const_2, jit_const_3, jit_const_4, jit_const_5, jit_const_6, u_p_k_loc
    ):
    num_elements        = qp_phys.shape[0]
    # n_dofs_per_element  = 27
    n_dofs_per_element  = gdofs_map.shape[1]            # 9 for volume, 15 on ghost edge
    # print(f"num_elements: {num_elements},n_dofs_per_element: {n_dofs_per_element}")
    # print(f"number of quadrature points: {qw.shape[1]}")

    K_values = np.zeros((num_elements, n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
    F_values = np.zeros((num_elements, n_dofs_per_element), dtype=np.float64)
    # Shape of the integrand that lands in “J”.
    # -------- functional accumulator ------------------------------------
    k = 0
    J_init = 0.0
    J     = J_init
    J_values = np.zeros((num_elements), dtype=np.float64)

    for e in numba.prange(num_elements):
        Ke = np.zeros((n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
        Fe = np.zeros(n_dofs_per_element, dtype=np.float64)
        J  = J_init.copy() if False else J_init

        n_union = gdofs_map.shape[1]

        u_p_k_loc_e = u_p_k_loc[e]

        for q in range(qw.shape[1]):
            x_q, w_q, J_inv_q = qp_phys[e, q], qw[e, q], J_inv[e, q]
            normal_q = normals[e, q] if normals is not None else np.zeros(2, dtype=np.float64)
            phi_q    = 0.0
            J_inv_q = J_inv[e,q]
            b_ux_q = b_ux[e,q]
            b_uy_q = b_uy[e,q]
            g_p_q = g_p[e,q]
            g_ux_q = g_ux[e,q]
            g_uy_q = g_uy[e,q]
            const_val_1 = jit_const_0.item()
            const_val_2 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_3 = const_val_1 * const_val_2
            J_inv_q = J_inv[e, q]
            phys_grad_basis_5  = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_4 = gradient_qp(u_p_k_loc_e, phys_grad_basis_5)
            basis_stack_6 = np.stack((b_ux[e, q], b_uy[e, q]))
            J_inv_q = J_inv[e, q]
            grad_loc_e_7 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_8 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_9 = np.stack((grad_loc_e_7, grad_loc_e_8))
            # Dot plan: basis-vector · basis-gradient
            dot_10 = dot_vec_grad_components(basis_stack_6, grad_stack_9, True, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_11 = contract_first_first(dot_10, grad_val_4, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_12 = mul_scalar(res_3, dot_11, np.float64)
            const_val_13 = jit_const_0.item()
            const_val_14 = jit_const_2.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_15 = const_val_13 * const_val_14
            J_inv_q = J_inv[e, q]
            phys_grad_basis_17  = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_16 = gradient_qp(u_p_k_loc_e, phys_grad_basis_17)
            basis_stack_18 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_19 = jit_const_3
            J_inv_q = J_inv[e, q]
            grad_loc_e_20 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_21 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_22 = np.stack((grad_loc_e_20, grad_loc_e_21))
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_23 = contract_last_first(const_np_arr_19, grad_stack_22, np.float64)
            # Dot plan: basis-vector · basis-gradient
            dot_24 = dot_vec_grad_components(basis_stack_18, dot_23, True, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_25 = contract_first_first(dot_24, grad_val_16, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_26 = mul_scalar(res_15, dot_25, np.float64)
            # Addition
            res_27 = binary_add_generic(res_12, res_26, np.float64)
            const_val_28 = jit_const_4.item()
            const_val_29 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_30 = const_val_28 * const_val_29
            const_np_arr_31 = jit_const_5
            J_inv_q = J_inv[e, q]
            phys_grad_basis_33  = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_32 = gradient_qp(u_p_k_loc_e, phys_grad_basis_33)
            # Dot: planner-driven const/value contraction
            dot_34 = contract_last_first(const_np_arr_31, grad_val_32, np.float64)
            basis_stack_35 = np.stack((b_ux[e, q], b_uy[e, q]))
            J_inv_q = J_inv[e, q]
            grad_loc_e_36 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_37 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_38 = np.stack((grad_loc_e_36, grad_loc_e_37))
            # Dot plan: basis-vector · basis-gradient
            dot_39 = dot_vec_grad_components(basis_stack_35, grad_stack_38, True, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_40 = contract_first_first(dot_39, dot_34, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_41 = mul_scalar(res_30, dot_40, np.float64)
            # Addition
            res_42 = binary_add_generic(res_27, res_41, np.float64)
            const_val_43 = jit_const_4.item()
            const_val_44 = jit_const_2.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_45 = const_val_43 * const_val_44
            const_np_arr_46 = jit_const_5
            J_inv_q = J_inv[e, q]
            phys_grad_basis_48  = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_47 = gradient_qp(u_p_k_loc_e, phys_grad_basis_48)
            # Dot: planner-driven const/value contraction
            dot_49 = contract_last_first(const_np_arr_46, grad_val_47, np.float64)
            basis_stack_50 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_51 = jit_const_3
            J_inv_q = J_inv[e, q]
            grad_loc_e_52 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_53 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_54 = np.stack((grad_loc_e_52, grad_loc_e_53))
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_55 = contract_last_first(const_np_arr_51, grad_stack_54, np.float64)
            # Dot plan: basis-vector · basis-gradient
            dot_56 = dot_vec_grad_components(basis_stack_50, dot_55, True, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_57 = contract_first_first(dot_56, dot_49, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_58 = mul_scalar(res_45, dot_57, np.float64)
            # Addition
            res_59 = binary_add_generic(res_42, res_58, np.float64)
            const_val_60 = jit_const_6.item()
            const_val_61 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_62 = const_val_60 * const_val_61
            J_inv_q = J_inv[e, q]
            phys_grad_basis_64  = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_63 = gradient_qp(u_p_k_loc_e, phys_grad_basis_64)
            const_np_arr_65 = jit_const_3
            # Dot: planner-driven const/value contraction
            dot_66 = contract_last_first(grad_val_63, const_np_arr_65, np.float64)
            basis_stack_67 = np.stack((b_ux[e, q], b_uy[e, q]))
            J_inv_q = J_inv[e, q]
            grad_loc_e_68 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_69 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_70 = np.stack((grad_loc_e_68, grad_loc_e_69))
            # Dot plan: basis-vector · basis-gradient
            dot_71 = dot_vec_grad_components(basis_stack_67, grad_stack_70, True, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_72 = contract_first_first(dot_71, dot_66, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_73 = mul_scalar(res_62, dot_72, np.float64)
            # Addition
            res_74 = binary_add_generic(res_59, res_73, np.float64)
            const_val_75 = jit_const_6.item()
            const_val_76 = jit_const_2.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_77 = const_val_75 * const_val_76
            J_inv_q = J_inv[e, q]
            phys_grad_basis_79  = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_78 = gradient_qp(u_p_k_loc_e, phys_grad_basis_79)
            const_np_arr_80 = jit_const_3
            # Dot: planner-driven const/value contraction
            dot_81 = contract_last_first(grad_val_78, const_np_arr_80, np.float64)
            basis_stack_82 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_83 = jit_const_3
            J_inv_q = J_inv[e, q]
            grad_loc_e_84 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_85 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_86 = np.stack((grad_loc_e_84, grad_loc_e_85))
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_87 = contract_last_first(const_np_arr_83, grad_stack_86, np.float64)
            # Dot plan: basis-vector · basis-gradient
            dot_88 = dot_vec_grad_components(basis_stack_82, dot_87, True, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_89 = contract_first_first(dot_88, dot_81, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_90 = mul_scalar(res_77, dot_89, np.float64)
            # Addition
            res_91 = binary_add_generic(res_74, res_90, np.float64)
            Ke += res_91 * w_q

        K_values[e] = Ke
        F_values[e] = Fe
        J_values[e] = J

    return K_values, F_values, J_values


def get_kernel(analytic_map):
    pass
    return kernel
