# This file is auto-generated by pycutfem JIT – DO NOT EDIT
import numpy as np
import numba

CODEGEN_ABI = "2026-04-07-abi-dot-product-ghost-layout-v14"

import numba
import numpy as np
from pycutfem.jit.numba_helpers import (
    dot_grad_grad_mixed,
    contract_last_first,
    dot_mixed_const,
    dot_const_mixed,
    dot_vector_trial_grad_test,
    dot_mass_test_trial,
    dot_mass_trial_test,
    dot_grad_func_trial_vec,
    dot_trial_vec_grad_func,
    dot_vec_vec,
    dot_grad_grad_value,
    mul_scalar,
    dot_grad_basis_vector,
    vector_dot_grad_basis,
    vector_dot_grad_value,
    dot_grad_basis_with_grad_value,
    dot_grad_value_with_grad_basis,
    basis_dot_const_vector,
        const_vector_dot_basis,
        const_vector_dot_basis_1d,
        scalar_basis_times_vector,
        scalar_basis_times_vector_as_grad_tensor,
        matrix_times_scalar_basis,
        scalar_vector_outer_product,
        vector_trial_times_scalar_test,
        vector_test_times_scalar_trial,
        vector_vector_outer_product,
    dot_vec_grad_components,
    scalar_trial_times_grad_test,
    scalar_trial_times_basis_test,
    grad_trial_times_scalar_test,
    basis_trial_times_scalar_test,
    scale_mixed_basis_with_coeffs,
    trace_times_identity,
    identity_times_trace_matrix,
    columnwise_dot,
    hessian_dot_vector,
    vector_dot_hessian_basis,
    vector_dot_hessian_value,
    inner_rank2_value_rank2_basis,
    inner_rank2_basis_rank2_value,
    inner_grad_grad,
    inner_hessian_hessian,
    inner_grad_function_grad_test,
    inner_hessian_function_hessian_test,
    inner_mixed_grad_const,
    inner_grad_const_mixed,
    inner_grad_basis_grad_const,
    trace_matrix_value,
    trace_basis_tensor,
    trace_mixed_tensor,
    transpose_grad_tensor,
    transpose_mixed_grad_tensor,
    transpose_hessian_tensor,
    transpose_matrix,
    swap_mixed_basis_tensor,
    dot_value_with_grad,
    dot_grad_with_value,
    pushforward_d3,
    pushforward_d4,
    compute_physical_hessian,
    compute_physical_laplacian,
    load_variable_qp,
    gradient_qp,
    laplacian_qp,
    hessian_qp,
    ghost_grad_jump_penalty_scalar,
    ghost_grad_jump_penalty_vector,
    binary_add_generic,
    binary_add_3_4,
    binary_add_4_3,
    binary_sub_generic,
    binary_sub_3_4,
    binary_sub_4_3,
    scatter_tensor_to_union,
    pad_basis_to_union,
    pushforward_grad_to_union,
    contract_first_first
)
PARAM_ORDER = ['gdofs_map', 'node_coords', 'qp_phys', 'qw', 'detJ', 'J_inv', 'normals', 'b_ux', 'b_uy', 'jit_const_0', 'jit_const_1', 'jit_const_10', 'jit_const_11', 'jit_const_2', 'jit_const_3', 'jit_const_4', 'jit_const_5', 'jit_const_6', 'jit_const_7', 'jit_const_8', 'jit_const_9', 'u_u_k_loc']
@numba.njit(parallel=True, fastmath=True, cache=True)
def kernel(
        gdofs_map, node_coords, qp_phys, qw, detJ, J_inv, normals, b_ux, b_uy, jit_const_0, jit_const_1, jit_const_10, jit_const_11, jit_const_2, jit_const_3, jit_const_4, jit_const_5, jit_const_6, jit_const_7, jit_const_8, jit_const_9, u_u_k_loc
    ):
    num_elements        = qp_phys.shape[0]
    # n_dofs_per_element  = 18
    n_dofs_per_element  = gdofs_map.shape[1]            # 9 for volume, 15 on ghost edge
    # print(f"num_elements: {num_elements},n_dofs_per_element: {n_dofs_per_element}")
    # print(f"number of quadrature points: {qw.shape[1]}")

    K_values = np.zeros((num_elements, n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
    F_values = np.zeros((num_elements, n_dofs_per_element), dtype=np.float64)
    # Shape of the integrand that lands in “J”.
    # -------- functional accumulator ------------------------------------
    k = 0
    J_init = 0.0
    J     = J_init
    J_values = np.zeros((num_elements), dtype=np.float64)

    for e in numba.prange(num_elements):
        Ke = np.zeros((n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
        Fe = np.zeros(n_dofs_per_element, dtype=np.float64)
        J  = J_init.copy() if False else J_init

        n_union = gdofs_map.shape[1]

        u_u_k_loc_e = u_u_k_loc[e]

        for q in range(qw.shape[1]):
            x_q, w_q, J_inv_q = qp_phys[e, q], qw[e, q], J_inv[e, q]
            normal_q = normals[e, q] if normals is not None else np.zeros(2, dtype=np.float64)
            phi_q    = 0.0
            J_inv_q = J_inv[e,q]
            b_ux_q = b_ux[e,q]
            b_uy_q = b_uy[e,q]
            const_val_1 = jit_const_0.item()
            const_val_2 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_3 = const_val_1 * const_val_2
            basis_stack_4 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_5 = jit_const_2
            # Dot plan: semantic basis rank-1 · value vector
            dot_6 = basis_dot_const_vector(basis_stack_4, const_np_arr_5, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_7 = mul_scalar(res_3, dot_6[0], np.float64)
            const_val_8 = jit_const_0.item()
            const_val_9 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_10 = const_val_8 * const_val_9
            basis_stack_11 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_12 = jit_const_4
            const_np_arr_13 = jit_const_2
            # Dot: planner-driven const/value contraction
            dot_14 = contract_last_first(const_np_arr_12, const_np_arr_13, np.float64)
            # Dot plan: semantic basis rank-1 · value vector
            dot_15 = basis_dot_const_vector(basis_stack_11, dot_14, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_16 = mul_scalar(res_10, dot_15[0], np.float64)
            # Addition
            res_17 = binary_add_generic(res_7, res_16, np.float64)
            const_val_18 = jit_const_0.item()
            const_val_19 = jit_const_5.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_20 = const_val_18 * const_val_19
            basis_stack_21 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_22 = jit_const_2
            const_np_arr_23 = jit_const_6
            # Dot: planner-driven const/value contraction
            dot_24 = contract_last_first(const_np_arr_22, const_np_arr_23, np.float64)
            # Dot plan: basis-vector · value-gradient
            dot_25 = basis_dot_const_vector(basis_stack_21, np.ravel(dot_24), np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_26 = mul_scalar(res_20, dot_25[0], np.float64)
            # Addition
            res_27 = binary_add_generic(res_17, res_26, np.float64)
            const_val_28 = jit_const_0.item()
            const_val_29 = jit_const_7.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_30 = const_val_28 * const_val_29
            basis_stack_31 = np.stack((b_ux[e, q], b_uy[e, q]))
            u_k_val_32 = np.zeros((2,), dtype=np.float64)
            val_comp_33 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_32[0] = val_comp_33
            val_comp_34 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_32[1] = val_comp_34
            # Dot plan: semantic basis rank-1 · value vector
            dot_35 = basis_dot_const_vector(basis_stack_31, u_k_val_32, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_36 = mul_scalar(res_30, dot_35[0], np.float64)
            # Addition
            res_37 = binary_add_generic(res_27, res_36, np.float64)
            const_val_38 = jit_const_0.item()
            const_val_39 = jit_const_8.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_40 = const_val_38 * const_val_39
            basis_stack_41 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_42 = jit_const_4
            u_k_val_43 = np.zeros((2,), dtype=np.float64)
            val_comp_44 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_43[0] = val_comp_44
            val_comp_45 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_43[1] = val_comp_45
            # Dot: planner-driven const/value contraction
            dot_46 = contract_last_first(const_np_arr_42, u_k_val_43, np.float64)
            # Dot plan: semantic basis rank-1 · value vector
            dot_47 = basis_dot_const_vector(basis_stack_41, dot_46, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_48 = mul_scalar(res_40, dot_47[0], np.float64)
            # Addition
            res_49 = binary_add_generic(res_37, res_48, np.float64)
            const_val_50 = jit_const_0.item()
            const_val_51 = jit_const_9.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_52 = const_val_50 * const_val_51
            basis_stack_53 = np.stack((b_ux[e, q], b_uy[e, q]))
            u_k_val_54 = np.zeros((2,), dtype=np.float64)
            val_comp_55 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_54[0] = val_comp_55
            val_comp_56 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_54[1] = val_comp_56
            const_np_arr_57 = jit_const_6
            # Dot: planner-driven const/value contraction
            dot_58 = contract_last_first(u_k_val_54, const_np_arr_57, np.float64)
            # Dot plan: basis-vector · value-gradient
            dot_59 = basis_dot_const_vector(basis_stack_53, np.ravel(dot_58), np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_60 = mul_scalar(res_52, dot_59[0], np.float64)
            # Addition
            res_61 = binary_add_generic(res_49, res_60, np.float64)
            const_val_62 = jit_const_10.item()
            const_val_63 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_64 = const_val_62 * const_val_63
            const_np_arr_65 = jit_const_4
            basis_stack_66 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_67 = contract_last_first(const_np_arr_65, basis_stack_66, np.float64)
            const_np_arr_68 = jit_const_2
            # Dot plan: semantic basis rank-1 · value vector
            dot_69 = basis_dot_const_vector(dot_67, const_np_arr_68, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_70 = mul_scalar(res_64, dot_69[0], np.float64)
            # Addition
            res_71 = binary_add_generic(res_61, res_70, np.float64)
            const_val_72 = jit_const_10.item()
            const_val_73 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_74 = const_val_72 * const_val_73
            const_np_arr_75 = jit_const_4
            basis_stack_76 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_77 = contract_last_first(const_np_arr_75, basis_stack_76, np.float64)
            const_np_arr_78 = jit_const_4
            const_np_arr_79 = jit_const_2
            # Dot: planner-driven const/value contraction
            dot_80 = contract_last_first(const_np_arr_78, const_np_arr_79, np.float64)
            # Dot plan: semantic basis rank-1 · value vector
            dot_81 = basis_dot_const_vector(dot_77, dot_80, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_82 = mul_scalar(res_74, dot_81[0], np.float64)
            # Addition
            res_83 = binary_add_generic(res_71, res_82, np.float64)
            const_val_84 = jit_const_10.item()
            const_val_85 = jit_const_5.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_86 = const_val_84 * const_val_85
            const_np_arr_87 = jit_const_4
            basis_stack_88 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_89 = contract_last_first(const_np_arr_87, basis_stack_88, np.float64)
            const_np_arr_90 = jit_const_2
            const_np_arr_91 = jit_const_6
            # Dot: planner-driven const/value contraction
            dot_92 = contract_last_first(const_np_arr_90, const_np_arr_91, np.float64)
            # Dot plan: basis-vector · value-gradient
            dot_93 = basis_dot_const_vector(dot_89, np.ravel(dot_92), np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_94 = mul_scalar(res_86, dot_93[0], np.float64)
            # Addition
            res_95 = binary_add_generic(res_83, res_94, np.float64)
            const_val_96 = jit_const_10.item()
            const_val_97 = jit_const_7.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_98 = const_val_96 * const_val_97
            const_np_arr_99 = jit_const_4
            basis_stack_100 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_101 = contract_last_first(const_np_arr_99, basis_stack_100, np.float64)
            u_k_val_102 = np.zeros((2,), dtype=np.float64)
            val_comp_103 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_102[0] = val_comp_103
            val_comp_104 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_102[1] = val_comp_104
            # Dot plan: semantic basis rank-1 · value vector
            dot_105 = basis_dot_const_vector(dot_101, u_k_val_102, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_106 = mul_scalar(res_98, dot_105[0], np.float64)
            # Addition
            res_107 = binary_add_generic(res_95, res_106, np.float64)
            const_val_108 = jit_const_10.item()
            const_val_109 = jit_const_8.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_110 = const_val_108 * const_val_109
            const_np_arr_111 = jit_const_4
            basis_stack_112 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_113 = contract_last_first(const_np_arr_111, basis_stack_112, np.float64)
            const_np_arr_114 = jit_const_4
            u_k_val_115 = np.zeros((2,), dtype=np.float64)
            val_comp_116 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_115[0] = val_comp_116
            val_comp_117 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_115[1] = val_comp_117
            # Dot: planner-driven const/value contraction
            dot_118 = contract_last_first(const_np_arr_114, u_k_val_115, np.float64)
            # Dot plan: semantic basis rank-1 · value vector
            dot_119 = basis_dot_const_vector(dot_113, dot_118, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_120 = mul_scalar(res_110, dot_119[0], np.float64)
            # Addition
            res_121 = binary_add_generic(res_107, res_120, np.float64)
            const_val_122 = jit_const_10.item()
            const_val_123 = jit_const_9.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_124 = const_val_122 * const_val_123
            const_np_arr_125 = jit_const_4
            basis_stack_126 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_127 = contract_last_first(const_np_arr_125, basis_stack_126, np.float64)
            u_k_val_128 = np.zeros((2,), dtype=np.float64)
            val_comp_129 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_128[0] = val_comp_129
            val_comp_130 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_128[1] = val_comp_130
            const_np_arr_131 = jit_const_6
            # Dot: planner-driven const/value contraction
            dot_132 = contract_last_first(u_k_val_128, const_np_arr_131, np.float64)
            # Dot plan: basis-vector · value-gradient
            dot_133 = basis_dot_const_vector(dot_127, np.ravel(dot_132), np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_134 = mul_scalar(res_124, dot_133[0], np.float64)
            # Addition
            res_135 = binary_add_generic(res_121, res_134, np.float64)
            const_val_136 = jit_const_11.item()
            const_val_137 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_138 = const_val_136 * const_val_137
            basis_stack_139 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_140 = jit_const_6
            # Dot plan: basis-vector · value-gradient
            dot_141 = contract_last_first(transpose_matrix(const_np_arr_140, np.float64), basis_stack_139, np.float64)
            const_np_arr_142 = jit_const_2
            # Dot plan: basis-gradient · value-vector
            dot_143 = contract_last_first(np.ascontiguousarray(dot_141.T), np.ravel(const_np_arr_142), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_144 = mul_scalar(res_138, dot_143[0], np.float64)
            # Addition
            res_145 = binary_add_generic(res_135, res_144, np.float64)
            const_val_146 = jit_const_11.item()
            const_val_147 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_148 = const_val_146 * const_val_147
            basis_stack_149 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_150 = jit_const_6
            # Dot plan: basis-vector · value-gradient
            dot_151 = contract_last_first(transpose_matrix(const_np_arr_150, np.float64), basis_stack_149, np.float64)
            const_np_arr_152 = jit_const_4
            const_np_arr_153 = jit_const_2
            # Dot: planner-driven const/value contraction
            dot_154 = contract_last_first(const_np_arr_152, const_np_arr_153, np.float64)
            # Dot plan: basis-gradient · value-vector
            dot_155 = contract_last_first(np.ascontiguousarray(dot_151.T), np.ravel(dot_154), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_156 = mul_scalar(res_148, dot_155[0], np.float64)
            # Addition
            res_157 = binary_add_generic(res_145, res_156, np.float64)
            const_val_158 = jit_const_11.item()
            const_val_159 = jit_const_5.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_160 = const_val_158 * const_val_159
            basis_stack_161 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_162 = jit_const_6
            # Dot plan: basis-vector · value-gradient
            dot_163 = contract_last_first(transpose_matrix(const_np_arr_162, np.float64), basis_stack_161, np.float64)
            const_np_arr_164 = jit_const_2
            const_np_arr_165 = jit_const_6
            # Dot: planner-driven const/value contraction
            dot_166 = contract_last_first(const_np_arr_164, const_np_arr_165, np.float64)
            # Dot plan: basis-gradient · value-vector
            dot_167 = contract_last_first(np.ascontiguousarray(dot_163.T), np.ravel(dot_166), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_168 = mul_scalar(res_160, dot_167[0], np.float64)
            # Addition
            res_169 = binary_add_generic(res_157, res_168, np.float64)
            const_val_170 = jit_const_11.item()
            const_val_171 = jit_const_7.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_172 = const_val_170 * const_val_171
            basis_stack_173 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_174 = jit_const_6
            # Dot plan: basis-vector · value-gradient
            dot_175 = contract_last_first(transpose_matrix(const_np_arr_174, np.float64), basis_stack_173, np.float64)
            u_k_val_176 = np.zeros((2,), dtype=np.float64)
            val_comp_177 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_176[0] = val_comp_177
            val_comp_178 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_176[1] = val_comp_178
            # Dot plan: basis-gradient · value-vector
            dot_179 = contract_last_first(np.ascontiguousarray(dot_175.T), np.ravel(u_k_val_176), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_180 = mul_scalar(res_172, dot_179[0], np.float64)
            # Addition
            res_181 = binary_add_generic(res_169, res_180, np.float64)
            const_val_182 = jit_const_11.item()
            const_val_183 = jit_const_8.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_184 = const_val_182 * const_val_183
            basis_stack_185 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_186 = jit_const_6
            # Dot plan: basis-vector · value-gradient
            dot_187 = contract_last_first(transpose_matrix(const_np_arr_186, np.float64), basis_stack_185, np.float64)
            const_np_arr_188 = jit_const_4
            u_k_val_189 = np.zeros((2,), dtype=np.float64)
            val_comp_190 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_189[0] = val_comp_190
            val_comp_191 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_189[1] = val_comp_191
            # Dot: planner-driven const/value contraction
            dot_192 = contract_last_first(const_np_arr_188, u_k_val_189, np.float64)
            # Dot plan: basis-gradient · value-vector
            dot_193 = contract_last_first(np.ascontiguousarray(dot_187.T), np.ravel(dot_192), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_194 = mul_scalar(res_184, dot_193[0], np.float64)
            # Addition
            res_195 = binary_add_generic(res_181, res_194, np.float64)
            const_val_196 = jit_const_11.item()
            const_val_197 = jit_const_9.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_198 = const_val_196 * const_val_197
            basis_stack_199 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_200 = jit_const_6
            # Dot plan: basis-vector · value-gradient
            dot_201 = contract_last_first(transpose_matrix(const_np_arr_200, np.float64), basis_stack_199, np.float64)
            u_k_val_202 = np.zeros((2,), dtype=np.float64)
            val_comp_203 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_202[0] = val_comp_203
            val_comp_204 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_202[1] = val_comp_204
            const_np_arr_205 = jit_const_6
            # Dot: planner-driven const/value contraction
            dot_206 = contract_last_first(u_k_val_202, const_np_arr_205, np.float64)
            # Dot plan: basis-gradient · value-vector
            dot_207 = contract_last_first(np.ascontiguousarray(dot_201.T), np.ravel(dot_206), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_208 = mul_scalar(res_198, dot_207[0], np.float64)
            # Addition
            res_209 = binary_add_generic(res_195, res_208, np.float64)
            Fe += res_209 * w_q

        K_values[e] = Ke
        F_values[e] = Fe
        J_values[e] = J

    return K_values, F_values, J_values


def get_kernel(analytic_map):
    pass
    return kernel
