# This file is auto-generated by pycutfem JIT – DO NOT EDIT
import numpy as np
import numba

CODEGEN_ABI = "2026-04-07-abi-dot-product-ghost-layout-v14"

import numba
import numpy as np
from pycutfem.jit.numba_helpers import (
    dot_grad_grad_mixed,
    contract_last_first,
    dot_mixed_const,
    dot_const_mixed,
    dot_vector_trial_grad_test,
    dot_mass_test_trial,
    dot_mass_trial_test,
    dot_grad_func_trial_vec,
    dot_trial_vec_grad_func,
    dot_vec_vec,
    dot_grad_grad_value,
    mul_scalar,
    dot_grad_basis_vector,
    vector_dot_grad_basis,
    vector_dot_grad_value,
    dot_grad_basis_with_grad_value,
    dot_grad_value_with_grad_basis,
    basis_dot_const_vector,
        const_vector_dot_basis,
        const_vector_dot_basis_1d,
        scalar_basis_times_vector,
        scalar_basis_times_vector_as_grad_tensor,
        matrix_times_scalar_basis,
        scalar_vector_outer_product,
        vector_trial_times_scalar_test,
        vector_test_times_scalar_trial,
        vector_vector_outer_product,
    dot_vec_grad_components,
    scalar_trial_times_grad_test,
    scalar_trial_times_basis_test,
    grad_trial_times_scalar_test,
    basis_trial_times_scalar_test,
    scale_mixed_basis_with_coeffs,
    trace_times_identity,
    identity_times_trace_matrix,
    columnwise_dot,
    hessian_dot_vector,
    vector_dot_hessian_basis,
    vector_dot_hessian_value,
    inner_rank2_value_rank2_basis,
    inner_rank2_basis_rank2_value,
    inner_grad_grad,
    inner_hessian_hessian,
    inner_grad_function_grad_test,
    inner_hessian_function_hessian_test,
    inner_mixed_grad_const,
    inner_grad_const_mixed,
    inner_grad_basis_grad_const,
    trace_matrix_value,
    trace_basis_tensor,
    trace_mixed_tensor,
    transpose_grad_tensor,
    transpose_mixed_grad_tensor,
    transpose_hessian_tensor,
    transpose_matrix,
    swap_mixed_basis_tensor,
    dot_value_with_grad,
    dot_grad_with_value,
    pushforward_d3,
    pushforward_d4,
    compute_physical_hessian,
    compute_physical_laplacian,
    load_variable_qp,
    gradient_qp,
    laplacian_qp,
    hessian_qp,
    ghost_grad_jump_penalty_scalar,
    ghost_grad_jump_penalty_vector,
    binary_add_generic,
    binary_add_3_4,
    binary_add_4_3,
    binary_sub_generic,
    binary_sub_3_4,
    binary_sub_4_3,
    scatter_tensor_to_union,
    pad_basis_to_union,
    pushforward_grad_to_union,
    contract_first_first
)
PARAM_ORDER = ['gdofs_map', 'node_coords', 'qp_phys', 'qw', 'detJ', 'J_inv', 'normals', 'b_ux', 'b_uy', 'jit_const_0', 'jit_const_1', 'jit_const_2', 'jit_const_3', 'jit_const_4', 'jit_const_5', 'jit_const_6', 'jit_const_7']
@numba.njit(parallel=True, fastmath=True, cache=True)
def kernel(
        gdofs_map, node_coords, qp_phys, qw, detJ, J_inv, normals, b_ux, b_uy, jit_const_0, jit_const_1, jit_const_2, jit_const_3, jit_const_4, jit_const_5, jit_const_6, jit_const_7
    ):
    num_elements        = qp_phys.shape[0]
    # n_dofs_per_element  = 18
    n_dofs_per_element  = gdofs_map.shape[1]            # 9 for volume, 15 on ghost edge
    # print(f"num_elements: {num_elements},n_dofs_per_element: {n_dofs_per_element}")
    # print(f"number of quadrature points: {qw.shape[1]}")

    K_values = np.zeros((num_elements, n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
    F_values = np.zeros((num_elements, n_dofs_per_element), dtype=np.float64)
    # Shape of the integrand that lands in “J”.
    # -------- functional accumulator ------------------------------------
    k = 0
    J_init = 0.0
    J     = J_init
    J_values = np.zeros((num_elements), dtype=np.float64)

    for e in numba.prange(num_elements):
        Ke = np.zeros((n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
        Fe = np.zeros(n_dofs_per_element, dtype=np.float64)
        J  = J_init.copy() if False else J_init

        n_union = gdofs_map.shape[1]



        for q in range(qw.shape[1]):
            x_q, w_q, J_inv_q = qp_phys[e, q], qw[e, q], J_inv[e, q]
            normal_q = normals[e, q] if normals is not None else np.zeros(2, dtype=np.float64)
            phi_q    = 0.0
            J_inv_q = J_inv[e,q]
            b_ux_q = b_ux[e,q]
            b_uy_q = b_uy[e,q]
            const_val_1 = jit_const_0.item()
            const_val_2 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_3 = const_val_1 * const_val_2
            basis_stack_4 = np.stack((b_ux[e, q], b_uy[e, q]))
            basis_stack_5 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-basis mass contraction
            dot_6 = dot_mass_test_trial(basis_stack_5, basis_stack_4, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_7 = mul_scalar(res_3, dot_6, np.float64)
            const_val_8 = jit_const_0.item()
            const_val_9 = jit_const_2.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_10 = const_val_8 * const_val_9
            basis_stack_11 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_12 = jit_const_3
            basis_stack_13 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_14 = contract_last_first(const_np_arr_12, basis_stack_13, np.float64)
            # Dot plan: basis-basis mass contraction
            dot_15 = dot_mass_test_trial(dot_14, basis_stack_11, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_16 = mul_scalar(res_10, dot_15, np.float64)
            # Addition
            res_17 = binary_add_generic(res_7, res_16, np.float64)
            const_val_18 = jit_const_0.item()
            const_val_19 = jit_const_4.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_20 = const_val_18 * const_val_19
            basis_stack_21 = np.stack((b_ux[e, q], b_uy[e, q]))
            basis_stack_22 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_23 = jit_const_5
            # Dot plan: basis-vector · value-gradient
            dot_24 = contract_last_first(transpose_matrix(const_np_arr_23, np.float64), basis_stack_22, np.float64)
            # Dot plan: basis-vector · basis-gradient
            dot_25 = dot_vec_grad_components(basis_stack_21, dot_24, False, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_26 = mul_scalar(res_20, dot_25, np.float64)
            # Addition
            res_27 = binary_add_generic(res_17, res_26, np.float64)
            const_val_28 = jit_const_6.item()
            const_val_29 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_30 = const_val_28 * const_val_29
            const_np_arr_31 = jit_const_3
            basis_stack_32 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_33 = contract_last_first(const_np_arr_31, basis_stack_32, np.float64)
            basis_stack_34 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-basis mass contraction
            dot_35 = dot_mass_test_trial(basis_stack_34, dot_33, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_36 = mul_scalar(res_30, dot_35, np.float64)
            # Addition
            res_37 = binary_add_generic(res_27, res_36, np.float64)
            const_val_38 = jit_const_6.item()
            const_val_39 = jit_const_2.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_40 = const_val_38 * const_val_39
            const_np_arr_41 = jit_const_3
            basis_stack_42 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_43 = contract_last_first(const_np_arr_41, basis_stack_42, np.float64)
            const_np_arr_44 = jit_const_3
            basis_stack_45 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_46 = contract_last_first(const_np_arr_44, basis_stack_45, np.float64)
            # Dot plan: basis-basis mass contraction
            dot_47 = dot_mass_test_trial(dot_46, dot_43, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_48 = mul_scalar(res_40, dot_47, np.float64)
            # Addition
            res_49 = binary_add_generic(res_37, res_48, np.float64)
            const_val_50 = jit_const_6.item()
            const_val_51 = jit_const_4.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_52 = const_val_50 * const_val_51
            const_np_arr_53 = jit_const_3
            basis_stack_54 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_55 = contract_last_first(const_np_arr_53, basis_stack_54, np.float64)
            basis_stack_56 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_57 = jit_const_5
            # Dot plan: basis-vector · value-gradient
            dot_58 = contract_last_first(transpose_matrix(const_np_arr_57, np.float64), basis_stack_56, np.float64)
            # Dot plan: basis-vector · basis-gradient
            dot_59 = dot_vec_grad_components(dot_55, dot_58, False, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_60 = mul_scalar(res_52, dot_59, np.float64)
            # Addition
            res_61 = binary_add_generic(res_49, res_60, np.float64)
            const_val_62 = jit_const_7.item()
            const_val_63 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_64 = const_val_62 * const_val_63
            basis_stack_65 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_66 = jit_const_5
            # Dot plan: basis-vector · value-gradient
            dot_67 = contract_last_first(transpose_matrix(const_np_arr_66, np.float64), basis_stack_65, np.float64)
            basis_stack_68 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_69 = contract_last_first(np.ascontiguousarray(dot_67.T), basis_stack_68, np.float64)
            dot_69 = transpose_matrix(dot_69, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_70 = mul_scalar(res_64, dot_69, np.float64)
            # Addition
            res_71 = binary_add_generic(res_61, res_70, np.float64)
            const_val_72 = jit_const_7.item()
            const_val_73 = jit_const_2.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_74 = const_val_72 * const_val_73
            basis_stack_75 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_76 = jit_const_5
            # Dot plan: basis-vector · value-gradient
            dot_77 = contract_last_first(transpose_matrix(const_np_arr_76, np.float64), basis_stack_75, np.float64)
            const_np_arr_78 = jit_const_3
            basis_stack_79 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_80 = contract_last_first(const_np_arr_78, basis_stack_79, np.float64)
            # Dot plan: basis-gradient · basis-vector
            dot_81 = contract_last_first(np.ascontiguousarray(dot_77.T), dot_80, np.float64)
            dot_81 = transpose_matrix(dot_81, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_82 = mul_scalar(res_74, dot_81, np.float64)
            # Addition
            res_83 = binary_add_generic(res_71, res_82, np.float64)
            const_val_84 = jit_const_7.item()
            const_val_85 = jit_const_4.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_86 = const_val_84 * const_val_85
            basis_stack_87 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_88 = jit_const_5
            # Dot plan: basis-vector · value-gradient
            dot_89 = contract_last_first(transpose_matrix(const_np_arr_88, np.float64), basis_stack_87, np.float64)
            basis_stack_90 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_91 = jit_const_5
            # Dot plan: basis-vector · value-gradient
            dot_92 = contract_last_first(transpose_matrix(const_np_arr_91, np.float64), basis_stack_90, np.float64)
            # Dot fallback: semantic basis-vector · basis-vector mass contraction
            dot_93 = dot_mass_test_trial(dot_92, dot_89, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_94 = mul_scalar(res_86, dot_93, np.float64)
            # Addition
            res_95 = binary_add_generic(res_83, res_94, np.float64)
            Ke += res_95 * w_q

        K_values[e] = Ke
        F_values[e] = Fe
        J_values[e] = J

    return K_values, F_values, J_values


def get_kernel(analytic_map):
    pass
    return kernel
