# This file is auto-generated by pycutfem JIT – DO NOT EDIT
import numpy as np
import numba

CODEGEN_ABI = "2026-04-07-abi-dot-product-ghost-layout-v14"

import numba
import numpy as np
from pycutfem.jit.numba_helpers import (
    dot_grad_grad_mixed,
    contract_last_first,
    dot_mixed_const,
    dot_const_mixed,
    dot_vector_trial_grad_test,
    dot_mass_test_trial,
    dot_mass_trial_test,
    dot_grad_func_trial_vec,
    dot_trial_vec_grad_func,
    dot_vec_vec,
    dot_grad_grad_value,
    mul_scalar,
    dot_grad_basis_vector,
    vector_dot_grad_basis,
    vector_dot_grad_value,
    dot_grad_basis_with_grad_value,
    dot_grad_value_with_grad_basis,
    basis_dot_const_vector,
        const_vector_dot_basis,
        const_vector_dot_basis_1d,
        scalar_basis_times_vector,
        scalar_basis_times_vector_as_grad_tensor,
        matrix_times_scalar_basis,
        scalar_vector_outer_product,
        vector_trial_times_scalar_test,
        vector_test_times_scalar_trial,
        vector_vector_outer_product,
    dot_vec_grad_components,
    scalar_trial_times_grad_test,
    scalar_trial_times_basis_test,
    grad_trial_times_scalar_test,
    basis_trial_times_scalar_test,
    scale_mixed_basis_with_coeffs,
    trace_times_identity,
    identity_times_trace_matrix,
    columnwise_dot,
    hessian_dot_vector,
    vector_dot_hessian_basis,
    vector_dot_hessian_value,
    inner_rank2_value_rank2_basis,
    inner_rank2_basis_rank2_value,
    inner_grad_grad,
    inner_hessian_hessian,
    inner_grad_function_grad_test,
    inner_hessian_function_hessian_test,
    inner_mixed_grad_const,
    inner_grad_const_mixed,
    inner_grad_basis_grad_const,
    trace_matrix_value,
    trace_basis_tensor,
    trace_mixed_tensor,
    transpose_grad_tensor,
    transpose_mixed_grad_tensor,
    transpose_hessian_tensor,
    transpose_matrix,
    swap_mixed_basis_tensor,
    dot_value_with_grad,
    dot_grad_with_value,
    pushforward_d3,
    pushforward_d4,
    compute_physical_hessian,
    compute_physical_laplacian,
    load_variable_qp,
    gradient_qp,
    laplacian_qp,
    hessian_qp,
    ghost_grad_jump_penalty_scalar,
    ghost_grad_jump_penalty_vector,
    binary_add_generic,
    binary_add_3_4,
    binary_add_4_3,
    binary_sub_generic,
    binary_sub_3_4,
    binary_sub_4_3,
    scatter_tensor_to_union,
    pad_basis_to_union,
    pushforward_grad_to_union,
    contract_first_first
)
PARAM_ORDER = ['gdofs_map', 'node_coords', 'qp_phys', 'qw', 'detJ', 'J_inv', 'normals', 'b_ux', 'b_uy', 'g_ux', 'g_uy', 'jit_const_0', 'jit_const_1', 'jit_const_10', 'jit_const_2', 'jit_const_3', 'jit_const_4', 'jit_const_5', 'jit_const_6', 'jit_const_7', 'jit_const_8', 'jit_const_9', 'u_u_k_loc']
@numba.njit(parallel=True, fastmath=True, cache=True)
def kernel(
        gdofs_map, node_coords, qp_phys, qw, detJ, J_inv, normals, b_ux, b_uy, g_ux, g_uy, jit_const_0, jit_const_1, jit_const_10, jit_const_2, jit_const_3, jit_const_4, jit_const_5, jit_const_6, jit_const_7, jit_const_8, jit_const_9, u_u_k_loc
    ):
    num_elements        = qp_phys.shape[0]
    # n_dofs_per_element  = 18
    n_dofs_per_element  = gdofs_map.shape[1]            # 9 for volume, 15 on ghost edge
    # print(f"num_elements: {num_elements},n_dofs_per_element: {n_dofs_per_element}")
    # print(f"number of quadrature points: {qw.shape[1]}")

    K_values = np.zeros((num_elements, n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
    F_values = np.zeros((num_elements, n_dofs_per_element), dtype=np.float64)
    # Shape of the integrand that lands in “J”.
    # -------- functional accumulator ------------------------------------
    k = 0
    J_init = 0.0
    J     = J_init
    J_values = np.zeros((num_elements), dtype=np.float64)

    for e in numba.prange(num_elements):
        Ke = np.zeros((n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
        Fe = np.zeros(n_dofs_per_element, dtype=np.float64)
        J  = J_init.copy() if False else J_init

        n_union = gdofs_map.shape[1]

        u_u_k_loc_e = u_u_k_loc[e]

        for q in range(qw.shape[1]):
            x_q, w_q, J_inv_q = qp_phys[e, q], qw[e, q], J_inv[e, q]
            normal_q = normals[e, q] if normals is not None else np.zeros(2, dtype=np.float64)
            phi_q    = 0.0
            J_inv_q = J_inv[e,q]
            b_ux_q = b_ux[e,q]
            b_uy_q = b_uy[e,q]
            g_ux_q = g_ux[e,q]
            g_uy_q = g_uy[e,q]
            const_val_1 = jit_const_0.item()
            const_val_2 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_3 = const_val_1 * const_val_2
            const_np_arr_4 = jit_const_2
            J_inv_q = J_inv[e, q]
            grad_loc_e_5 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_6 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_7 = np.stack((grad_loc_e_5, grad_loc_e_6))
            basis_stack_8 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_9 = contract_last_first(grad_stack_7, basis_stack_8, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_10 = contract_first_first(dot_9, const_np_arr_4, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_11 = mul_scalar(res_3, dot_10, np.float64)
            const_val_12 = jit_const_0.item()
            const_val_13 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_14 = const_val_12 * const_val_13
            const_np_arr_15 = jit_const_2
            J_inv_q = J_inv[e, q]
            grad_loc_e_16 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_17 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_18 = np.stack((grad_loc_e_16, grad_loc_e_17))
            const_np_arr_19 = jit_const_4
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_20 = contract_last_first(grad_stack_18, const_np_arr_19, np.float64)
            basis_stack_21 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_22 = contract_last_first(dot_20, basis_stack_21, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_23 = contract_first_first(dot_22, const_np_arr_15, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_24 = mul_scalar(res_14, dot_23, np.float64)
            # Addition
            res_25 = binary_add_generic(res_11, res_24, np.float64)
            const_val_26 = jit_const_5.item()
            const_val_27 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_28 = const_val_26 * const_val_27
            const_np_arr_29 = jit_const_4
            const_np_arr_30 = jit_const_2
            # Dot: planner-driven const/value contraction
            dot_31 = contract_last_first(const_np_arr_29, const_np_arr_30, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_e_32 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_33 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_34 = np.stack((grad_loc_e_32, grad_loc_e_33))
            basis_stack_35 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_36 = contract_last_first(grad_stack_34, basis_stack_35, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_37 = contract_first_first(dot_36, dot_31, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_38 = mul_scalar(res_28, dot_37, np.float64)
            # Addition
            res_39 = binary_add_generic(res_25, res_38, np.float64)
            const_val_40 = jit_const_5.item()
            const_val_41 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_42 = const_val_40 * const_val_41
            const_np_arr_43 = jit_const_4
            const_np_arr_44 = jit_const_2
            # Dot: planner-driven const/value contraction
            dot_45 = contract_last_first(const_np_arr_43, const_np_arr_44, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_e_46 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_47 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_48 = np.stack((grad_loc_e_46, grad_loc_e_47))
            const_np_arr_49 = jit_const_4
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_50 = contract_last_first(grad_stack_48, const_np_arr_49, np.float64)
            basis_stack_51 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_52 = contract_last_first(dot_50, basis_stack_51, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_53 = contract_first_first(dot_52, dot_45, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_54 = mul_scalar(res_42, dot_53, np.float64)
            # Addition
            res_55 = binary_add_generic(res_39, res_54, np.float64)
            const_val_56 = jit_const_6.item()
            const_val_57 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_58 = const_val_56 * const_val_57
            const_np_arr_59 = jit_const_2
            const_np_arr_60 = jit_const_7
            # Dot: planner-driven const/value contraction
            dot_61 = contract_last_first(const_np_arr_59, const_np_arr_60, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_e_62 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_63 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_64 = np.stack((grad_loc_e_62, grad_loc_e_63))
            basis_stack_65 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_66 = contract_last_first(grad_stack_64, basis_stack_65, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_67 = contract_first_first(dot_66, dot_61, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_68 = mul_scalar(res_58, dot_67, np.float64)
            # Addition
            res_69 = binary_add_generic(res_55, res_68, np.float64)
            const_val_70 = jit_const_6.item()
            const_val_71 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_72 = const_val_70 * const_val_71
            const_np_arr_73 = jit_const_2
            const_np_arr_74 = jit_const_7
            # Dot: planner-driven const/value contraction
            dot_75 = contract_last_first(const_np_arr_73, const_np_arr_74, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_e_76 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_77 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_78 = np.stack((grad_loc_e_76, grad_loc_e_77))
            const_np_arr_79 = jit_const_4
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_80 = contract_last_first(grad_stack_78, const_np_arr_79, np.float64)
            basis_stack_81 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_82 = contract_last_first(dot_80, basis_stack_81, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_83 = contract_first_first(dot_82, dot_75, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_84 = mul_scalar(res_72, dot_83, np.float64)
            # Addition
            res_85 = binary_add_generic(res_69, res_84, np.float64)
            const_val_86 = jit_const_8.item()
            const_val_87 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_88 = const_val_86 * const_val_87
            u_k_val_89 = np.zeros((2,), dtype=np.float64)
            val_comp_90 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_89[0] = val_comp_90
            val_comp_91 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_89[1] = val_comp_91
            J_inv_q = J_inv[e, q]
            grad_loc_e_92 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_93 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_94 = np.stack((grad_loc_e_92, grad_loc_e_93))
            basis_stack_95 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_96 = contract_last_first(grad_stack_94, basis_stack_95, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_97 = contract_first_first(dot_96, u_k_val_89, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_98 = mul_scalar(res_88, dot_97, np.float64)
            # Addition
            res_99 = binary_add_generic(res_85, res_98, np.float64)
            const_val_100 = jit_const_8.item()
            const_val_101 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_102 = const_val_100 * const_val_101
            u_k_val_103 = np.zeros((2,), dtype=np.float64)
            val_comp_104 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_103[0] = val_comp_104
            val_comp_105 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_103[1] = val_comp_105
            J_inv_q = J_inv[e, q]
            grad_loc_e_106 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_107 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_108 = np.stack((grad_loc_e_106, grad_loc_e_107))
            const_np_arr_109 = jit_const_4
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_110 = contract_last_first(grad_stack_108, const_np_arr_109, np.float64)
            basis_stack_111 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_112 = contract_last_first(dot_110, basis_stack_111, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_113 = contract_first_first(dot_112, u_k_val_103, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_114 = mul_scalar(res_102, dot_113, np.float64)
            # Addition
            res_115 = binary_add_generic(res_99, res_114, np.float64)
            const_val_116 = jit_const_9.item()
            const_val_117 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_118 = const_val_116 * const_val_117
            const_np_arr_119 = jit_const_4
            u_k_val_120 = np.zeros((2,), dtype=np.float64)
            val_comp_121 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_120[0] = val_comp_121
            val_comp_122 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_120[1] = val_comp_122
            # Dot: planner-driven const/value contraction
            dot_123 = contract_last_first(const_np_arr_119, u_k_val_120, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_e_124 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_125 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_126 = np.stack((grad_loc_e_124, grad_loc_e_125))
            basis_stack_127 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_128 = contract_last_first(grad_stack_126, basis_stack_127, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_129 = contract_first_first(dot_128, dot_123, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_130 = mul_scalar(res_118, dot_129, np.float64)
            # Addition
            res_131 = binary_add_generic(res_115, res_130, np.float64)
            const_val_132 = jit_const_9.item()
            const_val_133 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_134 = const_val_132 * const_val_133
            const_np_arr_135 = jit_const_4
            u_k_val_136 = np.zeros((2,), dtype=np.float64)
            val_comp_137 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_136[0] = val_comp_137
            val_comp_138 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_136[1] = val_comp_138
            # Dot: planner-driven const/value contraction
            dot_139 = contract_last_first(const_np_arr_135, u_k_val_136, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_e_140 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_141 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_142 = np.stack((grad_loc_e_140, grad_loc_e_141))
            const_np_arr_143 = jit_const_4
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_144 = contract_last_first(grad_stack_142, const_np_arr_143, np.float64)
            basis_stack_145 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_146 = contract_last_first(dot_144, basis_stack_145, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_147 = contract_first_first(dot_146, dot_139, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_148 = mul_scalar(res_134, dot_147, np.float64)
            # Addition
            res_149 = binary_add_generic(res_131, res_148, np.float64)
            const_val_150 = jit_const_10.item()
            const_val_151 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_152 = const_val_150 * const_val_151
            u_k_val_153 = np.zeros((2,), dtype=np.float64)
            val_comp_154 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_153[0] = val_comp_154
            val_comp_155 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_153[1] = val_comp_155
            const_np_arr_156 = jit_const_7
            # Dot: planner-driven const/value contraction
            dot_157 = contract_last_first(u_k_val_153, const_np_arr_156, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_e_158 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_159 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_160 = np.stack((grad_loc_e_158, grad_loc_e_159))
            basis_stack_161 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_162 = contract_last_first(grad_stack_160, basis_stack_161, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_163 = contract_first_first(dot_162, dot_157, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_164 = mul_scalar(res_152, dot_163, np.float64)
            # Addition
            res_165 = binary_add_generic(res_149, res_164, np.float64)
            const_val_166 = jit_const_10.item()
            const_val_167 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_168 = const_val_166 * const_val_167
            u_k_val_169 = np.zeros((2,), dtype=np.float64)
            val_comp_170 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_169[0] = val_comp_170
            val_comp_171 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_169[1] = val_comp_171
            const_np_arr_172 = jit_const_7
            # Dot: planner-driven const/value contraction
            dot_173 = contract_last_first(u_k_val_169, const_np_arr_172, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_e_174 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_175 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_176 = np.stack((grad_loc_e_174, grad_loc_e_175))
            const_np_arr_177 = jit_const_4
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_178 = contract_last_first(grad_stack_176, const_np_arr_177, np.float64)
            basis_stack_179 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_180 = contract_last_first(dot_178, basis_stack_179, np.float64)
            # Dot plan: value vector · semantic mixed rank-1
            dot_181 = contract_first_first(dot_180, dot_173, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_182 = mul_scalar(res_168, dot_181, np.float64)
            # Addition
            res_183 = binary_add_generic(res_165, res_182, np.float64)
            Ke += res_183 * w_q

        K_values[e] = Ke
        F_values[e] = Fe
        J_values[e] = J

    return K_values, F_values, J_values


def get_kernel(analytic_map):
    pass
    return kernel
