# This file is auto-generated by pycutfem JIT – DO NOT EDIT
import numpy as np
import numba

CODEGEN_ABI = "2026-04-07-abi-dot-product-ghost-layout-v14"

import numba
import numpy as np
from pycutfem.jit.numba_helpers import (
    dot_grad_grad_mixed,
    contract_last_first,
    dot_mixed_const,
    dot_const_mixed,
    dot_vector_trial_grad_test,
    dot_mass_test_trial,
    dot_mass_trial_test,
    dot_grad_func_trial_vec,
    dot_trial_vec_grad_func,
    dot_vec_vec,
    dot_grad_grad_value,
    mul_scalar,
    dot_grad_basis_vector,
    vector_dot_grad_basis,
    vector_dot_grad_value,
    dot_grad_basis_with_grad_value,
    dot_grad_value_with_grad_basis,
    basis_dot_const_vector,
        const_vector_dot_basis,
        const_vector_dot_basis_1d,
        scalar_basis_times_vector,
        scalar_basis_times_vector_as_grad_tensor,
        matrix_times_scalar_basis,
        scalar_vector_outer_product,
        vector_trial_times_scalar_test,
        vector_test_times_scalar_trial,
        vector_vector_outer_product,
    dot_vec_grad_components,
    scalar_trial_times_grad_test,
    scalar_trial_times_basis_test,
    grad_trial_times_scalar_test,
    basis_trial_times_scalar_test,
    scale_mixed_basis_with_coeffs,
    trace_times_identity,
    identity_times_trace_matrix,
    columnwise_dot,
    hessian_dot_vector,
    vector_dot_hessian_basis,
    vector_dot_hessian_value,
    inner_rank2_value_rank2_basis,
    inner_rank2_basis_rank2_value,
    inner_grad_grad,
    inner_hessian_hessian,
    inner_grad_function_grad_test,
    inner_hessian_function_hessian_test,
    inner_mixed_grad_const,
    inner_grad_const_mixed,
    inner_grad_basis_grad_const,
    trace_matrix_value,
    trace_basis_tensor,
    trace_mixed_tensor,
    transpose_grad_tensor,
    transpose_mixed_grad_tensor,
    transpose_hessian_tensor,
    transpose_matrix,
    swap_mixed_basis_tensor,
    dot_value_with_grad,
    dot_grad_with_value,
    pushforward_d3,
    pushforward_d4,
    compute_physical_hessian,
    compute_physical_laplacian,
    load_variable_qp,
    gradient_qp,
    laplacian_qp,
    hessian_qp,
    ghost_grad_jump_penalty_scalar,
    ghost_grad_jump_penalty_vector,
    binary_add_generic,
    binary_add_3_4,
    binary_add_4_3,
    binary_sub_generic,
    binary_sub_3_4,
    binary_sub_4_3,
    scatter_tensor_to_union,
    pad_basis_to_union,
    pushforward_grad_to_union,
    contract_first_first
)
PARAM_ORDER = ['gdofs_map', 'node_coords', 'qp_phys', 'qw', 'detJ', 'J_inv', 'normals', 'g_p', 'jit_const_0', 'jit_const_1', 'jit_const_2', 'jit_const_3', 'jit_const_4', 'jit_const_5', 'jit_const_6', 'jit_const_7', 'u_p_k_loc']
@numba.njit(parallel=True, fastmath=True, cache=True)
def kernel(
        gdofs_map, node_coords, qp_phys, qw, detJ, J_inv, normals, g_p, jit_const_0, jit_const_1, jit_const_2, jit_const_3, jit_const_4, jit_const_5, jit_const_6, jit_const_7, u_p_k_loc
    ):
    num_elements        = qp_phys.shape[0]
    # n_dofs_per_element  = 9
    n_dofs_per_element  = gdofs_map.shape[1]            # 9 for volume, 15 on ghost edge
    # print(f"num_elements: {num_elements},n_dofs_per_element: {n_dofs_per_element}")
    # print(f"number of quadrature points: {qw.shape[1]}")

    K_values = np.zeros((num_elements, n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
    F_values = np.zeros((num_elements, n_dofs_per_element), dtype=np.float64)
    # Shape of the integrand that lands in “J”.
    # -------- functional accumulator ------------------------------------
    k = 0
    J_init = 0.0
    J     = J_init
    J_values = np.zeros((num_elements), dtype=np.float64)

    for e in numba.prange(num_elements):
        Ke = np.zeros((n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
        Fe = np.zeros(n_dofs_per_element, dtype=np.float64)
        J  = J_init.copy() if False else J_init

        n_union = gdofs_map.shape[1]

        u_p_k_loc_e = u_p_k_loc[e]

        for q in range(qw.shape[1]):
            x_q, w_q, J_inv_q = qp_phys[e, q], qw[e, q], J_inv[e, q]
            normal_q = normals[e, q] if normals is not None else np.zeros(2, dtype=np.float64)
            phi_q    = 0.0
            J_inv_q = J_inv[e,q]
            g_p_q = g_p[e,q]
            const_val_1 = jit_const_0.item()
            const_val_2 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_3 = const_val_1 * const_val_2
            J_inv_q = J_inv[e, q]
            phys_grad_basis_5  = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_4 = gradient_qp(u_p_k_loc_e, phys_grad_basis_5)
            J_inv_q = J_inv[e, q]
            grad_loc_e_6 = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_scalar_7 = np.ascontiguousarray(grad_loc_e_6.T.copy())
            # Dot plan: value-vector · basis-gradient
            dot_8 = contract_last_first(np.ascontiguousarray(grad_scalar_7.T), np.ravel(grad_val_4), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_9 = mul_scalar(res_3, dot_8[0], np.float64)
            const_val_10 = jit_const_0.item()
            const_val_11 = jit_const_2.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_12 = const_val_10 * const_val_11
            J_inv_q = J_inv[e, q]
            phys_grad_basis_14  = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_13 = gradient_qp(u_p_k_loc_e, phys_grad_basis_14)
            const_np_arr_15 = jit_const_3
            J_inv_q = J_inv[e, q]
            grad_loc_e_16 = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_scalar_17 = np.ascontiguousarray(grad_loc_e_16.T.copy())
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_18 = contract_last_first(const_np_arr_15, grad_scalar_17, np.float64)
            # Dot plan: value vector · semantic basis rank-1
            dot_19 = basis_dot_const_vector(dot_18, grad_val_13, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_20 = mul_scalar(res_12, dot_19[0], np.float64)
            # Addition
            res_21 = binary_add_generic(res_9, res_20, np.float64)
            const_val_22 = jit_const_0.item()
            const_val_23 = jit_const_4.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_24 = const_val_22 * const_val_23
            J_inv_q = J_inv[e, q]
            phys_grad_basis_26  = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_25 = gradient_qp(u_p_k_loc_e, phys_grad_basis_26)
            J_inv_q = J_inv[e, q]
            grad_loc_e_27 = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_scalar_28 = np.ascontiguousarray(grad_loc_e_27.T.copy())
            const_np_arr_29 = jit_const_5
            # Dot: scalar Grad(basis) · matrix(value/const) → vector basis
            dot_30 = contract_last_first(transpose_matrix(const_np_arr_29, np.float64), grad_scalar_28, np.float64)
            # Dot plan: value-vector · basis-gradient
            dot_31 = contract_last_first(np.ascontiguousarray(dot_30.T), np.ravel(grad_val_25), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_32 = mul_scalar(res_24, dot_31[0], np.float64)
            # Addition
            res_33 = binary_add_generic(res_21, res_32, np.float64)
            const_val_34 = jit_const_6.item()
            const_val_35 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_36 = const_val_34 * const_val_35
            const_np_arr_37 = jit_const_3
            J_inv_q = J_inv[e, q]
            phys_grad_basis_39  = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_38 = gradient_qp(u_p_k_loc_e, phys_grad_basis_39)
            # Dot: planner-driven const/value contraction
            dot_40 = contract_last_first(const_np_arr_37, grad_val_38, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_e_41 = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_scalar_42 = np.ascontiguousarray(grad_loc_e_41.T.copy())
            # Dot plan: value-vector · basis-gradient
            dot_43 = contract_last_first(np.ascontiguousarray(grad_scalar_42.T), np.ravel(dot_40), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_44 = mul_scalar(res_36, dot_43[0], np.float64)
            # Addition
            res_45 = binary_add_generic(res_33, res_44, np.float64)
            const_val_46 = jit_const_6.item()
            const_val_47 = jit_const_2.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_48 = const_val_46 * const_val_47
            const_np_arr_49 = jit_const_3
            J_inv_q = J_inv[e, q]
            phys_grad_basis_51  = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_50 = gradient_qp(u_p_k_loc_e, phys_grad_basis_51)
            # Dot: planner-driven const/value contraction
            dot_52 = contract_last_first(const_np_arr_49, grad_val_50, np.float64)
            const_np_arr_53 = jit_const_3
            J_inv_q = J_inv[e, q]
            grad_loc_e_54 = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_scalar_55 = np.ascontiguousarray(grad_loc_e_54.T.copy())
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_56 = contract_last_first(const_np_arr_53, grad_scalar_55, np.float64)
            # Dot plan: value vector · semantic basis rank-1
            dot_57 = basis_dot_const_vector(dot_56, dot_52, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_58 = mul_scalar(res_48, dot_57[0], np.float64)
            # Addition
            res_59 = binary_add_generic(res_45, res_58, np.float64)
            const_val_60 = jit_const_6.item()
            const_val_61 = jit_const_4.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_62 = const_val_60 * const_val_61
            const_np_arr_63 = jit_const_3
            J_inv_q = J_inv[e, q]
            phys_grad_basis_65  = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_64 = gradient_qp(u_p_k_loc_e, phys_grad_basis_65)
            # Dot: planner-driven const/value contraction
            dot_66 = contract_last_first(const_np_arr_63, grad_val_64, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_e_67 = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_scalar_68 = np.ascontiguousarray(grad_loc_e_67.T.copy())
            const_np_arr_69 = jit_const_5
            # Dot: scalar Grad(basis) · matrix(value/const) → vector basis
            dot_70 = contract_last_first(transpose_matrix(const_np_arr_69, np.float64), grad_scalar_68, np.float64)
            # Dot plan: value-vector · basis-gradient
            dot_71 = contract_last_first(np.ascontiguousarray(dot_70.T), np.ravel(dot_66), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_72 = mul_scalar(res_62, dot_71[0], np.float64)
            # Addition
            res_73 = binary_add_generic(res_59, res_72, np.float64)
            const_val_74 = jit_const_7.item()
            const_val_75 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_76 = const_val_74 * const_val_75
            J_inv_q = J_inv[e, q]
            phys_grad_basis_78  = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_77 = gradient_qp(u_p_k_loc_e, phys_grad_basis_78)
            const_np_arr_79 = jit_const_5
            # Dot: planner-driven const/value contraction
            dot_80 = contract_last_first(grad_val_77, const_np_arr_79, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_e_81 = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_scalar_82 = np.ascontiguousarray(grad_loc_e_81.T.copy())
            # Dot plan: value-vector · basis-gradient
            dot_83 = contract_last_first(np.ascontiguousarray(grad_scalar_82.T), np.ravel(dot_80), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_84 = mul_scalar(res_76, dot_83[0], np.float64)
            # Addition
            res_85 = binary_add_generic(res_73, res_84, np.float64)
            const_val_86 = jit_const_7.item()
            const_val_87 = jit_const_2.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_88 = const_val_86 * const_val_87
            J_inv_q = J_inv[e, q]
            phys_grad_basis_90  = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_89 = gradient_qp(u_p_k_loc_e, phys_grad_basis_90)
            const_np_arr_91 = jit_const_5
            # Dot: planner-driven const/value contraction
            dot_92 = contract_last_first(grad_val_89, const_np_arr_91, np.float64)
            const_np_arr_93 = jit_const_3
            J_inv_q = J_inv[e, q]
            grad_loc_e_94 = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_scalar_95 = np.ascontiguousarray(grad_loc_e_94.T.copy())
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_96 = contract_last_first(const_np_arr_93, grad_scalar_95, np.float64)
            # Dot plan: value-gradient · basis-vector
            dot_97 = basis_dot_const_vector(dot_96, np.ravel(dot_92), np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_98 = mul_scalar(res_88, dot_97[0], np.float64)
            # Addition
            res_99 = binary_add_generic(res_85, res_98, np.float64)
            const_val_100 = jit_const_7.item()
            const_val_101 = jit_const_4.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_102 = const_val_100 * const_val_101
            J_inv_q = J_inv[e, q]
            phys_grad_basis_104  = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_103 = gradient_qp(u_p_k_loc_e, phys_grad_basis_104)
            const_np_arr_105 = jit_const_5
            # Dot: planner-driven const/value contraction
            dot_106 = contract_last_first(grad_val_103, const_np_arr_105, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_e_107 = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_scalar_108 = np.ascontiguousarray(grad_loc_e_107.T.copy())
            const_np_arr_109 = jit_const_5
            # Dot: scalar Grad(basis) · matrix(value/const) → vector basis
            dot_110 = contract_last_first(transpose_matrix(const_np_arr_109, np.float64), grad_scalar_108, np.float64)
            # Dot plan: value-vector · basis-gradient
            dot_111 = contract_last_first(np.ascontiguousarray(dot_110.T), np.ravel(dot_106), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_112 = mul_scalar(res_102, dot_111[0], np.float64)
            # Addition
            res_113 = binary_add_generic(res_99, res_112, np.float64)
            Fe += res_113 * w_q

        K_values[e] = Ke
        F_values[e] = Fe
        J_values[e] = J

    return K_values, F_values, J_values


def get_kernel(analytic_map):
    pass
    return kernel
