# This file is auto-generated by pycutfem JIT – DO NOT EDIT
import numpy as np
import numba

CODEGEN_ABI = "2026-04-07-abi-dot-product-ghost-layout-v14"

import numba
import numpy as np
from pycutfem.jit.numba_helpers import (
    dot_grad_grad_mixed,
    contract_last_first,
    dot_mixed_const,
    dot_const_mixed,
    dot_vector_trial_grad_test,
    dot_mass_test_trial,
    dot_mass_trial_test,
    dot_grad_func_trial_vec,
    dot_trial_vec_grad_func,
    dot_vec_vec,
    dot_grad_grad_value,
    mul_scalar,
    dot_grad_basis_vector,
    vector_dot_grad_basis,
    vector_dot_grad_value,
    dot_grad_basis_with_grad_value,
    dot_grad_value_with_grad_basis,
    basis_dot_const_vector,
        const_vector_dot_basis,
        const_vector_dot_basis_1d,
        scalar_basis_times_vector,
        scalar_basis_times_vector_as_grad_tensor,
        matrix_times_scalar_basis,
        scalar_vector_outer_product,
        vector_trial_times_scalar_test,
        vector_test_times_scalar_trial,
        vector_vector_outer_product,
    dot_vec_grad_components,
    scalar_trial_times_grad_test,
    scalar_trial_times_basis_test,
    grad_trial_times_scalar_test,
    basis_trial_times_scalar_test,
    scale_mixed_basis_with_coeffs,
    trace_times_identity,
    identity_times_trace_matrix,
    columnwise_dot,
    hessian_dot_vector,
    vector_dot_hessian_basis,
    vector_dot_hessian_value,
    inner_rank2_value_rank2_basis,
    inner_rank2_basis_rank2_value,
    inner_grad_grad,
    inner_hessian_hessian,
    inner_grad_function_grad_test,
    inner_hessian_function_hessian_test,
    inner_mixed_grad_const,
    inner_grad_const_mixed,
    inner_grad_basis_grad_const,
    trace_matrix_value,
    trace_basis_tensor,
    trace_mixed_tensor,
    transpose_grad_tensor,
    transpose_mixed_grad_tensor,
    transpose_hessian_tensor,
    transpose_matrix,
    swap_mixed_basis_tensor,
    dot_value_with_grad,
    dot_grad_with_value,
    pushforward_d3,
    pushforward_d4,
    compute_physical_hessian,
    compute_physical_laplacian,
    load_variable_qp,
    gradient_qp,
    laplacian_qp,
    hessian_qp,
    ghost_grad_jump_penalty_scalar,
    ghost_grad_jump_penalty_vector,
    binary_add_generic,
    binary_add_3_4,
    binary_add_4_3,
    binary_sub_generic,
    binary_sub_3_4,
    binary_sub_4_3,
    scatter_tensor_to_union,
    pad_basis_to_union,
    pushforward_grad_to_union,
    contract_first_first
)
PARAM_ORDER = ['gdofs_map', 'node_coords', 'qp_phys', 'qw', 'detJ', 'J_inv', 'normals', 'b_ux', 'b_uy', 'g_ux', 'g_uy', 'jit_const_0', 'jit_const_1', 'jit_const_10', 'jit_const_2', 'jit_const_3', 'jit_const_4', 'jit_const_5', 'jit_const_6', 'jit_const_7', 'jit_const_8', 'jit_const_9', 'u_u_k_loc']
@numba.njit(parallel=True, fastmath=True, cache=True)
def kernel(
        gdofs_map, node_coords, qp_phys, qw, detJ, J_inv, normals, b_ux, b_uy, g_ux, g_uy, jit_const_0, jit_const_1, jit_const_10, jit_const_2, jit_const_3, jit_const_4, jit_const_5, jit_const_6, jit_const_7, jit_const_8, jit_const_9, u_u_k_loc
    ):
    num_elements        = qp_phys.shape[0]
    # n_dofs_per_element  = 18
    n_dofs_per_element  = gdofs_map.shape[1]            # 9 for volume, 15 on ghost edge
    # print(f"num_elements: {num_elements},n_dofs_per_element: {n_dofs_per_element}")
    # print(f"number of quadrature points: {qw.shape[1]}")

    K_values = np.zeros((num_elements, n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
    F_values = np.zeros((num_elements, n_dofs_per_element), dtype=np.float64)
    # Shape of the integrand that lands in “J”.
    # -------- functional accumulator ------------------------------------
    k = 0
    J_init = 0.0
    J     = J_init
    J_values = np.zeros((num_elements), dtype=np.float64)

    for e in numba.prange(num_elements):
        Ke = np.zeros((n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
        Fe = np.zeros(n_dofs_per_element, dtype=np.float64)
        J  = J_init.copy() if False else J_init

        n_union = gdofs_map.shape[1]

        u_u_k_loc_e = u_u_k_loc[e]

        for q in range(qw.shape[1]):
            x_q, w_q, J_inv_q = qp_phys[e, q], qw[e, q], J_inv[e, q]
            normal_q = normals[e, q] if normals is not None else np.zeros(2, dtype=np.float64)
            phi_q    = 0.0
            J_inv_q = J_inv[e,q]
            b_ux_q = b_ux[e,q]
            b_uy_q = b_uy[e,q]
            g_ux_q = g_ux[e,q]
            g_uy_q = g_uy[e,q]
            const_val_1 = jit_const_0.item()
            const_val_2 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_3 = const_val_1 * const_val_2
            J_inv_q = J_inv[e, q]
            grad_loc_e_4 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_5 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_6 = np.stack((grad_loc_e_4, grad_loc_e_5))
            basis_stack_7 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_8 = contract_last_first(grad_stack_6, basis_stack_7, np.float64)
            const_np_arr_9 = jit_const_2
            # Dot: mixed basis (k,m,n) · constant vector → matrix
            dot_10 = contract_first_first(dot_8, const_np_arr_9, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_11 = mul_scalar(res_3, dot_10, np.float64)
            const_val_12 = jit_const_0.item()
            const_val_13 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_14 = const_val_12 * const_val_13
            J_inv_q = J_inv[e, q]
            grad_loc_e_15 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_16 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_17 = np.stack((grad_loc_e_15, grad_loc_e_16))
            basis_stack_18 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_19 = contract_last_first(grad_stack_17, basis_stack_18, np.float64)
            const_np_arr_20 = jit_const_4
            const_np_arr_21 = jit_const_2
            # Dot: planner-driven const/value contraction
            dot_22 = contract_last_first(const_np_arr_20, const_np_arr_21, np.float64)
            # Dot: mixed basis (k,m,n) · constant vector → matrix
            dot_23 = contract_first_first(dot_19, dot_22, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_24 = mul_scalar(res_14, dot_23, np.float64)
            # Addition
            res_25 = binary_add_generic(res_11, res_24, np.float64)
            const_val_26 = jit_const_0.item()
            const_val_27 = jit_const_5.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_28 = const_val_26 * const_val_27
            J_inv_q = J_inv[e, q]
            grad_loc_e_29 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_30 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_31 = np.stack((grad_loc_e_29, grad_loc_e_30))
            basis_stack_32 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_33 = contract_last_first(grad_stack_31, basis_stack_32, np.float64)
            const_np_arr_34 = jit_const_2
            const_np_arr_35 = jit_const_6
            # Dot: planner-driven const/value contraction
            dot_36 = contract_last_first(const_np_arr_34, const_np_arr_35, np.float64)
            # Dot: mixed basis (k,m,n) · constant vector → matrix
            dot_37 = contract_first_first(dot_33, dot_36, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_38 = mul_scalar(res_28, dot_37, np.float64)
            # Addition
            res_39 = binary_add_generic(res_25, res_38, np.float64)
            const_val_40 = jit_const_0.item()
            const_val_41 = jit_const_7.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_42 = const_val_40 * const_val_41
            J_inv_q = J_inv[e, q]
            grad_loc_e_43 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_44 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_45 = np.stack((grad_loc_e_43, grad_loc_e_44))
            basis_stack_46 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_47 = contract_last_first(grad_stack_45, basis_stack_46, np.float64)
            u_k_val_48 = np.zeros((2,), dtype=np.float64)
            val_comp_49 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_48[0] = val_comp_49
            val_comp_50 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_48[1] = val_comp_50
            # Dot: mixed basis (k,m,n) · constant vector → matrix
            dot_51 = contract_first_first(dot_47, u_k_val_48, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_52 = mul_scalar(res_42, dot_51, np.float64)
            # Addition
            res_53 = binary_add_generic(res_39, res_52, np.float64)
            const_val_54 = jit_const_0.item()
            const_val_55 = jit_const_8.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_56 = const_val_54 * const_val_55
            J_inv_q = J_inv[e, q]
            grad_loc_e_57 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_58 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_59 = np.stack((grad_loc_e_57, grad_loc_e_58))
            basis_stack_60 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_61 = contract_last_first(grad_stack_59, basis_stack_60, np.float64)
            const_np_arr_62 = jit_const_4
            u_k_val_63 = np.zeros((2,), dtype=np.float64)
            val_comp_64 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_63[0] = val_comp_64
            val_comp_65 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_63[1] = val_comp_65
            # Dot: planner-driven const/value contraction
            dot_66 = contract_last_first(const_np_arr_62, u_k_val_63, np.float64)
            # Dot: mixed basis (k,m,n) · constant vector → matrix
            dot_67 = contract_first_first(dot_61, dot_66, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_68 = mul_scalar(res_56, dot_67, np.float64)
            # Addition
            res_69 = binary_add_generic(res_53, res_68, np.float64)
            const_val_70 = jit_const_0.item()
            const_val_71 = jit_const_9.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_72 = const_val_70 * const_val_71
            J_inv_q = J_inv[e, q]
            grad_loc_e_73 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_74 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_75 = np.stack((grad_loc_e_73, grad_loc_e_74))
            basis_stack_76 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_77 = contract_last_first(grad_stack_75, basis_stack_76, np.float64)
            u_k_val_78 = np.zeros((2,), dtype=np.float64)
            val_comp_79 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_78[0] = val_comp_79
            val_comp_80 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_78[1] = val_comp_80
            const_np_arr_81 = jit_const_6
            # Dot: planner-driven const/value contraction
            dot_82 = contract_last_first(u_k_val_78, const_np_arr_81, np.float64)
            # Dot: mixed basis (k,m,n) · constant vector → matrix
            dot_83 = contract_first_first(dot_77, dot_82, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_84 = mul_scalar(res_72, dot_83, np.float64)
            # Addition
            res_85 = binary_add_generic(res_69, res_84, np.float64)
            const_val_86 = jit_const_10.item()
            const_val_87 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_88 = const_val_86 * const_val_87
            J_inv_q = J_inv[e, q]
            grad_loc_e_89 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_90 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_91 = np.stack((grad_loc_e_89, grad_loc_e_90))
            const_np_arr_92 = jit_const_4
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_93 = contract_last_first(grad_stack_91, const_np_arr_92, np.float64)
            basis_stack_94 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_95 = contract_last_first(dot_93, basis_stack_94, np.float64)
            const_np_arr_96 = jit_const_2
            # Dot: mixed basis (k,m,n) · constant vector → matrix
            dot_97 = contract_first_first(dot_95, const_np_arr_96, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_98 = mul_scalar(res_88, dot_97, np.float64)
            # Addition
            res_99 = binary_add_generic(res_85, res_98, np.float64)
            const_val_100 = jit_const_10.item()
            const_val_101 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_102 = const_val_100 * const_val_101
            J_inv_q = J_inv[e, q]
            grad_loc_e_103 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_104 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_105 = np.stack((grad_loc_e_103, grad_loc_e_104))
            const_np_arr_106 = jit_const_4
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_107 = contract_last_first(grad_stack_105, const_np_arr_106, np.float64)
            basis_stack_108 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_109 = contract_last_first(dot_107, basis_stack_108, np.float64)
            const_np_arr_110 = jit_const_4
            const_np_arr_111 = jit_const_2
            # Dot: planner-driven const/value contraction
            dot_112 = contract_last_first(const_np_arr_110, const_np_arr_111, np.float64)
            # Dot: mixed basis (k,m,n) · constant vector → matrix
            dot_113 = contract_first_first(dot_109, dot_112, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_114 = mul_scalar(res_102, dot_113, np.float64)
            # Addition
            res_115 = binary_add_generic(res_99, res_114, np.float64)
            const_val_116 = jit_const_10.item()
            const_val_117 = jit_const_5.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_118 = const_val_116 * const_val_117
            J_inv_q = J_inv[e, q]
            grad_loc_e_119 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_120 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_121 = np.stack((grad_loc_e_119, grad_loc_e_120))
            const_np_arr_122 = jit_const_4
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_123 = contract_last_first(grad_stack_121, const_np_arr_122, np.float64)
            basis_stack_124 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_125 = contract_last_first(dot_123, basis_stack_124, np.float64)
            const_np_arr_126 = jit_const_2
            const_np_arr_127 = jit_const_6
            # Dot: planner-driven const/value contraction
            dot_128 = contract_last_first(const_np_arr_126, const_np_arr_127, np.float64)
            # Dot: mixed basis (k,m,n) · constant vector → matrix
            dot_129 = contract_first_first(dot_125, dot_128, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_130 = mul_scalar(res_118, dot_129, np.float64)
            # Addition
            res_131 = binary_add_generic(res_115, res_130, np.float64)
            const_val_132 = jit_const_10.item()
            const_val_133 = jit_const_7.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_134 = const_val_132 * const_val_133
            J_inv_q = J_inv[e, q]
            grad_loc_e_135 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_136 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_137 = np.stack((grad_loc_e_135, grad_loc_e_136))
            const_np_arr_138 = jit_const_4
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_139 = contract_last_first(grad_stack_137, const_np_arr_138, np.float64)
            basis_stack_140 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_141 = contract_last_first(dot_139, basis_stack_140, np.float64)
            u_k_val_142 = np.zeros((2,), dtype=np.float64)
            val_comp_143 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_142[0] = val_comp_143
            val_comp_144 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_142[1] = val_comp_144
            # Dot: mixed basis (k,m,n) · constant vector → matrix
            dot_145 = contract_first_first(dot_141, u_k_val_142, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_146 = mul_scalar(res_134, dot_145, np.float64)
            # Addition
            res_147 = binary_add_generic(res_131, res_146, np.float64)
            const_val_148 = jit_const_10.item()
            const_val_149 = jit_const_8.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_150 = const_val_148 * const_val_149
            J_inv_q = J_inv[e, q]
            grad_loc_e_151 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_152 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_153 = np.stack((grad_loc_e_151, grad_loc_e_152))
            const_np_arr_154 = jit_const_4
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_155 = contract_last_first(grad_stack_153, const_np_arr_154, np.float64)
            basis_stack_156 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_157 = contract_last_first(dot_155, basis_stack_156, np.float64)
            const_np_arr_158 = jit_const_4
            u_k_val_159 = np.zeros((2,), dtype=np.float64)
            val_comp_160 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_159[0] = val_comp_160
            val_comp_161 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_159[1] = val_comp_161
            # Dot: planner-driven const/value contraction
            dot_162 = contract_last_first(const_np_arr_158, u_k_val_159, np.float64)
            # Dot: mixed basis (k,m,n) · constant vector → matrix
            dot_163 = contract_first_first(dot_157, dot_162, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_164 = mul_scalar(res_150, dot_163, np.float64)
            # Addition
            res_165 = binary_add_generic(res_147, res_164, np.float64)
            const_val_166 = jit_const_10.item()
            const_val_167 = jit_const_9.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_168 = const_val_166 * const_val_167
            J_inv_q = J_inv[e, q]
            grad_loc_e_169 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_e_170 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_171 = np.stack((grad_loc_e_169, grad_loc_e_170))
            const_np_arr_172 = jit_const_4
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_173 = contract_last_first(grad_stack_171, const_np_arr_172, np.float64)
            basis_stack_174 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: basis-gradient · basis-vector
            dot_175 = contract_last_first(dot_173, basis_stack_174, np.float64)
            u_k_val_176 = np.zeros((2,), dtype=np.float64)
            val_comp_177 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_176[0] = val_comp_177
            val_comp_178 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_176[1] = val_comp_178
            const_np_arr_179 = jit_const_6
            # Dot: planner-driven const/value contraction
            dot_180 = contract_last_first(u_k_val_176, const_np_arr_179, np.float64)
            # Dot: mixed basis (k,m,n) · constant vector → matrix
            dot_181 = contract_first_first(dot_175, dot_180, np.float64)
            # Product: const * mixed
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_182 = mul_scalar(res_168, dot_181, np.float64)
            # Addition
            res_183 = binary_add_generic(res_165, res_182, np.float64)
            Ke += res_183 * w_q

        K_values[e] = Ke
        F_values[e] = Fe
        J_values[e] = J

    return K_values, F_values, J_values


def get_kernel(analytic_map):
    pass
    return kernel
