# This file is auto-generated by pycutfem JIT – DO NOT EDIT
import numpy as np
import numba

CODEGEN_ABI = "2026-04-07-abi-dot-product-ghost-layout-v14"

import numba
import numpy as np
from pycutfem.jit.numba_helpers import (
    dot_grad_grad_mixed,
    contract_last_first,
    dot_mixed_const,
    dot_const_mixed,
    dot_vector_trial_grad_test,
    dot_mass_test_trial,
    dot_mass_trial_test,
    dot_grad_func_trial_vec,
    dot_trial_vec_grad_func,
    dot_vec_vec,
    dot_grad_grad_value,
    mul_scalar,
    dot_grad_basis_vector,
    vector_dot_grad_basis,
    vector_dot_grad_value,
    dot_grad_basis_with_grad_value,
    dot_grad_value_with_grad_basis,
    basis_dot_const_vector,
        const_vector_dot_basis,
        const_vector_dot_basis_1d,
        scalar_basis_times_vector,
        scalar_basis_times_vector_as_grad_tensor,
        matrix_times_scalar_basis,
        scalar_vector_outer_product,
        vector_trial_times_scalar_test,
        vector_test_times_scalar_trial,
        vector_vector_outer_product,
    dot_vec_grad_components,
    scalar_trial_times_grad_test,
    scalar_trial_times_basis_test,
    grad_trial_times_scalar_test,
    basis_trial_times_scalar_test,
    scale_mixed_basis_with_coeffs,
    trace_times_identity,
    identity_times_trace_matrix,
    columnwise_dot,
    hessian_dot_vector,
    vector_dot_hessian_basis,
    vector_dot_hessian_value,
    inner_rank2_value_rank2_basis,
    inner_rank2_basis_rank2_value,
    inner_grad_grad,
    inner_hessian_hessian,
    inner_grad_function_grad_test,
    inner_hessian_function_hessian_test,
    inner_mixed_grad_const,
    inner_grad_const_mixed,
    inner_grad_basis_grad_const,
    trace_matrix_value,
    trace_basis_tensor,
    trace_mixed_tensor,
    transpose_grad_tensor,
    transpose_mixed_grad_tensor,
    transpose_hessian_tensor,
    transpose_matrix,
    swap_mixed_basis_tensor,
    dot_value_with_grad,
    dot_grad_with_value,
    pushforward_d3,
    pushforward_d4,
    compute_physical_hessian,
    compute_physical_laplacian,
    load_variable_qp,
    gradient_qp,
    laplacian_qp,
    hessian_qp,
    ghost_grad_jump_penalty_scalar,
    ghost_grad_jump_penalty_vector,
    binary_add_generic,
    binary_add_3_4,
    binary_add_4_3,
    binary_sub_generic,
    binary_sub_3_4,
    binary_sub_4_3,
    scatter_tensor_to_union,
    pad_basis_to_union,
    pushforward_grad_to_union,
    contract_first_first
)
PARAM_ORDER = ['gdofs_map', 'node_coords', 'qp_phys', 'qw', 'detJ', 'J_inv', 'normals', 'b_ux', 'b_uy', 'jit_const_0', 'jit_const_1', 'jit_const_10', 'jit_const_11', 'jit_const_2', 'jit_const_3', 'jit_const_4', 'jit_const_5', 'jit_const_6', 'jit_const_7', 'jit_const_8', 'jit_const_9', 'u_u_k_loc']
@numba.njit(parallel=True, fastmath=True, cache=True)
def kernel(
        gdofs_map, node_coords, qp_phys, qw, detJ, J_inv, normals, b_ux, b_uy, jit_const_0, jit_const_1, jit_const_10, jit_const_11, jit_const_2, jit_const_3, jit_const_4, jit_const_5, jit_const_6, jit_const_7, jit_const_8, jit_const_9, u_u_k_loc
    ):
    num_elements        = qp_phys.shape[0]
    # n_dofs_per_element  = 18
    n_dofs_per_element  = gdofs_map.shape[1]            # 9 for volume, 15 on ghost edge
    # print(f"num_elements: {num_elements},n_dofs_per_element: {n_dofs_per_element}")
    # print(f"number of quadrature points: {qw.shape[1]}")

    K_values = np.zeros((num_elements, n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
    F_values = np.zeros((num_elements, n_dofs_per_element), dtype=np.float64)
    # Shape of the integrand that lands in “J”.
    # -------- functional accumulator ------------------------------------
    k = 0
    J_init = 0.0
    J     = J_init
    J_values = np.zeros((num_elements), dtype=np.float64)

    for e in numba.prange(num_elements):
        Ke = np.zeros((n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
        Fe = np.zeros(n_dofs_per_element, dtype=np.float64)
        J  = J_init.copy() if False else J_init

        n_union = gdofs_map.shape[1]

        u_u_k_loc_e = u_u_k_loc[e]

        for q in range(qw.shape[1]):
            x_q, w_q, J_inv_q = qp_phys[e, q], qw[e, q], J_inv[e, q]
            normal_q = normals[e, q] if normals is not None else np.zeros(2, dtype=np.float64)
            phi_q    = 0.0
            J_inv_q = J_inv[e,q]
            b_ux_q = b_ux[e,q]
            b_uy_q = b_uy[e,q]
            const_val_1 = jit_const_0.item()
            const_val_2 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_3 = const_val_1 * const_val_2
            const_np_arr_4 = jit_const_2
            basis_stack_5 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Constant body-force: dot(const-vec, Test)
            dot_6 = const_vector_dot_basis_1d(const_np_arr_4, basis_stack_5, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_7 = mul_scalar(res_3, dot_6, np.float64)
            const_val_8 = jit_const_0.item()
            const_val_9 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_10 = const_val_8 * const_val_9
            const_np_arr_11 = jit_const_2
            const_np_arr_12 = jit_const_4
            basis_stack_13 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_14 = contract_last_first(const_np_arr_12, basis_stack_13, np.float64)
            # Constant body-force: dot(const-vec, Test)
            dot_15 = const_vector_dot_basis_1d(const_np_arr_11, dot_14, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_16 = mul_scalar(res_10, dot_15, np.float64)
            # Addition
            res_17 = binary_add_generic(res_7, res_16, np.float64)
            const_val_18 = jit_const_0.item()
            const_val_19 = jit_const_5.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_20 = const_val_18 * const_val_19
            const_np_arr_21 = jit_const_2
            basis_stack_22 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_23 = jit_const_6
            # Dot plan: basis-vector · value-gradient
            dot_24 = contract_last_first(transpose_matrix(const_np_arr_23, np.float64), basis_stack_22, np.float64)
            # Dot plan: value-vector · basis-gradient
            dot_25 = contract_last_first(np.ascontiguousarray(dot_24.T), np.ravel(const_np_arr_21), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_26 = mul_scalar(res_20, dot_25[0], np.float64)
            # Addition
            res_27 = binary_add_generic(res_17, res_26, np.float64)
            const_val_28 = jit_const_7.item()
            const_val_29 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_30 = const_val_28 * const_val_29
            const_np_arr_31 = jit_const_4
            const_np_arr_32 = jit_const_2
            # Dot: planner-driven const/value contraction
            dot_33 = contract_last_first(const_np_arr_31, const_np_arr_32, np.float64)
            basis_stack_34 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Constant body-force: dot(const-vec, Test)
            dot_35 = const_vector_dot_basis_1d(dot_33, basis_stack_34, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_36 = mul_scalar(res_30, dot_35, np.float64)
            # Addition
            res_37 = binary_add_generic(res_27, res_36, np.float64)
            const_val_38 = jit_const_7.item()
            const_val_39 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_40 = const_val_38 * const_val_39
            const_np_arr_41 = jit_const_4
            const_np_arr_42 = jit_const_2
            # Dot: planner-driven const/value contraction
            dot_43 = contract_last_first(const_np_arr_41, const_np_arr_42, np.float64)
            const_np_arr_44 = jit_const_4
            basis_stack_45 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_46 = contract_last_first(const_np_arr_44, basis_stack_45, np.float64)
            # Constant body-force: dot(const-vec, Test)
            dot_47 = const_vector_dot_basis_1d(dot_43, dot_46, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_48 = mul_scalar(res_40, dot_47, np.float64)
            # Addition
            res_49 = binary_add_generic(res_37, res_48, np.float64)
            const_val_50 = jit_const_7.item()
            const_val_51 = jit_const_5.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_52 = const_val_50 * const_val_51
            const_np_arr_53 = jit_const_4
            const_np_arr_54 = jit_const_2
            # Dot: planner-driven const/value contraction
            dot_55 = contract_last_first(const_np_arr_53, const_np_arr_54, np.float64)
            basis_stack_56 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_57 = jit_const_6
            # Dot plan: basis-vector · value-gradient
            dot_58 = contract_last_first(transpose_matrix(const_np_arr_57, np.float64), basis_stack_56, np.float64)
            # Dot plan: value-vector · basis-gradient
            dot_59 = contract_last_first(np.ascontiguousarray(dot_58.T), np.ravel(dot_55), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_60 = mul_scalar(res_52, dot_59[0], np.float64)
            # Addition
            res_61 = binary_add_generic(res_49, res_60, np.float64)
            const_val_62 = jit_const_8.item()
            const_val_63 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_64 = const_val_62 * const_val_63
            const_np_arr_65 = jit_const_2
            const_np_arr_66 = jit_const_6
            # Dot: planner-driven const/value contraction
            dot_67 = contract_last_first(const_np_arr_65, const_np_arr_66, np.float64)
            basis_stack_68 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_69 = basis_dot_const_vector(basis_stack_68, np.ravel(dot_67), np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_70 = mul_scalar(res_64, dot_69[0], np.float64)
            # Addition
            res_71 = binary_add_generic(res_61, res_70, np.float64)
            const_val_72 = jit_const_8.item()
            const_val_73 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_74 = const_val_72 * const_val_73
            const_np_arr_75 = jit_const_2
            const_np_arr_76 = jit_const_6
            # Dot: planner-driven const/value contraction
            dot_77 = contract_last_first(const_np_arr_75, const_np_arr_76, np.float64)
            const_np_arr_78 = jit_const_4
            basis_stack_79 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_80 = contract_last_first(const_np_arr_78, basis_stack_79, np.float64)
            # Dot plan: value-gradient · basis-vector
            dot_81 = basis_dot_const_vector(dot_80, np.ravel(dot_77), np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_82 = mul_scalar(res_74, dot_81[0], np.float64)
            # Addition
            res_83 = binary_add_generic(res_71, res_82, np.float64)
            const_val_84 = jit_const_8.item()
            const_val_85 = jit_const_5.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_86 = const_val_84 * const_val_85
            const_np_arr_87 = jit_const_2
            const_np_arr_88 = jit_const_6
            # Dot: planner-driven const/value contraction
            dot_89 = contract_last_first(const_np_arr_87, const_np_arr_88, np.float64)
            basis_stack_90 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_91 = jit_const_6
            # Dot plan: basis-vector · value-gradient
            dot_92 = contract_last_first(transpose_matrix(const_np_arr_91, np.float64), basis_stack_90, np.float64)
            # Dot plan: value-vector · basis-gradient
            dot_93 = contract_last_first(np.ascontiguousarray(dot_92.T), np.ravel(dot_89), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_94 = mul_scalar(res_86, dot_93[0], np.float64)
            # Addition
            res_95 = binary_add_generic(res_83, res_94, np.float64)
            const_val_96 = jit_const_9.item()
            const_val_97 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_98 = const_val_96 * const_val_97
            u_k_val_99 = np.zeros((2,), dtype=np.float64)
            val_comp_100 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_99[0] = val_comp_100
            val_comp_101 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_99[1] = val_comp_101
            basis_stack_102 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value vector · semantic basis rank-1
            dot_103 = basis_dot_const_vector(basis_stack_102, u_k_val_99, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_104 = mul_scalar(res_98, dot_103[0], np.float64)
            # Addition
            res_105 = binary_add_generic(res_95, res_104, np.float64)
            const_val_106 = jit_const_9.item()
            const_val_107 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_108 = const_val_106 * const_val_107
            u_k_val_109 = np.zeros((2,), dtype=np.float64)
            val_comp_110 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_109[0] = val_comp_110
            val_comp_111 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_109[1] = val_comp_111
            const_np_arr_112 = jit_const_4
            basis_stack_113 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_114 = contract_last_first(const_np_arr_112, basis_stack_113, np.float64)
            # Dot plan: value vector · semantic basis rank-1
            dot_115 = basis_dot_const_vector(dot_114, u_k_val_109, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_116 = mul_scalar(res_108, dot_115[0], np.float64)
            # Addition
            res_117 = binary_add_generic(res_105, res_116, np.float64)
            const_val_118 = jit_const_9.item()
            const_val_119 = jit_const_5.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_120 = const_val_118 * const_val_119
            u_k_val_121 = np.zeros((2,), dtype=np.float64)
            val_comp_122 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_121[0] = val_comp_122
            val_comp_123 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_121[1] = val_comp_123
            basis_stack_124 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_125 = jit_const_6
            # Dot plan: basis-vector · value-gradient
            dot_126 = contract_last_first(transpose_matrix(const_np_arr_125, np.float64), basis_stack_124, np.float64)
            # Dot plan: value-vector · basis-gradient
            dot_127 = contract_last_first(np.ascontiguousarray(dot_126.T), np.ravel(u_k_val_121), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_128 = mul_scalar(res_120, dot_127[0], np.float64)
            # Addition
            res_129 = binary_add_generic(res_117, res_128, np.float64)
            const_val_130 = jit_const_10.item()
            const_val_131 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_132 = const_val_130 * const_val_131
            const_np_arr_133 = jit_const_4
            u_k_val_134 = np.zeros((2,), dtype=np.float64)
            val_comp_135 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_134[0] = val_comp_135
            val_comp_136 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_134[1] = val_comp_136
            # Dot: planner-driven const/value contraction
            dot_137 = contract_last_first(const_np_arr_133, u_k_val_134, np.float64)
            basis_stack_138 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value vector · semantic basis rank-1
            dot_139 = basis_dot_const_vector(basis_stack_138, dot_137, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_140 = mul_scalar(res_132, dot_139[0], np.float64)
            # Addition
            res_141 = binary_add_generic(res_129, res_140, np.float64)
            const_val_142 = jit_const_10.item()
            const_val_143 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_144 = const_val_142 * const_val_143
            const_np_arr_145 = jit_const_4
            u_k_val_146 = np.zeros((2,), dtype=np.float64)
            val_comp_147 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_146[0] = val_comp_147
            val_comp_148 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_146[1] = val_comp_148
            # Dot: planner-driven const/value contraction
            dot_149 = contract_last_first(const_np_arr_145, u_k_val_146, np.float64)
            const_np_arr_150 = jit_const_4
            basis_stack_151 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_152 = contract_last_first(const_np_arr_150, basis_stack_151, np.float64)
            # Dot plan: value vector · semantic basis rank-1
            dot_153 = basis_dot_const_vector(dot_152, dot_149, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_154 = mul_scalar(res_144, dot_153[0], np.float64)
            # Addition
            res_155 = binary_add_generic(res_141, res_154, np.float64)
            const_val_156 = jit_const_10.item()
            const_val_157 = jit_const_5.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_158 = const_val_156 * const_val_157
            const_np_arr_159 = jit_const_4
            u_k_val_160 = np.zeros((2,), dtype=np.float64)
            val_comp_161 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_160[0] = val_comp_161
            val_comp_162 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_160[1] = val_comp_162
            # Dot: planner-driven const/value contraction
            dot_163 = contract_last_first(const_np_arr_159, u_k_val_160, np.float64)
            basis_stack_164 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_165 = jit_const_6
            # Dot plan: basis-vector · value-gradient
            dot_166 = contract_last_first(transpose_matrix(const_np_arr_165, np.float64), basis_stack_164, np.float64)
            # Dot plan: value-vector · basis-gradient
            dot_167 = contract_last_first(np.ascontiguousarray(dot_166.T), np.ravel(dot_163), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_168 = mul_scalar(res_158, dot_167[0], np.float64)
            # Addition
            res_169 = binary_add_generic(res_155, res_168, np.float64)
            const_val_170 = jit_const_11.item()
            const_val_171 = jit_const_1.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_172 = const_val_170 * const_val_171
            u_k_val_173 = np.zeros((2,), dtype=np.float64)
            val_comp_174 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_173[0] = val_comp_174
            val_comp_175 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_173[1] = val_comp_175
            const_np_arr_176 = jit_const_6
            # Dot: planner-driven const/value contraction
            dot_177 = contract_last_first(u_k_val_173, const_np_arr_176, np.float64)
            basis_stack_178 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_179 = basis_dot_const_vector(basis_stack_178, np.ravel(dot_177), np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_180 = mul_scalar(res_172, dot_179[0], np.float64)
            # Addition
            res_181 = binary_add_generic(res_169, res_180, np.float64)
            const_val_182 = jit_const_11.item()
            const_val_183 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_184 = const_val_182 * const_val_183
            u_k_val_185 = np.zeros((2,), dtype=np.float64)
            val_comp_186 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_185[0] = val_comp_186
            val_comp_187 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_185[1] = val_comp_187
            const_np_arr_188 = jit_const_6
            # Dot: planner-driven const/value contraction
            dot_189 = contract_last_first(u_k_val_185, const_np_arr_188, np.float64)
            const_np_arr_190 = jit_const_4
            basis_stack_191 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value-gradient · basis-vector
            dot_192 = contract_last_first(const_np_arr_190, basis_stack_191, np.float64)
            # Dot plan: value-gradient · basis-vector
            dot_193 = basis_dot_const_vector(dot_192, np.ravel(dot_189), np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_194 = mul_scalar(res_184, dot_193[0], np.float64)
            # Addition
            res_195 = binary_add_generic(res_181, res_194, np.float64)
            const_val_196 = jit_const_11.item()
            const_val_197 = jit_const_5.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_198 = const_val_196 * const_val_197
            u_k_val_199 = np.zeros((2,), dtype=np.float64)
            val_comp_200 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_199[0] = val_comp_200
            val_comp_201 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_199[1] = val_comp_201
            const_np_arr_202 = jit_const_6
            # Dot: planner-driven const/value contraction
            dot_203 = contract_last_first(u_k_val_199, const_np_arr_202, np.float64)
            basis_stack_204 = np.stack((b_ux[e, q], b_uy[e, q]))
            const_np_arr_205 = jit_const_6
            # Dot plan: basis-vector · value-gradient
            dot_206 = contract_last_first(transpose_matrix(const_np_arr_205, np.float64), basis_stack_204, np.float64)
            # Dot plan: value-vector · basis-gradient
            dot_207 = contract_last_first(np.ascontiguousarray(dot_206.T), np.ravel(dot_203), np.float64)[np.newaxis, :]
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_208 = mul_scalar(res_198, dot_207[0], np.float64)
            # Addition
            res_209 = binary_add_generic(res_195, res_208, np.float64)
            Fe += res_209 * w_q

        K_values[e] = Ke
        F_values[e] = Fe
        J_values[e] = J

    return K_values, F_values, J_values


def get_kernel(analytic_map):
    pass
    return kernel
