# This file is auto-generated by pycutfem JIT – DO NOT EDIT
import numpy as np
import numba

CODEGEN_ABI = "2026-04-07-abi-dot-product-ghost-layout-v14"

import numba
import numpy as np
from pycutfem.jit.numba_helpers import (
    dot_grad_grad_mixed,
    contract_last_first,
    dot_mixed_const,
    dot_const_mixed,
    dot_vector_trial_grad_test,
    dot_mass_test_trial,
    dot_mass_trial_test,
    dot_grad_func_trial_vec,
    dot_trial_vec_grad_func,
    dot_vec_vec,
    dot_grad_grad_value,
    mul_scalar,
    dot_grad_basis_vector,
    vector_dot_grad_basis,
    vector_dot_grad_value,
    dot_grad_basis_with_grad_value,
    dot_grad_value_with_grad_basis,
    basis_dot_const_vector,
        const_vector_dot_basis,
        const_vector_dot_basis_1d,
        scalar_basis_times_vector,
        scalar_basis_times_vector_as_grad_tensor,
        matrix_times_scalar_basis,
        scalar_vector_outer_product,
        vector_trial_times_scalar_test,
        vector_test_times_scalar_trial,
        vector_vector_outer_product,
    dot_vec_grad_components,
    scalar_trial_times_grad_test,
    scalar_trial_times_basis_test,
    grad_trial_times_scalar_test,
    basis_trial_times_scalar_test,
    scale_mixed_basis_with_coeffs,
    trace_times_identity,
    identity_times_trace_matrix,
    columnwise_dot,
    hessian_dot_vector,
    vector_dot_hessian_basis,
    vector_dot_hessian_value,
    inner_rank2_value_rank2_basis,
    inner_rank2_basis_rank2_value,
    inner_grad_grad,
    inner_hessian_hessian,
    inner_grad_function_grad_test,
    inner_hessian_function_hessian_test,
    inner_mixed_grad_const,
    inner_grad_const_mixed,
    inner_grad_basis_grad_const,
    trace_matrix_value,
    trace_basis_tensor,
    trace_mixed_tensor,
    transpose_grad_tensor,
    transpose_mixed_grad_tensor,
    transpose_hessian_tensor,
    transpose_matrix,
    swap_mixed_basis_tensor,
    dot_value_with_grad,
    dot_grad_with_value,
    pushforward_d3,
    pushforward_d4,
    compute_physical_hessian,
    compute_physical_laplacian,
    load_variable_qp,
    gradient_qp,
    laplacian_qp,
    hessian_qp,
    ghost_grad_jump_penalty_scalar,
    ghost_grad_jump_penalty_vector,
    binary_add_generic,
    binary_add_3_4,
    binary_add_4_3,
    binary_sub_generic,
    binary_sub_3_4,
    binary_sub_4_3,
    scatter_tensor_to_union,
    pad_basis_to_union,
    pushforward_grad_to_union,
    contract_first_first
)
PARAM_ORDER = ['gdofs_map', 'node_coords', 'qp_phys', 'qw', 'detJ', 'J_inv', 'normals', 'example2_local_half', 'example2_local_mesh_lambda', 'example2_local_mesh_mu', 'example2_local_two', 'g_mx', 'g_my', 'jit_const_0']
@numba.njit(parallel=True, fastmath=True, cache=True)
def kernel(
        gdofs_map, node_coords, qp_phys, qw, detJ, J_inv, normals, example2_local_half, example2_local_mesh_lambda, example2_local_mesh_mu, example2_local_two, g_mx, g_my, jit_const_0
    ):
    num_elements        = qp_phys.shape[0]
    # n_dofs_per_element  = 6
    n_dofs_per_element  = gdofs_map.shape[1]            # 9 for volume, 15 on ghost edge
    # print(f"num_elements: {num_elements},n_dofs_per_element: {n_dofs_per_element}")
    # print(f"number of quadrature points: {qw.shape[1]}")

    K_values = np.zeros((num_elements, n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
    F_values = np.zeros((num_elements, n_dofs_per_element), dtype=np.float64)
    # Shape of the integrand that lands in “J”.
    # -------- functional accumulator ------------------------------------
    k = 0
    J_init = 0.0
    J     = J_init
    J_values = np.zeros((num_elements), dtype=np.float64)

    for e in numba.prange(num_elements):
        Ke = np.zeros((n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
        Fe = np.zeros(n_dofs_per_element, dtype=np.float64)
        J  = J_init.copy() if False else J_init

        n_union = gdofs_map.shape[1]



        for q in range(qw.shape[1]):
            x_q, w_q, J_inv_q = qp_phys[e, q], qw[e, q], J_inv[e, q]
            normal_q = normals[e, q] if normals is not None else np.zeros(2, dtype=np.float64)
            phi_q    = 0.0
            J_inv_q = J_inv[e,q]
            g_mx_q = g_mx[e,q]
            g_my_q = g_my[e,q]
            const_val_1 = example2_local_two.item()
            const_val_2 = example2_local_mesh_mu.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_3 = const_val_1 * const_val_2
            const_val_4 = example2_local_half.item()
            J_inv_q = J_inv[e, q]
            grad_loc_5 = np.ascontiguousarray(g_mx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_6 = np.ascontiguousarray(g_my[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_7 = np.stack((grad_loc_5, grad_loc_6))
            J_inv_q = J_inv[e, q]
            grad_loc_8 = np.ascontiguousarray(g_mx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_9 = np.ascontiguousarray(g_my[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_10 = np.stack((grad_loc_8, grad_loc_9))
            trp_11 = transpose_grad_tensor(grad_stack_10, np.float64)
            # Addition
            res_12 = binary_add_generic(grad_stack_7, trp_11, np.float64)
            # Product: const * trial
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_13 = mul_scalar(const_val_4, res_12, np.float64)
            # Product: const * trial
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_14 = mul_scalar(res_3, res_13, np.float64)
            const_val_15 = example2_local_mesh_lambda.item()
            J_inv_q = J_inv[e, q]
            grad_loc_16 = np.ascontiguousarray(g_mx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_17 = np.ascontiguousarray(g_my[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_18 = np.stack((grad_loc_16, grad_loc_17))
            # Div(basis) → scalar basis (1,n_loc)
            n_loc  = grad_stack_18.shape[1]
            n_vec  = 2
            div_19 = np.zeros((1, n_loc), dtype=np.float64)
            for j in range(n_loc):
                tmp = 0.0
                for k in range(n_vec):
                    tmp += grad_stack_18[k, j, k]
                div_19[0, j] = tmp
            # Product: const * trial
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_20 = mul_scalar(const_val_15, div_19, np.float64)
            const_np_arr_21 = jit_const_0
            # Product: trial * const
            # rhs: trace(trial) * Identity → 
            res_22 = trace_times_identity(res_20, const_np_arr_21, np.float64)
            # Addition
            res_23 = binary_add_generic(res_14, res_22, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_24 = np.ascontiguousarray(g_mx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_25 = np.ascontiguousarray(g_my[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_26 = np.stack((grad_loc_24, grad_loc_25))
            # Inner(LHS): orient rows=test, cols=trial
            inner_27 = inner_grad_grad(grad_stack_26, res_23, np.float64)
            Ke += inner_27 * w_q

        K_values[e] = Ke
        F_values[e] = Fe
        J_values[e] = J

    return K_values, F_values, J_values


def get_kernel(analytic_map):
    pass
    return kernel
