# This file is auto-generated by pycutfem JIT – DO NOT EDIT
import numpy as np
import numba

CODEGEN_ABI = "2026-04-07-abi-dot-product-ghost-layout-v14"

import numba
import numpy as np
from pycutfem.jit.numba_helpers import (
    dot_grad_grad_mixed,
    contract_last_first,
    dot_mixed_const,
    dot_const_mixed,
    dot_vector_trial_grad_test,
    dot_mass_test_trial,
    dot_mass_trial_test,
    dot_grad_func_trial_vec,
    dot_trial_vec_grad_func,
    dot_vec_vec,
    dot_grad_grad_value,
    mul_scalar,
    dot_grad_basis_vector,
    vector_dot_grad_basis,
    vector_dot_grad_value,
    dot_grad_basis_with_grad_value,
    dot_grad_value_with_grad_basis,
    basis_dot_const_vector,
        const_vector_dot_basis,
        const_vector_dot_basis_1d,
        scalar_basis_times_vector,
        scalar_basis_times_vector_as_grad_tensor,
        matrix_times_scalar_basis,
        scalar_vector_outer_product,
        vector_trial_times_scalar_test,
        vector_test_times_scalar_trial,
        vector_vector_outer_product,
    dot_vec_grad_components,
    scalar_trial_times_grad_test,
    scalar_trial_times_basis_test,
    grad_trial_times_scalar_test,
    basis_trial_times_scalar_test,
    scale_mixed_basis_with_coeffs,
    trace_times_identity,
    identity_times_trace_matrix,
    columnwise_dot,
    hessian_dot_vector,
    vector_dot_hessian_basis,
    vector_dot_hessian_value,
    inner_rank2_value_rank2_basis,
    inner_rank2_basis_rank2_value,
    inner_grad_grad,
    inner_hessian_hessian,
    inner_grad_function_grad_test,
    inner_hessian_function_hessian_test,
    inner_mixed_grad_const,
    inner_grad_const_mixed,
    inner_grad_basis_grad_const,
    trace_matrix_value,
    trace_basis_tensor,
    trace_mixed_tensor,
    transpose_grad_tensor,
    transpose_mixed_grad_tensor,
    transpose_hessian_tensor,
    transpose_matrix,
    swap_mixed_basis_tensor,
    dot_value_with_grad,
    dot_grad_with_value,
    pushforward_d3,
    pushforward_d4,
    compute_physical_hessian,
    compute_physical_laplacian,
    load_variable_qp,
    gradient_qp,
    laplacian_qp,
    hessian_qp,
    ghost_grad_jump_penalty_scalar,
    ghost_grad_jump_penalty_vector,
    binary_add_generic,
    binary_add_3_4,
    binary_add_4_3,
    binary_sub_generic,
    binary_sub_3_4,
    binary_sub_4_3,
    scatter_tensor_to_union,
    pad_basis_to_union,
    pushforward_grad_to_union,
    contract_first_first
)
PARAM_ORDER = ['gdofs_map', 'node_coords', 'qp_phys', 'qw', 'detJ', 'J_inv', 'normals', 'b_ux', 'b_uy', 'example2_local_bossak_alpha', 'example2_local_bossak_ma0', 'example2_local_bossak_ma2', 'example2_local_one', 'example2_local_rho_f', 'g_mx', 'g_my', 'jit_const_0', 'u_a_prev_loc', 'u_d_mesh_loc', 'u_u_k_loc', 'u_u_prev_loc']
@numba.njit(parallel=True, fastmath=True, cache=True)
def kernel(
        gdofs_map, node_coords, qp_phys, qw, detJ, J_inv, normals, b_ux, b_uy, example2_local_bossak_alpha, example2_local_bossak_ma0, example2_local_bossak_ma2, example2_local_one, example2_local_rho_f, g_mx, g_my, jit_const_0, u_a_prev_loc, u_d_mesh_loc, u_u_k_loc, u_u_prev_loc
    ):
    num_elements        = qp_phys.shape[0]
    # n_dofs_per_element  = 12
    n_dofs_per_element  = gdofs_map.shape[1]            # 9 for volume, 15 on ghost edge
    # print(f"num_elements: {num_elements},n_dofs_per_element: {n_dofs_per_element}")
    # print(f"number of quadrature points: {qw.shape[1]}")

    K_values = np.zeros((num_elements, n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
    F_values = np.zeros((num_elements, n_dofs_per_element), dtype=np.float64)
    # Shape of the integrand that lands in “J”.
    # -------- functional accumulator ------------------------------------
    k = 0
    J_init = 0.0
    J     = J_init
    J_values = np.zeros((num_elements), dtype=np.float64)

    for e in numba.prange(num_elements):
        Ke = np.zeros((n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
        Fe = np.zeros(n_dofs_per_element, dtype=np.float64)
        J  = J_init.copy() if False else J_init

        n_union = gdofs_map.shape[1]

        u_a_prev_loc_e = u_a_prev_loc[e]
        u_d_mesh_loc_e = u_d_mesh_loc[e]
        u_u_k_loc_e = u_u_k_loc[e]
        u_u_prev_loc_e = u_u_prev_loc[e]

        for q in range(qw.shape[1]):
            x_q, w_q, J_inv_q = qp_phys[e, q], qw[e, q], J_inv[e, q]
            normal_q = normals[e, q] if normals is not None else np.zeros(2, dtype=np.float64)
            phi_q    = 0.0
            J_inv_q = J_inv[e,q]
            b_ux_q = b_ux[e,q]
            b_uy_q = b_uy[e,q]
            g_mx_q = g_mx[e,q]
            g_my_q = g_my[e,q]
            const_val_1 = example2_local_rho_f.item()
            const_np_arr_2 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_4  = np.ascontiguousarray(g_mx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_3 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_4)
            phys_grad_basis_6  = np.ascontiguousarray(g_my[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_5 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_6)
            grad_val_stack_7 = np.stack((grad_val_3, grad_val_5))
            # Addition
            res_8 = binary_add_generic(const_np_arr_2, grad_val_stack_7, np.float64)
            a00 = res_8[0, 0]
            a01 = res_8[0, 1]
            a10 = res_8[1, 0]
            a11 = res_8[1, 1]
            det2_9 = a00 * a11 - a01 * a10
            # Product: const * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_10 = const_val_1 * det2_9
            const_val_11 = example2_local_one.item()
            const_val_12 = example2_local_bossak_alpha.item()
            # Subtraction
            res_13 = binary_sub_generic(const_val_11, const_val_12, np.float64)
            const_val_14 = example2_local_bossak_ma0.item()
            u_k_val_15 = np.zeros((2,), dtype=np.float64)
            val_comp_16 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_15[0] = val_comp_16
            val_comp_17 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_15[1] = val_comp_17
            u_prev_val_18 = np.zeros((2,), dtype=np.float64)
            val_comp_19 = load_variable_qp(u_u_prev_loc_e, b_ux[e, q])
            u_prev_val_18[0] = val_comp_19
            val_comp_20 = load_variable_qp(u_u_prev_loc_e, b_uy[e, q])
            u_prev_val_18[1] = val_comp_20
            # Subtraction
            res_21 = binary_sub_generic(u_k_val_15, u_prev_val_18, np.float64)
            # Product: const * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_22 = mul_scalar(const_val_14, res_21, np.float64)
            const_val_23 = example2_local_bossak_ma2.item()
            a_prev_val_24 = np.zeros((2,), dtype=np.float64)
            val_comp_25 = load_variable_qp(u_a_prev_loc_e, b_ux[e, q])
            a_prev_val_24[0] = val_comp_25
            val_comp_26 = load_variable_qp(u_a_prev_loc_e, b_uy[e, q])
            a_prev_val_24[1] = val_comp_26
            # Product: const * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_27 = mul_scalar(const_val_23, a_prev_val_24, np.float64)
            # Addition
            res_28 = binary_add_generic(res_22, res_27, np.float64)
            # Product: const * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_29 = mul_scalar(res_13, res_28, np.float64)
            const_val_30 = example2_local_bossak_alpha.item()
            a_prev_val_31 = np.zeros((2,), dtype=np.float64)
            val_comp_32 = load_variable_qp(u_a_prev_loc_e, b_ux[e, q])
            a_prev_val_31[0] = val_comp_32
            val_comp_33 = load_variable_qp(u_a_prev_loc_e, b_uy[e, q])
            a_prev_val_31[1] = val_comp_33
            # Product: const * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_34 = mul_scalar(const_val_30, a_prev_val_31, np.float64)
            # Addition
            res_35 = binary_add_generic(res_29, res_34, np.float64)
            basis_stack_36 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Dot plan: value vector · semantic basis rank-1
            dot_37 = basis_dot_const_vector(basis_stack_36, res_35, np.float64)
            # Product: value * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_38 = mul_scalar(res_10, dot_37[0], np.float64)
            Fe += res_38 * w_q

        K_values[e] = Ke
        F_values[e] = Fe
        J_values[e] = J

    return K_values, F_values, J_values


def get_kernel(analytic_map):
    pass
    return kernel
