# This file is auto-generated by pycutfem JIT – DO NOT EDIT
import numpy as np
import numba

CODEGEN_ABI = "2026-04-07-abi-dot-product-ghost-layout-v14"

import numba
import numpy as np
from pycutfem.jit.numba_helpers import (
    dot_grad_grad_mixed,
    contract_last_first,
    dot_mixed_const,
    dot_const_mixed,
    dot_vector_trial_grad_test,
    dot_mass_test_trial,
    dot_mass_trial_test,
    dot_grad_func_trial_vec,
    dot_trial_vec_grad_func,
    dot_vec_vec,
    dot_grad_grad_value,
    mul_scalar,
    dot_grad_basis_vector,
    vector_dot_grad_basis,
    vector_dot_grad_value,
    dot_grad_basis_with_grad_value,
    dot_grad_value_with_grad_basis,
    basis_dot_const_vector,
        const_vector_dot_basis,
        const_vector_dot_basis_1d,
        scalar_basis_times_vector,
        scalar_basis_times_vector_as_grad_tensor,
        matrix_times_scalar_basis,
        scalar_vector_outer_product,
        vector_trial_times_scalar_test,
        vector_test_times_scalar_trial,
        vector_vector_outer_product,
    dot_vec_grad_components,
    scalar_trial_times_grad_test,
    scalar_trial_times_basis_test,
    grad_trial_times_scalar_test,
    basis_trial_times_scalar_test,
    scale_mixed_basis_with_coeffs,
    trace_times_identity,
    identity_times_trace_matrix,
    columnwise_dot,
    hessian_dot_vector,
    vector_dot_hessian_basis,
    vector_dot_hessian_value,
    inner_rank2_value_rank2_basis,
    inner_rank2_basis_rank2_value,
    inner_grad_grad,
    inner_hessian_hessian,
    inner_grad_function_grad_test,
    inner_hessian_function_hessian_test,
    inner_mixed_grad_const,
    inner_grad_const_mixed,
    inner_grad_basis_grad_const,
    trace_matrix_value,
    trace_basis_tensor,
    trace_mixed_tensor,
    transpose_grad_tensor,
    transpose_mixed_grad_tensor,
    transpose_hessian_tensor,
    transpose_matrix,
    swap_mixed_basis_tensor,
    dot_value_with_grad,
    dot_grad_with_value,
    pushforward_d3,
    pushforward_d4,
    compute_physical_hessian,
    compute_physical_laplacian,
    load_variable_qp,
    gradient_qp,
    laplacian_qp,
    hessian_qp,
    ghost_grad_jump_penalty_scalar,
    ghost_grad_jump_penalty_vector,
    binary_add_generic,
    binary_add_3_4,
    binary_add_4_3,
    binary_sub_generic,
    binary_sub_3_4,
    binary_sub_4_3,
    scatter_tensor_to_union,
    pad_basis_to_union,
    pushforward_grad_to_union,
    contract_first_first
)
PARAM_ORDER = ['gdofs_map', 'node_coords', 'qp_phys', 'qw', 'detJ', 'J_inv', 'normals', 'example2_half', 'example2_local_lambda_s', 'example2_local_mu_s', 'example2_one', 'example2_two', 'example2_two_thirds', 'g_dx', 'g_dy', 'jit_const_0', 'jit_const_1', 'jit_const_2', 'jit_const_3', 'u_d_k_loc']
@numba.njit(parallel=True, fastmath=True, cache=True)
def kernel(
        gdofs_map, node_coords, qp_phys, qw, detJ, J_inv, normals, example2_half, example2_local_lambda_s, example2_local_mu_s, example2_one, example2_two, example2_two_thirds, g_dx, g_dy, jit_const_0, jit_const_1, jit_const_2, jit_const_3, u_d_k_loc
    ):
    num_elements        = qp_phys.shape[0]
    # n_dofs_per_element  = 8
    n_dofs_per_element  = gdofs_map.shape[1]            # 9 for volume, 15 on ghost edge
    # print(f"num_elements: {num_elements},n_dofs_per_element: {n_dofs_per_element}")
    # print(f"number of quadrature points: {qw.shape[1]}")

    K_values = np.zeros((num_elements, n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
    F_values = np.zeros((num_elements, n_dofs_per_element), dtype=np.float64)
    # Shape of the integrand that lands in “J”.
    # -------- functional accumulator ------------------------------------
    k = 0
    J_init = 0.0
    J     = J_init
    J_values = np.zeros((num_elements), dtype=np.float64)

    for e in numba.prange(num_elements):
        Ke = np.zeros((n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
        Fe = np.zeros(n_dofs_per_element, dtype=np.float64)
        J  = J_init.copy() if False else J_init

        n_union = gdofs_map.shape[1]

        u_d_k_loc_e = u_d_k_loc[e]

        for q in range(qw.shape[1]):
            x_q, w_q, J_inv_q = qp_phys[e, q], qw[e, q], J_inv[e, q]
            normal_q = normals[e, q] if normals is not None else np.zeros(2, dtype=np.float64)
            phi_q    = 0.0
            J_inv_q = J_inv[e,q]
            g_dx_q = g_dx[e,q]
            g_dy_q = g_dy[e,q]
            J_inv_q = J_inv[e, q]
            grad_loc_1 = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_2 = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_3 = np.stack((grad_loc_1, grad_loc_2))
            const_val_4 = example2_two.item()
            const_val_5 = example2_half.item()
            const_val_6 = example2_local_mu_s.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_7 = const_val_5 * const_val_6
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_8 = const_val_4 * res_7
            const_np_arr_9 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_11  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_10 = gradient_qp(u_d_k_loc_e, phys_grad_basis_11)
            phys_grad_basis_13  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_12 = gradient_qp(u_d_k_loc_e, phys_grad_basis_13)
            grad_val_stack_14 = np.stack((grad_val_10, grad_val_12))
            # Addition
            res_15 = binary_add_generic(const_np_arr_9, grad_val_stack_14, np.float64)
            a00 = res_15[0, 0]
            a01 = res_15[0, 1]
            a10 = res_15[1, 0]
            a11 = res_15[1, 1]
            det2_16 = a00 * a11 - a01 * a10
            # Division
            res_17 = res_8 / float(det2_16)
            const_np_arr_18 = jit_const_1
            const_val_19 = example2_half.item()
            const_np_arr_20 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_22  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_21 = gradient_qp(u_d_k_loc_e, phys_grad_basis_22)
            phys_grad_basis_24  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_23 = gradient_qp(u_d_k_loc_e, phys_grad_basis_24)
            grad_val_stack_25 = np.stack((grad_val_21, grad_val_23))
            # Addition
            res_26 = binary_add_generic(const_np_arr_20, grad_val_stack_25, np.float64)
            trp_27 = transpose_matrix(res_26, np.float64)
            const_np_arr_28 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_30  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_29 = gradient_qp(u_d_k_loc_e, phys_grad_basis_30)
            phys_grad_basis_32  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_31 = gradient_qp(u_d_k_loc_e, phys_grad_basis_32)
            grad_val_stack_33 = np.stack((grad_val_29, grad_val_31))
            # Addition
            res_34 = binary_add_generic(const_np_arr_28, grad_val_stack_33, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_35 = contract_last_first(trp_27, res_34, np.float64)
            # Trace of a computed matrix -> scalar value
            trace_res_36 = trace_matrix_value(dot_35, np.float64)
            # Product: const * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_37 = const_val_19 * trace_res_36
            const_np_arr_38 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_40  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_39 = gradient_qp(u_d_k_loc_e, phys_grad_basis_40)
            phys_grad_basis_42  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_41 = gradient_qp(u_d_k_loc_e, phys_grad_basis_42)
            grad_val_stack_43 = np.stack((grad_val_39, grad_val_41))
            # Addition
            res_44 = binary_add_generic(const_np_arr_38, grad_val_stack_43, np.float64)
            trp_45 = transpose_matrix(res_44, np.float64)
            const_np_arr_46 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_48  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_47 = gradient_qp(u_d_k_loc_e, phys_grad_basis_48)
            phys_grad_basis_50  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_49 = gradient_qp(u_d_k_loc_e, phys_grad_basis_50)
            grad_val_stack_51 = np.stack((grad_val_47, grad_val_49))
            # Addition
            res_52 = binary_add_generic(const_np_arr_46, grad_val_stack_51, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_53 = contract_last_first(trp_45, res_52, np.float64)
            a00 = dot_53[0, 0]
            a01 = dot_53[0, 1]
            a10 = dot_53[1, 0]
            a11 = dot_53[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_54 = np.empty((2, 2), dtype=np.float64)
            inv2_54[0, 0] =  a11 * inv_det
            inv2_54[0, 1] = -a01 * inv_det
            inv2_54[1, 0] = -a10 * inv_det
            inv2_54[1, 1] =  a00 * inv_det
            # Product: value * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_55 = mul_scalar(res_37, inv2_54, np.float64)
            # Subtraction
            res_56 = binary_sub_generic(const_np_arr_18, res_55, np.float64)
            # Product: value * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_57 = mul_scalar(res_17, res_56, np.float64)
            const_np_arr_58 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_60  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_59 = gradient_qp(u_d_k_loc_e, phys_grad_basis_60)
            phys_grad_basis_62  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_61 = gradient_qp(u_d_k_loc_e, phys_grad_basis_62)
            grad_val_stack_63 = np.stack((grad_val_59, grad_val_61))
            # Addition
            res_64 = binary_add_generic(const_np_arr_58, grad_val_stack_63, np.float64)
            a00 = res_64[0, 0]
            a01 = res_64[0, 1]
            a10 = res_64[1, 0]
            a11 = res_64[1, 1]
            det2_65 = a00 * a11 - a01 * a10
            const_val_66 = example2_local_lambda_s.item()
            const_val_67 = example2_two_thirds.item()
            const_val_68 = example2_local_mu_s.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_69 = const_val_67 * const_val_68
            # Addition
            res_70 = binary_add_generic(const_val_66, res_69, np.float64)
            const_np_arr_71 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_73  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_72 = gradient_qp(u_d_k_loc_e, phys_grad_basis_73)
            phys_grad_basis_75  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_74 = gradient_qp(u_d_k_loc_e, phys_grad_basis_75)
            grad_val_stack_76 = np.stack((grad_val_72, grad_val_74))
            # Addition
            res_77 = binary_add_generic(const_np_arr_71, grad_val_stack_76, np.float64)
            a00 = res_77[0, 0]
            a01 = res_77[0, 1]
            a10 = res_77[1, 0]
            a11 = res_77[1, 1]
            det2_78 = a00 * a11 - a01 * a10
            const_val_79 = example2_one.item()
            # Subtraction
            res_80 = binary_sub_generic(det2_78, const_val_79, np.float64)
            # Product: const * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_81 = res_70 * res_80
            # Product: value * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_82 = det2_65 * res_81
            const_np_arr_83 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_85  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_84 = gradient_qp(u_d_k_loc_e, phys_grad_basis_85)
            phys_grad_basis_87  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_86 = gradient_qp(u_d_k_loc_e, phys_grad_basis_87)
            grad_val_stack_88 = np.stack((grad_val_84, grad_val_86))
            # Addition
            res_89 = binary_add_generic(const_np_arr_83, grad_val_stack_88, np.float64)
            trp_90 = transpose_matrix(res_89, np.float64)
            const_np_arr_91 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_93  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_92 = gradient_qp(u_d_k_loc_e, phys_grad_basis_93)
            phys_grad_basis_95  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_94 = gradient_qp(u_d_k_loc_e, phys_grad_basis_95)
            grad_val_stack_96 = np.stack((grad_val_92, grad_val_94))
            # Addition
            res_97 = binary_add_generic(const_np_arr_91, grad_val_stack_96, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_98 = contract_last_first(trp_90, res_97, np.float64)
            a00 = dot_98[0, 0]
            a01 = dot_98[0, 1]
            a10 = dot_98[1, 0]
            a11 = dot_98[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_99 = np.empty((2, 2), dtype=np.float64)
            inv2_99[0, 0] =  a11 * inv_det
            inv2_99[0, 1] = -a01 * inv_det
            inv2_99[1, 0] = -a10 * inv_det
            inv2_99[1, 1] =  a00 * inv_det
            # Product: value * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_100 = mul_scalar(res_82, inv2_99, np.float64)
            # Addition
            res_101 = binary_add_generic(res_57, res_100, np.float64)
            # dot(grad(trial), grad(value)) -> (k,n,k) tensor basis
            dot_102 = dot_grad_basis_with_grad_value(grad_stack_3, res_101, np.float64)
            const_np_arr_103 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_105  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_104 = gradient_qp(u_d_k_loc_e, phys_grad_basis_105)
            phys_grad_basis_107  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_106 = gradient_qp(u_d_k_loc_e, phys_grad_basis_107)
            grad_val_stack_108 = np.stack((grad_val_104, grad_val_106))
            # Addition
            res_109 = binary_add_generic(const_np_arr_103, grad_val_stack_108, np.float64)
            const_val_110 = jit_const_2.item()
            const_val_111 = example2_two.item()
            const_val_112 = example2_half.item()
            const_val_113 = example2_local_mu_s.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_114 = const_val_112 * const_val_113
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_115 = const_val_111 * res_114
            const_val_116 = example2_two.item()
            const_np_arr_117 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_119  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_118 = gradient_qp(u_d_k_loc_e, phys_grad_basis_119)
            phys_grad_basis_121  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_120 = gradient_qp(u_d_k_loc_e, phys_grad_basis_121)
            grad_val_stack_122 = np.stack((grad_val_118, grad_val_120))
            # Addition
            res_123 = binary_add_generic(const_np_arr_117, grad_val_stack_122, np.float64)
            a00 = res_123[0, 0]
            a01 = res_123[0, 1]
            a10 = res_123[1, 0]
            a11 = res_123[1, 1]
            det2_124 = a00 * a11 - a01 * a10
            # Product: const * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_125 = const_val_116 * det2_124
            # Division
            res_126 = res_115 / float(res_125)
            # Product: const * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_127 = const_val_110 * res_126
            const_np_arr_128 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_130  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_129 = gradient_qp(u_d_k_loc_e, phys_grad_basis_130)
            phys_grad_basis_132  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_131 = gradient_qp(u_d_k_loc_e, phys_grad_basis_132)
            grad_val_stack_133 = np.stack((grad_val_129, grad_val_131))
            # Addition
            res_134 = binary_add_generic(const_np_arr_128, grad_val_stack_133, np.float64)
            trp_135 = transpose_matrix(res_134, np.float64)
            const_np_arr_136 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_138  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_137 = gradient_qp(u_d_k_loc_e, phys_grad_basis_138)
            phys_grad_basis_140  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_139 = gradient_qp(u_d_k_loc_e, phys_grad_basis_140)
            grad_val_stack_141 = np.stack((grad_val_137, grad_val_139))
            # Addition
            res_142 = binary_add_generic(const_np_arr_136, grad_val_stack_141, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_143 = contract_last_first(trp_135, res_142, np.float64)
            a00 = dot_143[0, 0]
            a01 = dot_143[0, 1]
            a10 = dot_143[1, 0]
            a11 = dot_143[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_144 = np.empty((2, 2), dtype=np.float64)
            inv2_144[0, 0] =  a11 * inv_det
            inv2_144[0, 1] = -a01 * inv_det
            inv2_144[1, 0] = -a10 * inv_det
            inv2_144[1, 1] =  a00 * inv_det
            J_inv_q = J_inv[e, q]
            grad_loc_145 = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_146 = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_147 = np.stack((grad_loc_145, grad_loc_146))
            trp_148 = transpose_grad_tensor(grad_stack_147, np.float64)
            const_np_arr_149 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_151  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_150 = gradient_qp(u_d_k_loc_e, phys_grad_basis_151)
            phys_grad_basis_153  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_152 = gradient_qp(u_d_k_loc_e, phys_grad_basis_153)
            grad_val_stack_154 = np.stack((grad_val_150, grad_val_152))
            # Addition
            res_155 = binary_add_generic(const_np_arr_149, grad_val_stack_154, np.float64)
            # dot(grad(trial), grad(value)) -> (k,n,k) tensor basis
            dot_156 = dot_grad_basis_with_grad_value(trp_148, res_155, np.float64)
            const_np_arr_157 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_159  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_158 = gradient_qp(u_d_k_loc_e, phys_grad_basis_159)
            phys_grad_basis_161  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_160 = gradient_qp(u_d_k_loc_e, phys_grad_basis_161)
            grad_val_stack_162 = np.stack((grad_val_158, grad_val_160))
            # Addition
            res_163 = binary_add_generic(const_np_arr_157, grad_val_stack_162, np.float64)
            trp_164 = transpose_matrix(res_163, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_165 = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_166 = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_167 = np.stack((grad_loc_165, grad_loc_166))
            # dot(grad(value), grad(trial)) -> (k,n,d) tensor basis
            dot_168 = dot_grad_value_with_grad_basis(trp_164, grad_stack_167, np.float64)
            # Addition
            res_169 = binary_add_generic(dot_156, dot_168, np.float64)
            # dot(grad(value), grad(trial)) -> (k,n,d) tensor basis
            dot_170 = dot_grad_value_with_grad_basis(inv2_144, res_169, np.float64)
            # Trace of a symbolic tensor -> scalar basis of shape (1, n)
            trace_res_171 = trace_basis_tensor(dot_170, np.float64)
            # Product: value * trial
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_172 = mul_scalar(res_127, trace_res_171, np.float64)
            const_np_arr_173 = jit_const_1
            const_val_174 = example2_half.item()
            const_np_arr_175 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_177  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_176 = gradient_qp(u_d_k_loc_e, phys_grad_basis_177)
            phys_grad_basis_179  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_178 = gradient_qp(u_d_k_loc_e, phys_grad_basis_179)
            grad_val_stack_180 = np.stack((grad_val_176, grad_val_178))
            # Addition
            res_181 = binary_add_generic(const_np_arr_175, grad_val_stack_180, np.float64)
            trp_182 = transpose_matrix(res_181, np.float64)
            const_np_arr_183 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_185  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_184 = gradient_qp(u_d_k_loc_e, phys_grad_basis_185)
            phys_grad_basis_187  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_186 = gradient_qp(u_d_k_loc_e, phys_grad_basis_187)
            grad_val_stack_188 = np.stack((grad_val_184, grad_val_186))
            # Addition
            res_189 = binary_add_generic(const_np_arr_183, grad_val_stack_188, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_190 = contract_last_first(trp_182, res_189, np.float64)
            # Trace of a computed matrix -> scalar value
            trace_res_191 = trace_matrix_value(dot_190, np.float64)
            # Product: const * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_192 = const_val_174 * trace_res_191
            const_np_arr_193 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_195  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_194 = gradient_qp(u_d_k_loc_e, phys_grad_basis_195)
            phys_grad_basis_197  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_196 = gradient_qp(u_d_k_loc_e, phys_grad_basis_197)
            grad_val_stack_198 = np.stack((grad_val_194, grad_val_196))
            # Addition
            res_199 = binary_add_generic(const_np_arr_193, grad_val_stack_198, np.float64)
            trp_200 = transpose_matrix(res_199, np.float64)
            const_np_arr_201 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_203  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_202 = gradient_qp(u_d_k_loc_e, phys_grad_basis_203)
            phys_grad_basis_205  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_204 = gradient_qp(u_d_k_loc_e, phys_grad_basis_205)
            grad_val_stack_206 = np.stack((grad_val_202, grad_val_204))
            # Addition
            res_207 = binary_add_generic(const_np_arr_201, grad_val_stack_206, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_208 = contract_last_first(trp_200, res_207, np.float64)
            a00 = dot_208[0, 0]
            a01 = dot_208[0, 1]
            a10 = dot_208[1, 0]
            a11 = dot_208[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_209 = np.empty((2, 2), dtype=np.float64)
            inv2_209[0, 0] =  a11 * inv_det
            inv2_209[0, 1] = -a01 * inv_det
            inv2_209[1, 0] = -a10 * inv_det
            inv2_209[1, 1] =  a00 * inv_det
            # Product: value * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_210 = mul_scalar(res_192, inv2_209, np.float64)
            # Subtraction
            res_211 = binary_sub_generic(const_np_arr_173, res_210, np.float64)
            # Product: trial * value
            # rhs: trace(trial) * Identity → 
            res_212 = trace_times_identity(res_172, res_211, np.float64)
            const_val_213 = example2_two.item()
            const_val_214 = example2_half.item()
            const_val_215 = example2_local_mu_s.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_216 = const_val_214 * const_val_215
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_217 = const_val_213 * res_216
            const_np_arr_218 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_220  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_219 = gradient_qp(u_d_k_loc_e, phys_grad_basis_220)
            phys_grad_basis_222  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_221 = gradient_qp(u_d_k_loc_e, phys_grad_basis_222)
            grad_val_stack_223 = np.stack((grad_val_219, grad_val_221))
            # Addition
            res_224 = binary_add_generic(const_np_arr_218, grad_val_stack_223, np.float64)
            a00 = res_224[0, 0]
            a01 = res_224[0, 1]
            a10 = res_224[1, 0]
            a11 = res_224[1, 1]
            det2_225 = a00 * a11 - a01 * a10
            # Division
            res_226 = res_217 / float(det2_225)
            const_val_227 = jit_const_3.item()
            const_val_228 = example2_half.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_229 = const_val_227 * const_val_228
            J_inv_q = J_inv[e, q]
            grad_loc_230 = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_231 = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_232 = np.stack((grad_loc_230, grad_loc_231))
            trp_233 = transpose_grad_tensor(grad_stack_232, np.float64)
            const_np_arr_234 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_236  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_235 = gradient_qp(u_d_k_loc_e, phys_grad_basis_236)
            phys_grad_basis_238  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_237 = gradient_qp(u_d_k_loc_e, phys_grad_basis_238)
            grad_val_stack_239 = np.stack((grad_val_235, grad_val_237))
            # Addition
            res_240 = binary_add_generic(const_np_arr_234, grad_val_stack_239, np.float64)
            # dot(grad(trial), grad(value)) -> (k,n,k) tensor basis
            dot_241 = dot_grad_basis_with_grad_value(trp_233, res_240, np.float64)
            const_np_arr_242 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_244  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_243 = gradient_qp(u_d_k_loc_e, phys_grad_basis_244)
            phys_grad_basis_246  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_245 = gradient_qp(u_d_k_loc_e, phys_grad_basis_246)
            grad_val_stack_247 = np.stack((grad_val_243, grad_val_245))
            # Addition
            res_248 = binary_add_generic(const_np_arr_242, grad_val_stack_247, np.float64)
            trp_249 = transpose_matrix(res_248, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_250 = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_251 = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_252 = np.stack((grad_loc_250, grad_loc_251))
            # dot(grad(value), grad(trial)) -> (k,n,d) tensor basis
            dot_253 = dot_grad_value_with_grad_basis(trp_249, grad_stack_252, np.float64)
            # Addition
            res_254 = binary_add_generic(dot_241, dot_253, np.float64)
            # Trace of a symbolic tensor -> scalar basis of shape (1, n)
            trace_res_255 = trace_basis_tensor(res_254, np.float64)
            # Product: const * trial
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_256 = mul_scalar(res_229, trace_res_255, np.float64)
            const_np_arr_257 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_259  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_258 = gradient_qp(u_d_k_loc_e, phys_grad_basis_259)
            phys_grad_basis_261  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_260 = gradient_qp(u_d_k_loc_e, phys_grad_basis_261)
            grad_val_stack_262 = np.stack((grad_val_258, grad_val_260))
            # Addition
            res_263 = binary_add_generic(const_np_arr_257, grad_val_stack_262, np.float64)
            trp_264 = transpose_matrix(res_263, np.float64)
            const_np_arr_265 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_267  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_266 = gradient_qp(u_d_k_loc_e, phys_grad_basis_267)
            phys_grad_basis_269  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_268 = gradient_qp(u_d_k_loc_e, phys_grad_basis_269)
            grad_val_stack_270 = np.stack((grad_val_266, grad_val_268))
            # Addition
            res_271 = binary_add_generic(const_np_arr_265, grad_val_stack_270, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_272 = contract_last_first(trp_264, res_271, np.float64)
            a00 = dot_272[0, 0]
            a01 = dot_272[0, 1]
            a10 = dot_272[1, 0]
            a11 = dot_272[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_273 = np.empty((2, 2), dtype=np.float64)
            inv2_273[0, 0] =  a11 * inv_det
            inv2_273[0, 1] = -a01 * inv_det
            inv2_273[1, 0] = -a10 * inv_det
            inv2_273[1, 1] =  a00 * inv_det
            # Product: trial * value
            # rhs: trace(trial) * Identity → 
            res_274 = trace_times_identity(res_256, inv2_273, np.float64)
            const_val_275 = example2_half.item()
            const_np_arr_276 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_278  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_277 = gradient_qp(u_d_k_loc_e, phys_grad_basis_278)
            phys_grad_basis_280  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_279 = gradient_qp(u_d_k_loc_e, phys_grad_basis_280)
            grad_val_stack_281 = np.stack((grad_val_277, grad_val_279))
            # Addition
            res_282 = binary_add_generic(const_np_arr_276, grad_val_stack_281, np.float64)
            trp_283 = transpose_matrix(res_282, np.float64)
            const_np_arr_284 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_286  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_285 = gradient_qp(u_d_k_loc_e, phys_grad_basis_286)
            phys_grad_basis_288  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_287 = gradient_qp(u_d_k_loc_e, phys_grad_basis_288)
            grad_val_stack_289 = np.stack((grad_val_285, grad_val_287))
            # Addition
            res_290 = binary_add_generic(const_np_arr_284, grad_val_stack_289, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_291 = contract_last_first(trp_283, res_290, np.float64)
            # Trace of a computed matrix -> scalar value
            trace_res_292 = trace_matrix_value(dot_291, np.float64)
            # Product: const * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_293 = const_val_275 * trace_res_292
            const_np_arr_294 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_296  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_295 = gradient_qp(u_d_k_loc_e, phys_grad_basis_296)
            phys_grad_basis_298  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_297 = gradient_qp(u_d_k_loc_e, phys_grad_basis_298)
            grad_val_stack_299 = np.stack((grad_val_295, grad_val_297))
            # Addition
            res_300 = binary_add_generic(const_np_arr_294, grad_val_stack_299, np.float64)
            trp_301 = transpose_matrix(res_300, np.float64)
            const_np_arr_302 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_304  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_303 = gradient_qp(u_d_k_loc_e, phys_grad_basis_304)
            phys_grad_basis_306  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_305 = gradient_qp(u_d_k_loc_e, phys_grad_basis_306)
            grad_val_stack_307 = np.stack((grad_val_303, grad_val_305))
            # Addition
            res_308 = binary_add_generic(const_np_arr_302, grad_val_stack_307, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_309 = contract_last_first(trp_301, res_308, np.float64)
            a00 = dot_309[0, 0]
            a01 = dot_309[0, 1]
            a10 = dot_309[1, 0]
            a11 = dot_309[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_310 = np.empty((2, 2), dtype=np.float64)
            inv2_310[0, 0] =  a11 * inv_det
            inv2_310[0, 1] = -a01 * inv_det
            inv2_310[1, 0] = -a10 * inv_det
            inv2_310[1, 1] =  a00 * inv_det
            J_inv_q = J_inv[e, q]
            grad_loc_311 = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_312 = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_313 = np.stack((grad_loc_311, grad_loc_312))
            trp_314 = transpose_grad_tensor(grad_stack_313, np.float64)
            const_np_arr_315 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_317  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_316 = gradient_qp(u_d_k_loc_e, phys_grad_basis_317)
            phys_grad_basis_319  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_318 = gradient_qp(u_d_k_loc_e, phys_grad_basis_319)
            grad_val_stack_320 = np.stack((grad_val_316, grad_val_318))
            # Addition
            res_321 = binary_add_generic(const_np_arr_315, grad_val_stack_320, np.float64)
            # dot(grad(trial), grad(value)) -> (k,n,k) tensor basis
            dot_322 = dot_grad_basis_with_grad_value(trp_314, res_321, np.float64)
            const_np_arr_323 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_325  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_324 = gradient_qp(u_d_k_loc_e, phys_grad_basis_325)
            phys_grad_basis_327  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_326 = gradient_qp(u_d_k_loc_e, phys_grad_basis_327)
            grad_val_stack_328 = np.stack((grad_val_324, grad_val_326))
            # Addition
            res_329 = binary_add_generic(const_np_arr_323, grad_val_stack_328, np.float64)
            trp_330 = transpose_matrix(res_329, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_331 = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_332 = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_333 = np.stack((grad_loc_331, grad_loc_332))
            # dot(grad(value), grad(trial)) -> (k,n,d) tensor basis
            dot_334 = dot_grad_value_with_grad_basis(trp_330, grad_stack_333, np.float64)
            # Addition
            res_335 = binary_add_generic(dot_322, dot_334, np.float64)
            # dot(grad(value), grad(trial)) -> (k,n,d) tensor basis
            dot_336 = dot_grad_value_with_grad_basis(inv2_310, res_335, np.float64)
            const_np_arr_337 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_339  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_338 = gradient_qp(u_d_k_loc_e, phys_grad_basis_339)
            phys_grad_basis_341  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_340 = gradient_qp(u_d_k_loc_e, phys_grad_basis_341)
            grad_val_stack_342 = np.stack((grad_val_338, grad_val_340))
            # Addition
            res_343 = binary_add_generic(const_np_arr_337, grad_val_stack_342, np.float64)
            trp_344 = transpose_matrix(res_343, np.float64)
            const_np_arr_345 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_347  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_346 = gradient_qp(u_d_k_loc_e, phys_grad_basis_347)
            phys_grad_basis_349  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_348 = gradient_qp(u_d_k_loc_e, phys_grad_basis_349)
            grad_val_stack_350 = np.stack((grad_val_346, grad_val_348))
            # Addition
            res_351 = binary_add_generic(const_np_arr_345, grad_val_stack_350, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_352 = contract_last_first(trp_344, res_351, np.float64)
            a00 = dot_352[0, 0]
            a01 = dot_352[0, 1]
            a10 = dot_352[1, 0]
            a11 = dot_352[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_353 = np.empty((2, 2), dtype=np.float64)
            inv2_353[0, 0] =  a11 * inv_det
            inv2_353[0, 1] = -a01 * inv_det
            inv2_353[1, 0] = -a10 * inv_det
            inv2_353[1, 1] =  a00 * inv_det
            # dot(grad(trial), grad(value)) -> (k,n,k) tensor basis
            dot_354 = dot_grad_basis_with_grad_value(dot_336, inv2_353, np.float64)
            # Product: value * trial
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_355 = mul_scalar(res_293, dot_354, np.float64)
            # Addition
            res_356 = binary_add_generic(res_274, res_355, np.float64)
            # Product: value * trial
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_357 = mul_scalar(res_226, res_356, np.float64)
            # Addition
            res_358 = binary_add_generic(res_212, res_357, np.float64)
            const_val_359 = example2_half.item()
            const_val_360 = example2_local_lambda_s.item()
            const_val_361 = example2_two_thirds.item()
            const_val_362 = example2_local_mu_s.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_363 = const_val_361 * const_val_362
            # Addition
            res_364 = binary_add_generic(const_val_360, res_363, np.float64)
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_365 = const_val_359 * res_364
            const_np_arr_366 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_368  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_367 = gradient_qp(u_d_k_loc_e, phys_grad_basis_368)
            phys_grad_basis_370  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_369 = gradient_qp(u_d_k_loc_e, phys_grad_basis_370)
            grad_val_stack_371 = np.stack((grad_val_367, grad_val_369))
            # Addition
            res_372 = binary_add_generic(const_np_arr_366, grad_val_stack_371, np.float64)
            a00 = res_372[0, 0]
            a01 = res_372[0, 1]
            a10 = res_372[1, 0]
            a11 = res_372[1, 1]
            det2_373 = a00 * a11 - a01 * a10
            # Product: const * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_374 = res_365 * det2_373
            const_val_375 = example2_two.item()
            const_np_arr_376 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_378  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_377 = gradient_qp(u_d_k_loc_e, phys_grad_basis_378)
            phys_grad_basis_380  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_379 = gradient_qp(u_d_k_loc_e, phys_grad_basis_380)
            grad_val_stack_381 = np.stack((grad_val_377, grad_val_379))
            # Addition
            res_382 = binary_add_generic(const_np_arr_376, grad_val_stack_381, np.float64)
            a00 = res_382[0, 0]
            a01 = res_382[0, 1]
            a10 = res_382[1, 0]
            a11 = res_382[1, 1]
            det2_383 = a00 * a11 - a01 * a10
            # Product: const * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_384 = const_val_375 * det2_383
            const_val_385 = example2_one.item()
            # Subtraction
            res_386 = binary_sub_generic(res_384, const_val_385, np.float64)
            # Product: value * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_387 = res_374 * res_386
            const_np_arr_388 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_390  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_389 = gradient_qp(u_d_k_loc_e, phys_grad_basis_390)
            phys_grad_basis_392  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_391 = gradient_qp(u_d_k_loc_e, phys_grad_basis_392)
            grad_val_stack_393 = np.stack((grad_val_389, grad_val_391))
            # Addition
            res_394 = binary_add_generic(const_np_arr_388, grad_val_stack_393, np.float64)
            trp_395 = transpose_matrix(res_394, np.float64)
            const_np_arr_396 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_398  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_397 = gradient_qp(u_d_k_loc_e, phys_grad_basis_398)
            phys_grad_basis_400  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_399 = gradient_qp(u_d_k_loc_e, phys_grad_basis_400)
            grad_val_stack_401 = np.stack((grad_val_397, grad_val_399))
            # Addition
            res_402 = binary_add_generic(const_np_arr_396, grad_val_stack_401, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_403 = contract_last_first(trp_395, res_402, np.float64)
            a00 = dot_403[0, 0]
            a01 = dot_403[0, 1]
            a10 = dot_403[1, 0]
            a11 = dot_403[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_404 = np.empty((2, 2), dtype=np.float64)
            inv2_404[0, 0] =  a11 * inv_det
            inv2_404[0, 1] = -a01 * inv_det
            inv2_404[1, 0] = -a10 * inv_det
            inv2_404[1, 1] =  a00 * inv_det
            J_inv_q = J_inv[e, q]
            grad_loc_405 = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_406 = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_407 = np.stack((grad_loc_405, grad_loc_406))
            trp_408 = transpose_grad_tensor(grad_stack_407, np.float64)
            const_np_arr_409 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_411  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_410 = gradient_qp(u_d_k_loc_e, phys_grad_basis_411)
            phys_grad_basis_413  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_412 = gradient_qp(u_d_k_loc_e, phys_grad_basis_413)
            grad_val_stack_414 = np.stack((grad_val_410, grad_val_412))
            # Addition
            res_415 = binary_add_generic(const_np_arr_409, grad_val_stack_414, np.float64)
            # dot(grad(trial), grad(value)) -> (k,n,k) tensor basis
            dot_416 = dot_grad_basis_with_grad_value(trp_408, res_415, np.float64)
            const_np_arr_417 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_419  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_418 = gradient_qp(u_d_k_loc_e, phys_grad_basis_419)
            phys_grad_basis_421  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_420 = gradient_qp(u_d_k_loc_e, phys_grad_basis_421)
            grad_val_stack_422 = np.stack((grad_val_418, grad_val_420))
            # Addition
            res_423 = binary_add_generic(const_np_arr_417, grad_val_stack_422, np.float64)
            trp_424 = transpose_matrix(res_423, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_425 = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_426 = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_427 = np.stack((grad_loc_425, grad_loc_426))
            # dot(grad(value), grad(trial)) -> (k,n,d) tensor basis
            dot_428 = dot_grad_value_with_grad_basis(trp_424, grad_stack_427, np.float64)
            # Addition
            res_429 = binary_add_generic(dot_416, dot_428, np.float64)
            # dot(grad(value), grad(trial)) -> (k,n,d) tensor basis
            dot_430 = dot_grad_value_with_grad_basis(inv2_404, res_429, np.float64)
            # Trace of a symbolic tensor -> scalar basis of shape (1, n)
            trace_res_431 = trace_basis_tensor(dot_430, np.float64)
            # Product: value * trial
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_432 = mul_scalar(res_387, trace_res_431, np.float64)
            const_np_arr_433 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_435  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_434 = gradient_qp(u_d_k_loc_e, phys_grad_basis_435)
            phys_grad_basis_437  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_436 = gradient_qp(u_d_k_loc_e, phys_grad_basis_437)
            grad_val_stack_438 = np.stack((grad_val_434, grad_val_436))
            # Addition
            res_439 = binary_add_generic(const_np_arr_433, grad_val_stack_438, np.float64)
            trp_440 = transpose_matrix(res_439, np.float64)
            const_np_arr_441 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_443  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_442 = gradient_qp(u_d_k_loc_e, phys_grad_basis_443)
            phys_grad_basis_445  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_444 = gradient_qp(u_d_k_loc_e, phys_grad_basis_445)
            grad_val_stack_446 = np.stack((grad_val_442, grad_val_444))
            # Addition
            res_447 = binary_add_generic(const_np_arr_441, grad_val_stack_446, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_448 = contract_last_first(trp_440, res_447, np.float64)
            a00 = dot_448[0, 0]
            a01 = dot_448[0, 1]
            a10 = dot_448[1, 0]
            a11 = dot_448[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_449 = np.empty((2, 2), dtype=np.float64)
            inv2_449[0, 0] =  a11 * inv_det
            inv2_449[0, 1] = -a01 * inv_det
            inv2_449[1, 0] = -a10 * inv_det
            inv2_449[1, 1] =  a00 * inv_det
            # Product: trial * value
            # rhs: trace(trial) * Identity → 
            res_450 = trace_times_identity(res_432, inv2_449, np.float64)
            const_val_451 = example2_local_lambda_s.item()
            const_val_452 = example2_two_thirds.item()
            const_val_453 = example2_local_mu_s.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_454 = const_val_452 * const_val_453
            # Addition
            res_455 = binary_add_generic(const_val_451, res_454, np.float64)
            const_np_arr_456 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_458  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_457 = gradient_qp(u_d_k_loc_e, phys_grad_basis_458)
            phys_grad_basis_460  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_459 = gradient_qp(u_d_k_loc_e, phys_grad_basis_460)
            grad_val_stack_461 = np.stack((grad_val_457, grad_val_459))
            # Addition
            res_462 = binary_add_generic(const_np_arr_456, grad_val_stack_461, np.float64)
            a00 = res_462[0, 0]
            a01 = res_462[0, 1]
            a10 = res_462[1, 0]
            a11 = res_462[1, 1]
            det2_463 = a00 * a11 - a01 * a10
            # Product: const * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_464 = res_455 * det2_463
            const_np_arr_465 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_467  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_466 = gradient_qp(u_d_k_loc_e, phys_grad_basis_467)
            phys_grad_basis_469  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_468 = gradient_qp(u_d_k_loc_e, phys_grad_basis_469)
            grad_val_stack_470 = np.stack((grad_val_466, grad_val_468))
            # Addition
            res_471 = binary_add_generic(const_np_arr_465, grad_val_stack_470, np.float64)
            a00 = res_471[0, 0]
            a01 = res_471[0, 1]
            a10 = res_471[1, 0]
            a11 = res_471[1, 1]
            det2_472 = a00 * a11 - a01 * a10
            const_val_473 = example2_one.item()
            # Subtraction
            res_474 = binary_sub_generic(det2_472, const_val_473, np.float64)
            # Product: value * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_475 = res_464 * res_474
            const_np_arr_476 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_478  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_477 = gradient_qp(u_d_k_loc_e, phys_grad_basis_478)
            phys_grad_basis_480  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_479 = gradient_qp(u_d_k_loc_e, phys_grad_basis_480)
            grad_val_stack_481 = np.stack((grad_val_477, grad_val_479))
            # Addition
            res_482 = binary_add_generic(const_np_arr_476, grad_val_stack_481, np.float64)
            trp_483 = transpose_matrix(res_482, np.float64)
            const_np_arr_484 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_486  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_485 = gradient_qp(u_d_k_loc_e, phys_grad_basis_486)
            phys_grad_basis_488  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_487 = gradient_qp(u_d_k_loc_e, phys_grad_basis_488)
            grad_val_stack_489 = np.stack((grad_val_485, grad_val_487))
            # Addition
            res_490 = binary_add_generic(const_np_arr_484, grad_val_stack_489, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_491 = contract_last_first(trp_483, res_490, np.float64)
            a00 = dot_491[0, 0]
            a01 = dot_491[0, 1]
            a10 = dot_491[1, 0]
            a11 = dot_491[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_492 = np.empty((2, 2), dtype=np.float64)
            inv2_492[0, 0] =  a11 * inv_det
            inv2_492[0, 1] = -a01 * inv_det
            inv2_492[1, 0] = -a10 * inv_det
            inv2_492[1, 1] =  a00 * inv_det
            J_inv_q = J_inv[e, q]
            grad_loc_493 = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_494 = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_495 = np.stack((grad_loc_493, grad_loc_494))
            trp_496 = transpose_grad_tensor(grad_stack_495, np.float64)
            const_np_arr_497 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_499  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_498 = gradient_qp(u_d_k_loc_e, phys_grad_basis_499)
            phys_grad_basis_501  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_500 = gradient_qp(u_d_k_loc_e, phys_grad_basis_501)
            grad_val_stack_502 = np.stack((grad_val_498, grad_val_500))
            # Addition
            res_503 = binary_add_generic(const_np_arr_497, grad_val_stack_502, np.float64)
            # dot(grad(trial), grad(value)) -> (k,n,k) tensor basis
            dot_504 = dot_grad_basis_with_grad_value(trp_496, res_503, np.float64)
            const_np_arr_505 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_507  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_506 = gradient_qp(u_d_k_loc_e, phys_grad_basis_507)
            phys_grad_basis_509  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_508 = gradient_qp(u_d_k_loc_e, phys_grad_basis_509)
            grad_val_stack_510 = np.stack((grad_val_506, grad_val_508))
            # Addition
            res_511 = binary_add_generic(const_np_arr_505, grad_val_stack_510, np.float64)
            trp_512 = transpose_matrix(res_511, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_513 = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_514 = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_515 = np.stack((grad_loc_513, grad_loc_514))
            # dot(grad(value), grad(trial)) -> (k,n,d) tensor basis
            dot_516 = dot_grad_value_with_grad_basis(trp_512, grad_stack_515, np.float64)
            # Addition
            res_517 = binary_add_generic(dot_504, dot_516, np.float64)
            # dot(grad(value), grad(trial)) -> (k,n,d) tensor basis
            dot_518 = dot_grad_value_with_grad_basis(inv2_492, res_517, np.float64)
            const_np_arr_519 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_521  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_520 = gradient_qp(u_d_k_loc_e, phys_grad_basis_521)
            phys_grad_basis_523  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_522 = gradient_qp(u_d_k_loc_e, phys_grad_basis_523)
            grad_val_stack_524 = np.stack((grad_val_520, grad_val_522))
            # Addition
            res_525 = binary_add_generic(const_np_arr_519, grad_val_stack_524, np.float64)
            trp_526 = transpose_matrix(res_525, np.float64)
            const_np_arr_527 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_529  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_528 = gradient_qp(u_d_k_loc_e, phys_grad_basis_529)
            phys_grad_basis_531  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_530 = gradient_qp(u_d_k_loc_e, phys_grad_basis_531)
            grad_val_stack_532 = np.stack((grad_val_528, grad_val_530))
            # Addition
            res_533 = binary_add_generic(const_np_arr_527, grad_val_stack_532, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_534 = contract_last_first(trp_526, res_533, np.float64)
            a00 = dot_534[0, 0]
            a01 = dot_534[0, 1]
            a10 = dot_534[1, 0]
            a11 = dot_534[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_535 = np.empty((2, 2), dtype=np.float64)
            inv2_535[0, 0] =  a11 * inv_det
            inv2_535[0, 1] = -a01 * inv_det
            inv2_535[1, 0] = -a10 * inv_det
            inv2_535[1, 1] =  a00 * inv_det
            # dot(grad(trial), grad(value)) -> (k,n,k) tensor basis
            dot_536 = dot_grad_basis_with_grad_value(dot_518, inv2_535, np.float64)
            # Product: value * trial
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_537 = mul_scalar(res_475, dot_536, np.float64)
            # Subtraction
            res_538 = binary_sub_generic(res_450, res_537, np.float64)
            # Addition
            res_539 = binary_add_generic(res_358, res_538, np.float64)
            # dot(grad(value), grad(trial)) -> (k,n,d) tensor basis
            dot_540 = dot_grad_value_with_grad_basis(res_109, res_539, np.float64)
            # Addition
            res_541 = binary_add_generic(dot_102, dot_540, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_542 = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_543 = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_544 = np.stack((grad_loc_542, grad_loc_543))
            # Inner(LHS): orient rows=test, cols=trial
            inner_545 = inner_grad_grad(grad_stack_544, res_541, np.float64)
            Ke += inner_545 * w_q

        K_values[e] = Ke
        F_values[e] = Fe
        J_values[e] = J

    return K_values, F_values, J_values


def get_kernel(analytic_map):
    pass
    return kernel
