# This file is auto-generated by pycutfem JIT – DO NOT EDIT
import numpy as np
import numba

CODEGEN_ABI = "2026-04-07-abi-dot-product-ghost-layout-v14"

import numba
import numpy as np
from pycutfem.jit.numba_helpers import (
    dot_grad_grad_mixed,
    contract_last_first,
    dot_mixed_const,
    dot_const_mixed,
    dot_vector_trial_grad_test,
    dot_mass_test_trial,
    dot_mass_trial_test,
    dot_grad_func_trial_vec,
    dot_trial_vec_grad_func,
    dot_vec_vec,
    dot_grad_grad_value,
    mul_scalar,
    dot_grad_basis_vector,
    vector_dot_grad_basis,
    vector_dot_grad_value,
    dot_grad_basis_with_grad_value,
    dot_grad_value_with_grad_basis,
    basis_dot_const_vector,
        const_vector_dot_basis,
        const_vector_dot_basis_1d,
        scalar_basis_times_vector,
        scalar_basis_times_vector_as_grad_tensor,
        matrix_times_scalar_basis,
        scalar_vector_outer_product,
        vector_trial_times_scalar_test,
        vector_test_times_scalar_trial,
        vector_vector_outer_product,
    dot_vec_grad_components,
    scalar_trial_times_grad_test,
    scalar_trial_times_basis_test,
    grad_trial_times_scalar_test,
    basis_trial_times_scalar_test,
    scale_mixed_basis_with_coeffs,
    trace_times_identity,
    identity_times_trace_matrix,
    columnwise_dot,
    hessian_dot_vector,
    vector_dot_hessian_basis,
    vector_dot_hessian_value,
    inner_rank2_value_rank2_basis,
    inner_rank2_basis_rank2_value,
    inner_grad_grad,
    inner_hessian_hessian,
    inner_grad_function_grad_test,
    inner_hessian_function_hessian_test,
    inner_mixed_grad_const,
    inner_grad_const_mixed,
    inner_grad_basis_grad_const,
    trace_matrix_value,
    trace_basis_tensor,
    trace_mixed_tensor,
    transpose_grad_tensor,
    transpose_mixed_grad_tensor,
    transpose_hessian_tensor,
    transpose_matrix,
    swap_mixed_basis_tensor,
    dot_value_with_grad,
    dot_grad_with_value,
    pushforward_d3,
    pushforward_d4,
    compute_physical_hessian,
    compute_physical_laplacian,
    load_variable_qp,
    gradient_qp,
    laplacian_qp,
    hessian_qp,
    ghost_grad_jump_penalty_scalar,
    ghost_grad_jump_penalty_vector,
    binary_add_generic,
    binary_add_3_4,
    binary_add_4_3,
    binary_sub_generic,
    binary_sub_3_4,
    binary_sub_4_3,
    scatter_tensor_to_union,
    pad_basis_to_union,
    pushforward_grad_to_union,
    contract_first_first
)
PARAM_ORDER = ['gdofs_map', 'node_coords', 'qp_phys', 'qw', 'detJ', 'J_inv', 'normals', 'b_p', 'g_mx', 'g_my', 'g_ux', 'g_uy', 'jit_const_0', 'jit_const_1', 'jit_const_2', 'u_d_mesh_loc', 'u_p_k_loc', 'u_u_k_loc']
@numba.njit(parallel=True, fastmath=True, cache=True)
def kernel(
        gdofs_map, node_coords, qp_phys, qw, detJ, J_inv, normals, b_p, g_mx, g_my, g_ux, g_uy, jit_const_0, jit_const_1, jit_const_2, u_d_mesh_loc, u_p_k_loc, u_u_k_loc
    ):
    num_elements        = qp_phys.shape[0]
    # n_dofs_per_element  = 40
    n_dofs_per_element  = gdofs_map.shape[1]            # 9 for volume, 15 on ghost edge
    # print(f"num_elements: {num_elements},n_dofs_per_element: {n_dofs_per_element}")
    # print(f"number of quadrature points: {qw.shape[1]}")

    K_values = np.zeros((num_elements, n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
    F_values = np.zeros((num_elements, n_dofs_per_element), dtype=np.float64)
    # Shape of the integrand that lands in “J”.
    # -------- functional accumulator ------------------------------------
    k = 0
    J_init = 0.0
    J     = J_init
    J_values = np.zeros((num_elements), dtype=np.float64)

    for e in numba.prange(num_elements):
        Ke = np.zeros((n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
        Fe = np.zeros(n_dofs_per_element, dtype=np.float64)
        J  = J_init.copy() if False else J_init

        n_union = gdofs_map.shape[1]

        u_d_mesh_loc_e = u_d_mesh_loc[e]
        u_p_k_loc_e = u_p_k_loc[e]
        u_u_k_loc_e = u_u_k_loc[e]

        for q in range(qw.shape[1]):
            x_q, w_q, J_inv_q = qp_phys[e, q], qw[e, q], J_inv[e, q]
            normal_q = normals[e, q] if normals is not None else np.zeros(2, dtype=np.float64)
            phi_q    = 0.0
            J_inv_q = J_inv[e,q]
            b_p_q = b_p[e,q]
            g_mx_q = g_mx[e,q]
            g_my_q = g_my[e,q]
            g_ux_q = g_ux[e,q]
            g_uy_q = g_uy[e,q]
            const_np_arr_1 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_3  = np.ascontiguousarray(g_mx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_2 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_3)
            phys_grad_basis_5  = np.ascontiguousarray(g_my[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_4 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_5)
            grad_val_stack_6 = np.stack((grad_val_2, grad_val_4))
            # Addition
            res_7 = binary_add_generic(const_np_arr_1, grad_val_stack_6, np.float64)
            a00 = res_7[0, 0]
            a01 = res_7[0, 1]
            a10 = res_7[1, 0]
            a11 = res_7[1, 1]
            det2_8 = a00 * a11 - a01 * a10
            const_val_9 = jit_const_1.item()
            p_k_val_10 = load_variable_qp(u_p_k_loc_e, b_p[e, q])
            # Product: const * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_11 = const_val_9 * p_k_val_10
            const_np_arr_12 = jit_const_0
            # Product: value * const
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_13 = mul_scalar(res_11, const_np_arr_12, np.float64)
            const_val_14 = jit_const_2.item()
            J_inv_q = J_inv[e, q]
            phys_grad_basis_16  = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_15 = gradient_qp(u_u_k_loc_e, phys_grad_basis_16)
            phys_grad_basis_18  = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_17 = gradient_qp(u_u_k_loc_e, phys_grad_basis_18)
            grad_val_stack_19 = np.stack((grad_val_15, grad_val_17))
            const_np_arr_20 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_22  = np.ascontiguousarray(g_mx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_21 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_22)
            phys_grad_basis_24  = np.ascontiguousarray(g_my[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_23 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_24)
            grad_val_stack_25 = np.stack((grad_val_21, grad_val_23))
            # Addition
            res_26 = binary_add_generic(const_np_arr_20, grad_val_stack_25, np.float64)
            a00 = res_26[0, 0]
            a01 = res_26[0, 1]
            a10 = res_26[1, 0]
            a11 = res_26[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_27 = np.empty((2, 2), dtype=np.float64)
            inv2_27[0, 0] =  a11 * inv_det
            inv2_27[0, 1] = -a01 * inv_det
            inv2_27[1, 0] = -a10 * inv_det
            inv2_27[1, 1] =  a00 * inv_det
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_28 = contract_last_first(grad_val_stack_19, inv2_27, np.float64)
            const_np_arr_29 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_31  = np.ascontiguousarray(g_mx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_30 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_31)
            phys_grad_basis_33  = np.ascontiguousarray(g_my[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_32 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_33)
            grad_val_stack_34 = np.stack((grad_val_30, grad_val_32))
            # Addition
            res_35 = binary_add_generic(const_np_arr_29, grad_val_stack_34, np.float64)
            a00 = res_35[0, 0]
            a01 = res_35[0, 1]
            a10 = res_35[1, 0]
            a11 = res_35[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_36 = np.empty((2, 2), dtype=np.float64)
            inv2_36[0, 0] =  a11 * inv_det
            inv2_36[0, 1] = -a01 * inv_det
            inv2_36[1, 0] = -a10 * inv_det
            inv2_36[1, 1] =  a00 * inv_det
            trp_37 = transpose_matrix(inv2_36, np.float64)
            J_inv_q = J_inv[e, q]
            phys_grad_basis_39  = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_38 = gradient_qp(u_u_k_loc_e, phys_grad_basis_39)
            phys_grad_basis_41  = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_40 = gradient_qp(u_u_k_loc_e, phys_grad_basis_41)
            grad_val_stack_42 = np.stack((grad_val_38, grad_val_40))
            trp_43 = transpose_matrix(grad_val_stack_42, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_44 = contract_last_first(trp_37, trp_43, np.float64)
            # Addition
            res_45 = binary_add_generic(dot_28, dot_44, np.float64)
            # Product: const * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_46 = mul_scalar(const_val_14, res_45, np.float64)
            # Addition
            res_47 = binary_add_generic(res_13, res_46, np.float64)
            const_np_arr_48 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_50  = np.ascontiguousarray(g_mx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_49 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_50)
            phys_grad_basis_52  = np.ascontiguousarray(g_my[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_51 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_52)
            grad_val_stack_53 = np.stack((grad_val_49, grad_val_51))
            # Addition
            res_54 = binary_add_generic(const_np_arr_48, grad_val_stack_53, np.float64)
            a00 = res_54[0, 0]
            a01 = res_54[0, 1]
            a10 = res_54[1, 0]
            a11 = res_54[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_55 = np.empty((2, 2), dtype=np.float64)
            inv2_55[0, 0] =  a11 * inv_det
            inv2_55[0, 1] = -a01 * inv_det
            inv2_55[1, 0] = -a10 * inv_det
            inv2_55[1, 1] =  a00 * inv_det
            trp_56 = transpose_matrix(inv2_55, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_57 = contract_last_first(res_47, trp_56, np.float64)
            # Product: value * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_58 = mul_scalar(det2_8, dot_57, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_59 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_60 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_61 = np.stack((grad_loc_59, grad_loc_60))
            # RHS: Inner(Function, Test)
            # RHS: Inner(Value rank-2, Test rank-2)
            inner_62 = inner_rank2_value_rank2_basis(res_58, grad_stack_61, np.float64)
            Fe += inner_62 * w_q

        K_values[e] = Ke
        F_values[e] = Fe
        J_values[e] = J

    return K_values, F_values, J_values


def get_kernel(analytic_map):
    pass
    return kernel
