# This file is auto-generated by pycutfem JIT – DO NOT EDIT
import numpy as np
import numba

CODEGEN_ABI = "2026-04-07-abi-dot-product-ghost-layout-v14"

import numba
import numpy as np
from pycutfem.jit.numba_helpers import (
    dot_grad_grad_mixed,
    contract_last_first,
    dot_mixed_const,
    dot_const_mixed,
    dot_vector_trial_grad_test,
    dot_mass_test_trial,
    dot_mass_trial_test,
    dot_grad_func_trial_vec,
    dot_trial_vec_grad_func,
    dot_vec_vec,
    dot_grad_grad_value,
    mul_scalar,
    dot_grad_basis_vector,
    vector_dot_grad_basis,
    vector_dot_grad_value,
    dot_grad_basis_with_grad_value,
    dot_grad_value_with_grad_basis,
    basis_dot_const_vector,
        const_vector_dot_basis,
        const_vector_dot_basis_1d,
        scalar_basis_times_vector,
        scalar_basis_times_vector_as_grad_tensor,
        matrix_times_scalar_basis,
        scalar_vector_outer_product,
        vector_trial_times_scalar_test,
        vector_test_times_scalar_trial,
        vector_vector_outer_product,
    dot_vec_grad_components,
    scalar_trial_times_grad_test,
    scalar_trial_times_basis_test,
    grad_trial_times_scalar_test,
    basis_trial_times_scalar_test,
    scale_mixed_basis_with_coeffs,
    trace_times_identity,
    identity_times_trace_matrix,
    columnwise_dot,
    hessian_dot_vector,
    vector_dot_hessian_basis,
    vector_dot_hessian_value,
    inner_rank2_value_rank2_basis,
    inner_rank2_basis_rank2_value,
    inner_grad_grad,
    inner_hessian_hessian,
    inner_grad_function_grad_test,
    inner_hessian_function_hessian_test,
    inner_mixed_grad_const,
    inner_grad_const_mixed,
    inner_grad_basis_grad_const,
    trace_matrix_value,
    trace_basis_tensor,
    trace_mixed_tensor,
    transpose_grad_tensor,
    transpose_mixed_grad_tensor,
    transpose_hessian_tensor,
    transpose_matrix,
    swap_mixed_basis_tensor,
    dot_value_with_grad,
    dot_grad_with_value,
    pushforward_d3,
    pushforward_d4,
    compute_physical_hessian,
    compute_physical_laplacian,
    load_variable_qp,
    gradient_qp,
    laplacian_qp,
    hessian_qp,
    ghost_grad_jump_penalty_scalar,
    ghost_grad_jump_penalty_vector,
    binary_add_generic,
    binary_add_3_4,
    binary_add_4_3,
    binary_sub_generic,
    binary_sub_3_4,
    binary_sub_4_3,
    scatter_tensor_to_union,
    pad_basis_to_union,
    pushforward_grad_to_union,
    contract_first_first
)
PARAM_ORDER = ['gdofs_map', 'node_coords', 'qp_phys', 'qw', 'detJ', 'J_inv', 'normals', 'b_mx', 'b_my', 'b_ux', 'b_uy', 'example2_local_bossak_alpha', 'example2_local_bossak_ma0', 'example2_local_bossak_ma2', 'example2_local_conv_eps', 'example2_local_dt', 'example2_local_dvms_predicted_subscale_velocity', 'example2_local_dynamic_tau', 'example2_local_half', 'example2_local_inv_dt', 'example2_local_mu_f', 'example2_local_one', 'example2_local_rho_f', 'example2_local_tau_c1', 'example2_local_tau_c2', 'g_mx', 'g_my', 'g_p', 'g_ux', 'g_uy', 'h_arr', 'jit_const_0', 'owner_id', 'u_a_prev_loc', 'u_d_mesh_loc', 'u_d_prev_loc', 'u_u_k_loc', 'u_u_prev_loc']
@numba.njit(parallel=True, fastmath=True, cache=True)
def kernel(
        gdofs_map, node_coords, qp_phys, qw, detJ, J_inv, normals, b_mx, b_my, b_ux, b_uy, example2_local_bossak_alpha, example2_local_bossak_ma0, example2_local_bossak_ma2, example2_local_conv_eps, example2_local_dt, example2_local_dvms_predicted_subscale_velocity, example2_local_dynamic_tau, example2_local_half, example2_local_inv_dt, example2_local_mu_f, example2_local_one, example2_local_rho_f, example2_local_tau_c1, example2_local_tau_c2, g_mx, g_my, g_p, g_ux, g_uy, h_arr, jit_const_0, owner_id, u_a_prev_loc, u_d_mesh_loc, u_d_prev_loc, u_u_k_loc, u_u_prev_loc
    ):
    num_elements        = qp_phys.shape[0]
    # n_dofs_per_element  = 15
    n_dofs_per_element  = gdofs_map.shape[1]            # 9 for volume, 15 on ghost edge
    # print(f"num_elements: {num_elements},n_dofs_per_element: {n_dofs_per_element}")
    # print(f"number of quadrature points: {qw.shape[1]}")

    K_values = np.zeros((num_elements, n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
    F_values = np.zeros((num_elements, n_dofs_per_element), dtype=np.float64)
    # Shape of the integrand that lands in “J”.
    # -------- functional accumulator ------------------------------------
    k = 0
    J_init = 0.0
    J     = J_init
    J_values = np.zeros((num_elements), dtype=np.float64)

    for e in numba.prange(num_elements):
        Ke = np.zeros((n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
        Fe = np.zeros(n_dofs_per_element, dtype=np.float64)
        J  = J_init.copy() if False else J_init

        n_union = gdofs_map.shape[1]

        u_a_prev_loc_e = u_a_prev_loc[e]
        u_d_mesh_loc_e = u_d_mesh_loc[e]
        u_d_prev_loc_e = u_d_prev_loc[e]
        u_u_k_loc_e = u_u_k_loc[e]
        u_u_prev_loc_e = u_u_prev_loc[e]

        for q in range(qw.shape[1]):
            x_q, w_q, J_inv_q = qp_phys[e, q], qw[e, q], J_inv[e, q]
            normal_q = normals[e, q] if normals is not None else np.zeros(2, dtype=np.float64)
            phi_q    = 0.0
            J_inv_q = J_inv[e,q]
            b_mx_q = b_mx[e,q]
            b_my_q = b_my[e,q]
            b_ux_q = b_ux[e,q]
            b_uy_q = b_uy[e,q]
            g_mx_q = g_mx[e,q]
            g_my_q = g_my[e,q]
            g_p_q = g_p[e,q]
            g_ux_q = g_ux[e,q]
            g_uy_q = g_uy[e,q]
            const_np_arr_1 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_3  = np.ascontiguousarray(g_mx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_2 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_3)
            phys_grad_basis_5  = np.ascontiguousarray(g_my[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_4 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_5)
            grad_val_stack_6 = np.stack((grad_val_2, grad_val_4))
            # Addition
            res_7 = binary_add_generic(const_np_arr_1, grad_val_stack_6, np.float64)
            a00 = res_7[0, 0]
            a01 = res_7[0, 1]
            a10 = res_7[1, 0]
            a11 = res_7[1, 1]
            det2_8 = a00 * a11 - a01 * a10
            const_val_9 = example2_local_dynamic_tau.item()
            const_val_10 = example2_local_tau_c1.item()
            const_val_11 = example2_local_mu_f.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_12 = const_val_10 * const_val_11
            h_13 = h_arr[owner_id[e]]
            h_14 = h_arr[owner_id[e]]
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_15 = h_13 * h_14
            # Division
            res_16 = res_12 / float(res_15)
            const_val_17 = example2_local_rho_f.item()
            const_val_18 = example2_local_inv_dt.item()
            const_val_19 = example2_local_tau_c2.item()
            u_k_val_20 = np.zeros((2,), dtype=np.float64)
            val_comp_21 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_20[0] = val_comp_21
            val_comp_22 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_20[1] = val_comp_22
            d_mesh_val_23 = np.zeros((2,), dtype=np.float64)
            val_comp_24 = load_variable_qp(u_d_mesh_loc_e, b_mx[e, q])
            d_mesh_val_23[0] = val_comp_24
            val_comp_25 = load_variable_qp(u_d_mesh_loc_e, b_my[e, q])
            d_mesh_val_23[1] = val_comp_25
            d_prev_val_26 = np.zeros((2,), dtype=np.float64)
            val_comp_27 = load_variable_qp(u_d_prev_loc_e, b_mx[e, q])
            d_prev_val_26[0] = val_comp_27
            val_comp_28 = load_variable_qp(u_d_prev_loc_e, b_my[e, q])
            d_prev_val_26[1] = val_comp_28
            # Subtraction
            res_29 = binary_sub_generic(d_mesh_val_23, d_prev_val_26, np.float64)
            const_val_30 = example2_local_dt.item()
            # Division
            res_31 = res_29 / float(const_val_30)
            # Subtraction
            res_32 = binary_sub_generic(u_k_val_20, res_31, np.float64)
            ewc_33 = example2_local_dvms_predicted_subscale_velocity[owner_id[e]]
            # Addition
            res_34 = binary_add_generic(res_32, ewc_33, np.float64)
            u_k_val_35 = np.zeros((2,), dtype=np.float64)
            val_comp_36 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_35[0] = val_comp_36
            val_comp_37 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_35[1] = val_comp_37
            d_mesh_val_38 = np.zeros((2,), dtype=np.float64)
            val_comp_39 = load_variable_qp(u_d_mesh_loc_e, b_mx[e, q])
            d_mesh_val_38[0] = val_comp_39
            val_comp_40 = load_variable_qp(u_d_mesh_loc_e, b_my[e, q])
            d_mesh_val_38[1] = val_comp_40
            d_prev_val_41 = np.zeros((2,), dtype=np.float64)
            val_comp_42 = load_variable_qp(u_d_prev_loc_e, b_mx[e, q])
            d_prev_val_41[0] = val_comp_42
            val_comp_43 = load_variable_qp(u_d_prev_loc_e, b_my[e, q])
            d_prev_val_41[1] = val_comp_43
            # Subtraction
            res_44 = binary_sub_generic(d_mesh_val_38, d_prev_val_41, np.float64)
            const_val_45 = example2_local_dt.item()
            # Division
            res_46 = res_44 / float(const_val_45)
            # Subtraction
            res_47 = binary_sub_generic(u_k_val_35, res_46, np.float64)
            ewc_48 = example2_local_dvms_predicted_subscale_velocity[owner_id[e]]
            # Addition
            res_49 = binary_add_generic(res_47, ewc_48, np.float64)
            # Non-linear term: dot(Function, Function)
            dot_50 = dot_vec_vec(res_34, res_49, np.float64)
            const_val_51 = example2_local_conv_eps.item()
            # Addition
            res_52 = binary_add_generic(dot_50, const_val_51, np.float64)
            const_val_53 = example2_local_half.item()
            # Power
            res_54 = res_52 ** float(const_val_53)
            # Product: const * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_55 = const_val_19 * res_54
            h_56 = h_arr[owner_id[e]]
            # Division
            res_57 = res_55 / float(h_56)
            # Addition
            res_58 = binary_add_generic(const_val_18, res_57, np.float64)
            # Product: const * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_59 = const_val_17 * res_58
            # Addition
            res_60 = binary_add_generic(res_16, res_59, np.float64)
            # Division
            res_61 = const_val_9 / float(res_60)
            # Product: value * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_62 = det2_8 * res_61
            const_val_63 = example2_local_rho_f.item()
            J_inv_q = J_inv[e, q]
            grad_loc_64 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_65 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_66 = np.stack((grad_loc_64, grad_loc_65))
            const_np_arr_67 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_69  = np.ascontiguousarray(g_mx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_68 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_69)
            phys_grad_basis_71  = np.ascontiguousarray(g_my[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_70 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_71)
            grad_val_stack_72 = np.stack((grad_val_68, grad_val_70))
            # Addition
            res_73 = binary_add_generic(const_np_arr_67, grad_val_stack_72, np.float64)
            a00 = res_73[0, 0]
            a01 = res_73[0, 1]
            a10 = res_73[1, 0]
            a11 = res_73[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_74 = np.empty((2, 2), dtype=np.float64)
            inv2_74[0, 0] =  a11 * inv_det
            inv2_74[0, 1] = -a01 * inv_det
            inv2_74[1, 0] = -a10 * inv_det
            inv2_74[1, 1] =  a00 * inv_det
            # dot(grad(test), grad(value)) -> (k,n,k) tensor basis
            dot_75 = dot_grad_basis_with_grad_value(grad_stack_66, inv2_74, np.float64)
            u_k_val_76 = np.zeros((2,), dtype=np.float64)
            val_comp_77 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_76[0] = val_comp_77
            val_comp_78 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_76[1] = val_comp_78
            d_mesh_val_79 = np.zeros((2,), dtype=np.float64)
            val_comp_80 = load_variable_qp(u_d_mesh_loc_e, b_mx[e, q])
            d_mesh_val_79[0] = val_comp_80
            val_comp_81 = load_variable_qp(u_d_mesh_loc_e, b_my[e, q])
            d_mesh_val_79[1] = val_comp_81
            d_prev_val_82 = np.zeros((2,), dtype=np.float64)
            val_comp_83 = load_variable_qp(u_d_prev_loc_e, b_mx[e, q])
            d_prev_val_82[0] = val_comp_83
            val_comp_84 = load_variable_qp(u_d_prev_loc_e, b_my[e, q])
            d_prev_val_82[1] = val_comp_84
            # Subtraction
            res_85 = binary_sub_generic(d_mesh_val_79, d_prev_val_82, np.float64)
            const_val_86 = example2_local_dt.item()
            # Division
            res_87 = res_85 / float(const_val_86)
            # Subtraction
            res_88 = binary_sub_generic(u_k_val_76, res_87, np.float64)
            ewc_89 = example2_local_dvms_predicted_subscale_velocity[owner_id[e]]
            # Addition
            res_90 = binary_add_generic(res_88, ewc_89, np.float64)
            # Dot plan: basis-gradient · value-vector
            dot_91 = dot_grad_basis_vector(dot_75, res_90, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_92 = mul_scalar(const_val_63, dot_91, np.float64)
            const_val_93 = example2_local_inv_dt.item()
            basis_stack_94 = np.stack((b_ux[e, q], b_uy[e, q]))
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_95 = mul_scalar(const_val_93, basis_stack_94, np.float64)
            # Subtraction
            res_96 = binary_sub_generic(res_92, res_95, np.float64)
            const_np_arr_97 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_99  = np.ascontiguousarray(g_mx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_98 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_99)
            phys_grad_basis_101  = np.ascontiguousarray(g_my[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_100 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_101)
            grad_val_stack_102 = np.stack((grad_val_98, grad_val_100))
            # Addition
            res_103 = binary_add_generic(const_np_arr_97, grad_val_stack_102, np.float64)
            a00 = res_103[0, 0]
            a01 = res_103[0, 1]
            a10 = res_103[1, 0]
            a11 = res_103[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_104 = np.empty((2, 2), dtype=np.float64)
            inv2_104[0, 0] =  a11 * inv_det
            inv2_104[0, 1] = -a01 * inv_det
            inv2_104[1, 0] = -a10 * inv_det
            inv2_104[1, 1] =  a00 * inv_det
            trp_105 = transpose_matrix(inv2_104, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_106 = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_scalar_107 = np.ascontiguousarray(grad_loc_106.T.copy())
            # Dot: matrix-like value gradient · scalar Grad(basis) -> vector basis
            dot_108 = contract_last_first(trp_105, grad_scalar_107, np.float64)
            # Addition
            res_109 = binary_add_generic(res_96, dot_108, np.float64)
            const_val_110 = example2_local_rho_f.item()
            const_val_111 = example2_local_one.item()
            const_val_112 = example2_local_bossak_alpha.item()
            # Subtraction
            res_113 = binary_sub_generic(const_val_111, const_val_112, np.float64)
            const_val_114 = example2_local_bossak_ma0.item()
            u_k_val_115 = np.zeros((2,), dtype=np.float64)
            val_comp_116 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_115[0] = val_comp_116
            val_comp_117 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_115[1] = val_comp_117
            u_prev_val_118 = np.zeros((2,), dtype=np.float64)
            val_comp_119 = load_variable_qp(u_u_prev_loc_e, b_ux[e, q])
            u_prev_val_118[0] = val_comp_119
            val_comp_120 = load_variable_qp(u_u_prev_loc_e, b_uy[e, q])
            u_prev_val_118[1] = val_comp_120
            # Subtraction
            res_121 = binary_sub_generic(u_k_val_115, u_prev_val_118, np.float64)
            # Product: const * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_122 = mul_scalar(const_val_114, res_121, np.float64)
            const_val_123 = example2_local_bossak_ma2.item()
            a_prev_val_124 = np.zeros((2,), dtype=np.float64)
            val_comp_125 = load_variable_qp(u_a_prev_loc_e, b_ux[e, q])
            a_prev_val_124[0] = val_comp_125
            val_comp_126 = load_variable_qp(u_a_prev_loc_e, b_uy[e, q])
            a_prev_val_124[1] = val_comp_126
            # Product: const * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_127 = mul_scalar(const_val_123, a_prev_val_124, np.float64)
            # Addition
            res_128 = binary_add_generic(res_122, res_127, np.float64)
            # Product: const * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_129 = mul_scalar(res_113, res_128, np.float64)
            const_val_130 = example2_local_bossak_alpha.item()
            a_prev_val_131 = np.zeros((2,), dtype=np.float64)
            val_comp_132 = load_variable_qp(u_a_prev_loc_e, b_ux[e, q])
            a_prev_val_131[0] = val_comp_132
            val_comp_133 = load_variable_qp(u_a_prev_loc_e, b_uy[e, q])
            a_prev_val_131[1] = val_comp_133
            # Product: const * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_134 = mul_scalar(const_val_130, a_prev_val_131, np.float64)
            # Addition
            res_135 = binary_add_generic(res_129, res_134, np.float64)
            # Product: const * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_136 = mul_scalar(const_val_110, res_135, np.float64)
            # Dot plan: semantic basis rank-1 · value vector
            dot_137 = basis_dot_const_vector(res_109, res_136, np.float64)
            # Product: value * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_138 = mul_scalar(res_62, dot_137[0], np.float64)
            Fe += res_138 * w_q

        K_values[e] = Ke
        F_values[e] = Fe
        J_values[e] = J

    return K_values, F_values, J_values


def get_kernel(analytic_map):
    pass
    return kernel
