# This file is auto-generated by pycutfem JIT – DO NOT EDIT
import numpy as np
import numba

CODEGEN_ABI = "2026-04-07-abi-dot-product-ghost-layout-v14"

import numba
import numpy as np
from pycutfem.jit.numba_helpers import (
    dot_grad_grad_mixed,
    contract_last_first,
    dot_mixed_const,
    dot_const_mixed,
    dot_vector_trial_grad_test,
    dot_mass_test_trial,
    dot_mass_trial_test,
    dot_grad_func_trial_vec,
    dot_trial_vec_grad_func,
    dot_vec_vec,
    dot_grad_grad_value,
    mul_scalar,
    dot_grad_basis_vector,
    vector_dot_grad_basis,
    vector_dot_grad_value,
    dot_grad_basis_with_grad_value,
    dot_grad_value_with_grad_basis,
    basis_dot_const_vector,
        const_vector_dot_basis,
        const_vector_dot_basis_1d,
        scalar_basis_times_vector,
        scalar_basis_times_vector_as_grad_tensor,
        matrix_times_scalar_basis,
        scalar_vector_outer_product,
        vector_trial_times_scalar_test,
        vector_test_times_scalar_trial,
        vector_vector_outer_product,
    dot_vec_grad_components,
    scalar_trial_times_grad_test,
    scalar_trial_times_basis_test,
    grad_trial_times_scalar_test,
    basis_trial_times_scalar_test,
    scale_mixed_basis_with_coeffs,
    trace_times_identity,
    identity_times_trace_matrix,
    columnwise_dot,
    hessian_dot_vector,
    vector_dot_hessian_basis,
    vector_dot_hessian_value,
    inner_rank2_value_rank2_basis,
    inner_rank2_basis_rank2_value,
    inner_grad_grad,
    inner_hessian_hessian,
    inner_grad_function_grad_test,
    inner_hessian_function_hessian_test,
    inner_mixed_grad_const,
    inner_grad_const_mixed,
    inner_grad_basis_grad_const,
    trace_matrix_value,
    trace_basis_tensor,
    trace_mixed_tensor,
    transpose_grad_tensor,
    transpose_mixed_grad_tensor,
    transpose_hessian_tensor,
    transpose_matrix,
    swap_mixed_basis_tensor,
    dot_value_with_grad,
    dot_grad_with_value,
    pushforward_d3,
    pushforward_d4,
    compute_physical_hessian,
    compute_physical_laplacian,
    load_variable_qp,
    gradient_qp,
    laplacian_qp,
    hessian_qp,
    ghost_grad_jump_penalty_scalar,
    ghost_grad_jump_penalty_vector,
    binary_add_generic,
    binary_add_3_4,
    binary_add_4_3,
    binary_sub_generic,
    binary_sub_3_4,
    binary_sub_4_3,
    scatter_tensor_to_union,
    pad_basis_to_union,
    pushforward_grad_to_union,
    contract_first_first
)
PARAM_ORDER = ['gdofs_map', 'node_coords', 'qp_phys', 'qw', 'detJ', 'J_inv', 'normals', 'example2_half', 'example2_local_lambda_s', 'example2_local_mu_s', 'example2_one', 'example2_two', 'example2_two_thirds', 'g_dx', 'g_dy', 'jit_const_0', 'jit_const_1', 'u_d_k_loc']
@numba.njit(parallel=True, fastmath=True, cache=True)
def kernel(
        gdofs_map, node_coords, qp_phys, qw, detJ, J_inv, normals, example2_half, example2_local_lambda_s, example2_local_mu_s, example2_one, example2_two, example2_two_thirds, g_dx, g_dy, jit_const_0, jit_const_1, u_d_k_loc
    ):
    num_elements        = qp_phys.shape[0]
    # n_dofs_per_element  = 8
    n_dofs_per_element  = gdofs_map.shape[1]            # 9 for volume, 15 on ghost edge
    # print(f"num_elements: {num_elements},n_dofs_per_element: {n_dofs_per_element}")
    # print(f"number of quadrature points: {qw.shape[1]}")

    K_values = np.zeros((num_elements, n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
    F_values = np.zeros((num_elements, n_dofs_per_element), dtype=np.float64)
    # Shape of the integrand that lands in “J”.
    # -------- functional accumulator ------------------------------------
    k = 0
    J_init = 0.0
    J     = J_init
    J_values = np.zeros((num_elements), dtype=np.float64)

    for e in numba.prange(num_elements):
        Ke = np.zeros((n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
        Fe = np.zeros(n_dofs_per_element, dtype=np.float64)
        J  = J_init.copy() if False else J_init

        n_union = gdofs_map.shape[1]

        u_d_k_loc_e = u_d_k_loc[e]

        for q in range(qw.shape[1]):
            x_q, w_q, J_inv_q = qp_phys[e, q], qw[e, q], J_inv[e, q]
            normal_q = normals[e, q] if normals is not None else np.zeros(2, dtype=np.float64)
            phi_q    = 0.0
            J_inv_q = J_inv[e,q]
            g_dx_q = g_dx[e,q]
            g_dy_q = g_dy[e,q]
            const_np_arr_1 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_3  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_2 = gradient_qp(u_d_k_loc_e, phys_grad_basis_3)
            phys_grad_basis_5  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_4 = gradient_qp(u_d_k_loc_e, phys_grad_basis_5)
            grad_val_stack_6 = np.stack((grad_val_2, grad_val_4))
            # Addition
            res_7 = binary_add_generic(const_np_arr_1, grad_val_stack_6, np.float64)
            const_val_8 = example2_two.item()
            const_val_9 = example2_half.item()
            const_val_10 = example2_local_mu_s.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_11 = const_val_9 * const_val_10
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_12 = const_val_8 * res_11
            const_np_arr_13 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_15  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_14 = gradient_qp(u_d_k_loc_e, phys_grad_basis_15)
            phys_grad_basis_17  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_16 = gradient_qp(u_d_k_loc_e, phys_grad_basis_17)
            grad_val_stack_18 = np.stack((grad_val_14, grad_val_16))
            # Addition
            res_19 = binary_add_generic(const_np_arr_13, grad_val_stack_18, np.float64)
            a00 = res_19[0, 0]
            a01 = res_19[0, 1]
            a10 = res_19[1, 0]
            a11 = res_19[1, 1]
            det2_20 = a00 * a11 - a01 * a10
            # Division
            res_21 = res_12 / float(det2_20)
            const_np_arr_22 = jit_const_1
            const_val_23 = example2_half.item()
            const_np_arr_24 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_26  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_25 = gradient_qp(u_d_k_loc_e, phys_grad_basis_26)
            phys_grad_basis_28  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_27 = gradient_qp(u_d_k_loc_e, phys_grad_basis_28)
            grad_val_stack_29 = np.stack((grad_val_25, grad_val_27))
            # Addition
            res_30 = binary_add_generic(const_np_arr_24, grad_val_stack_29, np.float64)
            trp_31 = transpose_matrix(res_30, np.float64)
            const_np_arr_32 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_34  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_33 = gradient_qp(u_d_k_loc_e, phys_grad_basis_34)
            phys_grad_basis_36  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_35 = gradient_qp(u_d_k_loc_e, phys_grad_basis_36)
            grad_val_stack_37 = np.stack((grad_val_33, grad_val_35))
            # Addition
            res_38 = binary_add_generic(const_np_arr_32, grad_val_stack_37, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_39 = contract_last_first(trp_31, res_38, np.float64)
            # Trace of a computed matrix -> scalar value
            trace_res_40 = trace_matrix_value(dot_39, np.float64)
            # Product: const * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_41 = const_val_23 * trace_res_40
            const_np_arr_42 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_44  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_43 = gradient_qp(u_d_k_loc_e, phys_grad_basis_44)
            phys_grad_basis_46  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_45 = gradient_qp(u_d_k_loc_e, phys_grad_basis_46)
            grad_val_stack_47 = np.stack((grad_val_43, grad_val_45))
            # Addition
            res_48 = binary_add_generic(const_np_arr_42, grad_val_stack_47, np.float64)
            trp_49 = transpose_matrix(res_48, np.float64)
            const_np_arr_50 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_52  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_51 = gradient_qp(u_d_k_loc_e, phys_grad_basis_52)
            phys_grad_basis_54  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_53 = gradient_qp(u_d_k_loc_e, phys_grad_basis_54)
            grad_val_stack_55 = np.stack((grad_val_51, grad_val_53))
            # Addition
            res_56 = binary_add_generic(const_np_arr_50, grad_val_stack_55, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_57 = contract_last_first(trp_49, res_56, np.float64)
            a00 = dot_57[0, 0]
            a01 = dot_57[0, 1]
            a10 = dot_57[1, 0]
            a11 = dot_57[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_58 = np.empty((2, 2), dtype=np.float64)
            inv2_58[0, 0] =  a11 * inv_det
            inv2_58[0, 1] = -a01 * inv_det
            inv2_58[1, 0] = -a10 * inv_det
            inv2_58[1, 1] =  a00 * inv_det
            # Product: value * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_59 = mul_scalar(res_41, inv2_58, np.float64)
            # Subtraction
            res_60 = binary_sub_generic(const_np_arr_22, res_59, np.float64)
            # Product: value * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_61 = mul_scalar(res_21, res_60, np.float64)
            const_np_arr_62 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_64  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_63 = gradient_qp(u_d_k_loc_e, phys_grad_basis_64)
            phys_grad_basis_66  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_65 = gradient_qp(u_d_k_loc_e, phys_grad_basis_66)
            grad_val_stack_67 = np.stack((grad_val_63, grad_val_65))
            # Addition
            res_68 = binary_add_generic(const_np_arr_62, grad_val_stack_67, np.float64)
            a00 = res_68[0, 0]
            a01 = res_68[0, 1]
            a10 = res_68[1, 0]
            a11 = res_68[1, 1]
            det2_69 = a00 * a11 - a01 * a10
            const_val_70 = example2_local_lambda_s.item()
            const_val_71 = example2_two_thirds.item()
            const_val_72 = example2_local_mu_s.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_73 = const_val_71 * const_val_72
            # Addition
            res_74 = binary_add_generic(const_val_70, res_73, np.float64)
            const_np_arr_75 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_77  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_76 = gradient_qp(u_d_k_loc_e, phys_grad_basis_77)
            phys_grad_basis_79  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_78 = gradient_qp(u_d_k_loc_e, phys_grad_basis_79)
            grad_val_stack_80 = np.stack((grad_val_76, grad_val_78))
            # Addition
            res_81 = binary_add_generic(const_np_arr_75, grad_val_stack_80, np.float64)
            a00 = res_81[0, 0]
            a01 = res_81[0, 1]
            a10 = res_81[1, 0]
            a11 = res_81[1, 1]
            det2_82 = a00 * a11 - a01 * a10
            const_val_83 = example2_one.item()
            # Subtraction
            res_84 = binary_sub_generic(det2_82, const_val_83, np.float64)
            # Product: const * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_85 = res_74 * res_84
            # Product: value * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_86 = det2_69 * res_85
            const_np_arr_87 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_89  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_88 = gradient_qp(u_d_k_loc_e, phys_grad_basis_89)
            phys_grad_basis_91  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_90 = gradient_qp(u_d_k_loc_e, phys_grad_basis_91)
            grad_val_stack_92 = np.stack((grad_val_88, grad_val_90))
            # Addition
            res_93 = binary_add_generic(const_np_arr_87, grad_val_stack_92, np.float64)
            trp_94 = transpose_matrix(res_93, np.float64)
            const_np_arr_95 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_97  = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_96 = gradient_qp(u_d_k_loc_e, phys_grad_basis_97)
            phys_grad_basis_99  = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_98 = gradient_qp(u_d_k_loc_e, phys_grad_basis_99)
            grad_val_stack_100 = np.stack((grad_val_96, grad_val_98))
            # Addition
            res_101 = binary_add_generic(const_np_arr_95, grad_val_stack_100, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_102 = contract_last_first(trp_94, res_101, np.float64)
            a00 = dot_102[0, 0]
            a01 = dot_102[0, 1]
            a10 = dot_102[1, 0]
            a11 = dot_102[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_103 = np.empty((2, 2), dtype=np.float64)
            inv2_103[0, 0] =  a11 * inv_det
            inv2_103[0, 1] = -a01 * inv_det
            inv2_103[1, 0] = -a10 * inv_det
            inv2_103[1, 1] =  a00 * inv_det
            # Product: value * value
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_104 = mul_scalar(res_86, inv2_103, np.float64)
            # Addition
            res_105 = binary_add_generic(res_61, res_104, np.float64)
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_106 = contract_last_first(res_7, res_105, np.float64)
            J_inv_q = J_inv[e, q]
            grad_loc_107 = np.ascontiguousarray(g_dx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_108 = np.ascontiguousarray(g_dy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_109 = np.stack((grad_loc_107, grad_loc_108))
            # RHS: Inner(Function, Test)
            # RHS: Inner(Value rank-2, Test rank-2)
            inner_110 = inner_rank2_value_rank2_basis(dot_106, grad_stack_109, np.float64)
            Fe += inner_110 * w_q

        K_values[e] = Ke
        F_values[e] = Fe
        J_values[e] = J

    return K_values, F_values, J_values


def get_kernel(analytic_map):
    pass
    return kernel
