# This file is auto-generated by pycutfem JIT – DO NOT EDIT
import numpy as np
import numba

CODEGEN_ABI = "2026-04-07-abi-dot-product-ghost-layout-v14"

import numba
import numpy as np
from pycutfem.jit.numba_helpers import (
    dot_grad_grad_mixed,
    contract_last_first,
    dot_mixed_const,
    dot_const_mixed,
    dot_vector_trial_grad_test,
    dot_mass_test_trial,
    dot_mass_trial_test,
    dot_grad_func_trial_vec,
    dot_trial_vec_grad_func,
    dot_vec_vec,
    dot_grad_grad_value,
    mul_scalar,
    dot_grad_basis_vector,
    vector_dot_grad_basis,
    vector_dot_grad_value,
    dot_grad_basis_with_grad_value,
    dot_grad_value_with_grad_basis,
    basis_dot_const_vector,
        const_vector_dot_basis,
        const_vector_dot_basis_1d,
        scalar_basis_times_vector,
        scalar_basis_times_vector_as_grad_tensor,
        matrix_times_scalar_basis,
        scalar_vector_outer_product,
        vector_trial_times_scalar_test,
        vector_test_times_scalar_trial,
        vector_vector_outer_product,
    dot_vec_grad_components,
    scalar_trial_times_grad_test,
    scalar_trial_times_basis_test,
    grad_trial_times_scalar_test,
    basis_trial_times_scalar_test,
    scale_mixed_basis_with_coeffs,
    trace_times_identity,
    identity_times_trace_matrix,
    columnwise_dot,
    hessian_dot_vector,
    vector_dot_hessian_basis,
    vector_dot_hessian_value,
    inner_rank2_value_rank2_basis,
    inner_rank2_basis_rank2_value,
    inner_grad_grad,
    inner_hessian_hessian,
    inner_grad_function_grad_test,
    inner_hessian_function_hessian_test,
    inner_mixed_grad_const,
    inner_grad_const_mixed,
    inner_grad_basis_grad_const,
    trace_matrix_value,
    trace_basis_tensor,
    trace_mixed_tensor,
    transpose_grad_tensor,
    transpose_mixed_grad_tensor,
    transpose_hessian_tensor,
    transpose_matrix,
    swap_mixed_basis_tensor,
    dot_value_with_grad,
    dot_grad_with_value,
    pushforward_d3,
    pushforward_d4,
    compute_physical_hessian,
    compute_physical_laplacian,
    load_variable_qp,
    gradient_qp,
    laplacian_qp,
    hessian_qp,
    ghost_grad_jump_penalty_scalar,
    ghost_grad_jump_penalty_vector,
    binary_add_generic,
    binary_add_3_4,
    binary_add_4_3,
    binary_sub_generic,
    binary_sub_3_4,
    binary_sub_4_3,
    scatter_tensor_to_union,
    pad_basis_to_union,
    pushforward_grad_to_union,
    contract_first_first
)
PARAM_ORDER = ['gdofs_map', 'node_coords', 'qp_phys', 'qw', 'detJ', 'J_inv', 'normals', 'b_mx', 'b_my', 'b_ux', 'b_uy', 'g_mx', 'g_my', 'g_ux', 'g_uy', 'h_arr', 'jit_const_0', 'jit_const_1', 'jit_const_2', 'jit_const_3', 'jit_const_4', 'jit_const_5', 'jit_const_6', 'jit_const_7', 'jit_const_8', 'owner_id', 'u_d_mesh_loc', 'u_d_prev_loc', 'u_u_k_loc']
@numba.njit(parallel=True, fastmath=True, cache=True)
def kernel(
        gdofs_map, node_coords, qp_phys, qw, detJ, J_inv, normals, b_mx, b_my, b_ux, b_uy, g_mx, g_my, g_ux, g_uy, h_arr, jit_const_0, jit_const_1, jit_const_2, jit_const_3, jit_const_4, jit_const_5, jit_const_6, jit_const_7, jit_const_8, owner_id, u_d_mesh_loc, u_d_prev_loc, u_u_k_loc
    ):
    num_elements        = qp_phys.shape[0]
    # n_dofs_per_element  = 36
    n_dofs_per_element  = gdofs_map.shape[1]            # 9 for volume, 15 on ghost edge
    # print(f"num_elements: {num_elements},n_dofs_per_element: {n_dofs_per_element}")
    # print(f"number of quadrature points: {qw.shape[1]}")

    K_values = np.zeros((num_elements, n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
    F_values = np.zeros((num_elements, n_dofs_per_element), dtype=np.float64)
    # Shape of the integrand that lands in “J”.
    # -------- functional accumulator ------------------------------------
    k = 0
    J_init = 0.0
    J     = J_init
    J_values = np.zeros((num_elements), dtype=np.float64)

    for e in numba.prange(num_elements):
        Ke = np.zeros((n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
        Fe = np.zeros(n_dofs_per_element, dtype=np.float64)
        J  = J_init.copy() if False else J_init

        n_union = gdofs_map.shape[1]

        u_d_mesh_loc_e = u_d_mesh_loc[e]
        u_d_prev_loc_e = u_d_prev_loc[e]
        u_u_k_loc_e = u_u_k_loc[e]

        for q in range(qw.shape[1]):
            x_q, w_q, J_inv_q = qp_phys[e, q], qw[e, q], J_inv[e, q]
            normal_q = normals[e, q] if normals is not None else np.zeros(2, dtype=np.float64)
            phi_q    = 0.0
            J_inv_q = J_inv[e,q]
            b_mx_q = b_mx[e,q]
            b_my_q = b_my[e,q]
            b_ux_q = b_ux[e,q]
            b_uy_q = b_uy[e,q]
            g_mx_q = g_mx[e,q]
            g_my_q = g_my[e,q]
            g_ux_q = g_ux[e,q]
            g_uy_q = g_uy[e,q]
            const_np_arr_1 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_3  = np.ascontiguousarray(g_mx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_2 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_3)
            phys_grad_basis_5  = np.ascontiguousarray(g_my[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_4 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_5)
            grad_val_stack_6 = np.stack((grad_val_2, grad_val_4))
            # Addition
            res_7 = binary_add_generic(const_np_arr_1, grad_val_stack_6, np.float64)
            a00 = res_7[0, 0]
            a01 = res_7[0, 1]
            a10 = res_7[1, 0]
            a11 = res_7[1, 1]
            det2_8 = a00 * a11 - a01 * a10
            const_val_9 = jit_const_1.item()
            const_val_10 = jit_const_2.item()
            const_val_11 = jit_const_3.item()
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_12 = const_val_10 * const_val_11
            h_13 = h_arr[owner_id[e]]
            h_14 = h_arr[owner_id[e]]
            # Product: const * const
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_15 = h_13 * h_14
            # Division
            res_16 = res_12 / float(res_15)
            const_val_17 = jit_const_4.item()
            const_val_18 = jit_const_5.item()
            u_k_val_19 = np.zeros((2,), dtype=np.float64)
            val_comp_20 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_19[0] = val_comp_20
            val_comp_21 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_19[1] = val_comp_21
            d_mesh_val_22 = np.zeros((2,), dtype=np.float64)
            val_comp_23 = load_variable_qp(u_d_mesh_loc_e, b_mx[e, q])
            d_mesh_val_22[0] = val_comp_23
            val_comp_24 = load_variable_qp(u_d_mesh_loc_e, b_my[e, q])
            d_mesh_val_22[1] = val_comp_24
            d_prev_val_25 = np.zeros((2,), dtype=np.float64)
            val_comp_26 = load_variable_qp(u_d_prev_loc_e, b_mx[e, q])
            d_prev_val_25[0] = val_comp_26
            val_comp_27 = load_variable_qp(u_d_prev_loc_e, b_my[e, q])
            d_prev_val_25[1] = val_comp_27
            # Subtraction
            res_28 = binary_sub_generic(d_mesh_val_22, d_prev_val_25, np.float64)
            const_val_29 = jit_const_6.item()
            # Division
            res_30 = res_28 / float(const_val_29)
            # Subtraction
            res_31 = binary_sub_generic(u_k_val_19, res_30, np.float64)
            u_k_val_32 = np.zeros((2,), dtype=np.float64)
            val_comp_33 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_32[0] = val_comp_33
            val_comp_34 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_32[1] = val_comp_34
            d_mesh_val_35 = np.zeros((2,), dtype=np.float64)
            val_comp_36 = load_variable_qp(u_d_mesh_loc_e, b_mx[e, q])
            d_mesh_val_35[0] = val_comp_36
            val_comp_37 = load_variable_qp(u_d_mesh_loc_e, b_my[e, q])
            d_mesh_val_35[1] = val_comp_37
            d_prev_val_38 = np.zeros((2,), dtype=np.float64)
            val_comp_39 = load_variable_qp(u_d_prev_loc_e, b_mx[e, q])
            d_prev_val_38[0] = val_comp_39
            val_comp_40 = load_variable_qp(u_d_prev_loc_e, b_my[e, q])
            d_prev_val_38[1] = val_comp_40
            # Subtraction
            res_41 = binary_sub_generic(d_mesh_val_35, d_prev_val_38, np.float64)
            const_val_42 = jit_const_6.item()
            # Division
            res_43 = res_41 / float(const_val_42)
            # Subtraction
            res_44 = binary_sub_generic(u_k_val_32, res_43, np.float64)
            # Non-linear term: dot(Function, Function)
            dot_45 = dot_vec_vec(res_31, res_44, np.float64)
            const_val_46 = jit_const_7.item()
            # Addition
            res_47 = binary_add_generic(dot_45, const_val_46, np.float64)
            const_val_48 = jit_const_8.item()
            # Power
            res_49 = res_47 ** float(const_val_48)
            # Product: const * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_50 = const_val_18 * res_49
            h_51 = h_arr[owner_id[e]]
            # Division
            res_52 = res_50 / float(h_51)
            # Addition
            res_53 = binary_add_generic(const_val_17, res_52, np.float64)
            # Addition
            res_54 = binary_add_generic(res_16, res_53, np.float64)
            # Division
            res_55 = const_val_9 / float(res_54)
            # Product: value * value
            # Product: scalar * scalar/np.ndarry → scalar/np.ndarray
            res_56 = det2_8 * res_55
            J_inv_q = J_inv[e, q]
            grad_loc_57 = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_loc_58 = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_stack_59 = np.stack((grad_loc_57, grad_loc_58))
            const_np_arr_60 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_62  = np.ascontiguousarray(g_mx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_61 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_62)
            phys_grad_basis_64  = np.ascontiguousarray(g_my[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_63 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_64)
            grad_val_stack_65 = np.stack((grad_val_61, grad_val_63))
            # Addition
            res_66 = binary_add_generic(const_np_arr_60, grad_val_stack_65, np.float64)
            a00 = res_66[0, 0]
            a01 = res_66[0, 1]
            a10 = res_66[1, 0]
            a11 = res_66[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_67 = np.empty((2, 2), dtype=np.float64)
            inv2_67[0, 0] =  a11 * inv_det
            inv2_67[0, 1] = -a01 * inv_det
            inv2_67[1, 0] = -a10 * inv_det
            inv2_67[1, 1] =  a00 * inv_det
            # dot(grad(test), grad(value)) -> (k,n,k) tensor basis
            dot_68 = dot_grad_basis_with_grad_value(grad_stack_59, inv2_67, np.float64)
            u_k_val_69 = np.zeros((2,), dtype=np.float64)
            val_comp_70 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_69[0] = val_comp_70
            val_comp_71 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_69[1] = val_comp_71
            d_mesh_val_72 = np.zeros((2,), dtype=np.float64)
            val_comp_73 = load_variable_qp(u_d_mesh_loc_e, b_mx[e, q])
            d_mesh_val_72[0] = val_comp_73
            val_comp_74 = load_variable_qp(u_d_mesh_loc_e, b_my[e, q])
            d_mesh_val_72[1] = val_comp_74
            d_prev_val_75 = np.zeros((2,), dtype=np.float64)
            val_comp_76 = load_variable_qp(u_d_prev_loc_e, b_mx[e, q])
            d_prev_val_75[0] = val_comp_76
            val_comp_77 = load_variable_qp(u_d_prev_loc_e, b_my[e, q])
            d_prev_val_75[1] = val_comp_77
            # Subtraction
            res_78 = binary_sub_generic(d_mesh_val_72, d_prev_val_75, np.float64)
            const_val_79 = jit_const_6.item()
            # Division
            res_80 = res_78 / float(const_val_79)
            # Subtraction
            res_81 = binary_sub_generic(u_k_val_69, res_80, np.float64)
            # Dot plan: basis-gradient · value-vector
            dot_82 = dot_grad_basis_vector(dot_68, res_81, np.float64)
            J_inv_q = J_inv[e, q]
            phys_grad_basis_84  = np.ascontiguousarray(g_ux[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_83 = gradient_qp(u_u_k_loc_e, phys_grad_basis_84)
            phys_grad_basis_86  = np.ascontiguousarray(g_uy[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_85 = gradient_qp(u_u_k_loc_e, phys_grad_basis_86)
            grad_val_stack_87 = np.stack((grad_val_83, grad_val_85))
            const_np_arr_88 = jit_const_0
            J_inv_q = J_inv[e, q]
            phys_grad_basis_90  = np.ascontiguousarray(g_mx[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_89 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_90)
            phys_grad_basis_92  = np.ascontiguousarray(g_my[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_val_91 = gradient_qp(u_d_mesh_loc_e, phys_grad_basis_92)
            grad_val_stack_93 = np.stack((grad_val_89, grad_val_91))
            # Addition
            res_94 = binary_add_generic(const_np_arr_88, grad_val_stack_93, np.float64)
            a00 = res_94[0, 0]
            a01 = res_94[0, 1]
            a10 = res_94[1, 0]
            a11 = res_94[1, 1]
            det = a00 * a11 - a01 * a10
            inv_det = 1.0 / (det + 1e-300)
            inv2_95 = np.empty((2, 2), dtype=np.float64)
            inv2_95[0, 0] =  a11 * inv_det
            inv2_95[0, 1] = -a01 * inv_det
            inv2_95[1, 0] = -a10 * inv_det
            inv2_95[1, 1] =  a00 * inv_det
            # Dot plan: value-gradient · value-gradient via semantic last-first contraction
            dot_96 = contract_last_first(grad_val_stack_87, inv2_95, np.float64)
            u_k_val_97 = np.zeros((2,), dtype=np.float64)
            val_comp_98 = load_variable_qp(u_u_k_loc_e, b_ux[e, q])
            u_k_val_97[0] = val_comp_98
            val_comp_99 = load_variable_qp(u_u_k_loc_e, b_uy[e, q])
            u_k_val_97[1] = val_comp_99
            d_mesh_val_100 = np.zeros((2,), dtype=np.float64)
            val_comp_101 = load_variable_qp(u_d_mesh_loc_e, b_mx[e, q])
            d_mesh_val_100[0] = val_comp_101
            val_comp_102 = load_variable_qp(u_d_mesh_loc_e, b_my[e, q])
            d_mesh_val_100[1] = val_comp_102
            d_prev_val_103 = np.zeros((2,), dtype=np.float64)
            val_comp_104 = load_variable_qp(u_d_prev_loc_e, b_mx[e, q])
            d_prev_val_103[0] = val_comp_104
            val_comp_105 = load_variable_qp(u_d_prev_loc_e, b_my[e, q])
            d_prev_val_103[1] = val_comp_105
            # Subtraction
            res_106 = binary_sub_generic(d_mesh_val_100, d_prev_val_103, np.float64)
            const_val_107 = jit_const_6.item()
            # Division
            res_108 = res_106 / float(const_val_107)
            # Subtraction
            res_109 = binary_sub_generic(u_k_val_97, res_108, np.float64)
            # RHS: planner-driven contraction for value gradient · value vector
            dot_110 = contract_last_first(dot_96, res_109, np.float64)
            # Dot plan: semantic basis rank-1 · value vector
            dot_111 = basis_dot_const_vector(dot_82, dot_110, np.float64)
            # Product: value * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_112 = mul_scalar(res_56, dot_111[0], np.float64)
            Fe += res_112 * w_q

        K_values[e] = Ke
        F_values[e] = Fe
        J_values[e] = J

    return K_values, F_values, J_values


def get_kernel(analytic_map):
    pass
    return kernel
