# This file is auto-generated by pycutfem JIT – DO NOT EDIT
import numpy as np
import numba

CODEGEN_ABI = "2026-04-07-abi-dot-product-ghost-layout-v14"

import numba
import numpy as np
from pycutfem.jit.numba_helpers import (
    dot_grad_grad_mixed,
    contract_last_first,
    dot_mixed_const,
    dot_const_mixed,
    dot_vector_trial_grad_test,
    dot_mass_test_trial,
    dot_mass_trial_test,
    dot_grad_func_trial_vec,
    dot_trial_vec_grad_func,
    dot_vec_vec,
    dot_grad_grad_value,
    mul_scalar,
    dot_grad_basis_vector,
    vector_dot_grad_basis,
    vector_dot_grad_value,
    dot_grad_basis_with_grad_value,
    dot_grad_value_with_grad_basis,
    basis_dot_const_vector,
        const_vector_dot_basis,
        const_vector_dot_basis_1d,
        scalar_basis_times_vector,
        scalar_basis_times_vector_as_grad_tensor,
        matrix_times_scalar_basis,
        scalar_vector_outer_product,
        vector_trial_times_scalar_test,
        vector_test_times_scalar_trial,
        vector_vector_outer_product,
    dot_vec_grad_components,
    scalar_trial_times_grad_test,
    scalar_trial_times_basis_test,
    grad_trial_times_scalar_test,
    basis_trial_times_scalar_test,
    scale_mixed_basis_with_coeffs,
    trace_times_identity,
    identity_times_trace_matrix,
    columnwise_dot,
    hessian_dot_vector,
    vector_dot_hessian_basis,
    vector_dot_hessian_value,
    inner_rank2_value_rank2_basis,
    inner_rank2_basis_rank2_value,
    inner_grad_grad,
    inner_hessian_hessian,
    inner_grad_function_grad_test,
    inner_hessian_function_hessian_test,
    inner_mixed_grad_const,
    inner_grad_const_mixed,
    inner_grad_basis_grad_const,
    trace_matrix_value,
    trace_basis_tensor,
    trace_mixed_tensor,
    transpose_grad_tensor,
    transpose_mixed_grad_tensor,
    transpose_hessian_tensor,
    transpose_matrix,
    swap_mixed_basis_tensor,
    dot_value_with_grad,
    dot_grad_with_value,
    pushforward_d3,
    pushforward_d4,
    compute_physical_hessian,
    compute_physical_laplacian,
    load_variable_qp,
    gradient_qp,
    laplacian_qp,
    hessian_qp,
    ghost_grad_jump_penalty_scalar,
    ghost_grad_jump_penalty_vector,
    binary_add_generic,
    binary_add_3_4,
    binary_add_4_3,
    binary_sub_generic,
    binary_sub_3_4,
    binary_sub_4_3,
    scatter_tensor_to_union,
    pad_basis_to_union,
    pushforward_grad_to_union,
    contract_first_first
)
PARAM_ORDER = ['gdofs_map', 'node_coords', 'qp_phys', 'qw', 'detJ', 'J_inv', 'normals', 'g_p', 'jit_const_0', 'jit_const_1', 'jit_const_2', 'jit_const_3', 'jit_const_4', 'jit_const_5', 'jit_const_6', 'jit_const_7']
@numba.njit(parallel=True, fastmath=True, cache=True)
def kernel(
        gdofs_map, node_coords, qp_phys, qw, detJ, J_inv, normals, g_p, jit_const_0, jit_const_1, jit_const_2, jit_const_3, jit_const_4, jit_const_5, jit_const_6, jit_const_7
    ):
    num_elements        = qp_phys.shape[0]
    # n_dofs_per_element  = 9
    n_dofs_per_element  = gdofs_map.shape[1]            # 9 for volume, 15 on ghost edge
    # print(f"num_elements: {num_elements},n_dofs_per_element: {n_dofs_per_element}")
    # print(f"number of quadrature points: {qw.shape[1]}")

    K_values = np.zeros((num_elements, n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
    F_values = np.zeros((num_elements, n_dofs_per_element), dtype=np.float64)
    # Shape of the integrand that lands in “J”.
    # -------- functional accumulator ------------------------------------
    k = 0
    J_init = 0.0
    J     = J_init
    J_values = np.zeros((num_elements), dtype=np.float64)

    for e in numba.prange(num_elements):
        Ke = np.zeros((n_dofs_per_element, n_dofs_per_element), dtype=np.float64)
        Fe = np.zeros(n_dofs_per_element, dtype=np.float64)
        J  = J_init.copy() if False else J_init

        n_union = gdofs_map.shape[1]



        for q in range(qw.shape[1]):
            x_q, w_q, J_inv_q = qp_phys[e, q], qw[e, q], J_inv[e, q]
            normal_q = normals[e, q] if normals is not None else np.zeros(2, dtype=np.float64)
            phi_q    = 0.0
            J_inv_q = J_inv[e,q]
            g_p_q = g_p[e,q]
            const_val_1 = jit_const_0.item()
            J_inv_q = J_inv[e, q]
            grad_loc_e_2 = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_scalar_3 = np.ascontiguousarray(grad_loc_e_2.T.copy())
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_4 = mul_scalar(const_val_1, grad_scalar_3, np.float64)
            const_val_5 = jit_const_1.item()
            const_np_arr_6 = jit_const_2
            J_inv_q = J_inv[e, q]
            grad_loc_e_7 = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_scalar_8 = np.ascontiguousarray(grad_loc_e_7.T.copy())
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_9 = contract_last_first(const_np_arr_6, grad_scalar_8, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_10 = mul_scalar(const_val_5, dot_9, np.float64)
            # Addition
            res_11 = binary_add_generic(res_4, res_10, np.float64)
            const_val_12 = jit_const_3.item()
            J_inv_q = J_inv[e, q]
            grad_loc_e_13 = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_scalar_14 = np.ascontiguousarray(grad_loc_e_13.T.copy())
            const_np_arr_15 = jit_const_4
            # Dot: scalar Grad(basis) · matrix(value/const) → vector basis
            dot_16 = contract_last_first(transpose_matrix(const_np_arr_15, np.float64), grad_scalar_14, np.float64)
            # Product: const * test
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_17 = mul_scalar(const_val_12, dot_16, np.float64)
            # Addition
            res_18 = binary_add_generic(res_11, res_17, np.float64)
            const_val_19 = jit_const_5.item()
            J_inv_q = J_inv[e, q]
            grad_loc_e_20 = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_scalar_21 = np.ascontiguousarray(grad_loc_e_20.T.copy())
            # Product: const * trial
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_22 = mul_scalar(const_val_19, grad_scalar_21, np.float64)
            const_val_23 = jit_const_6.item()
            const_np_arr_24 = jit_const_2
            J_inv_q = J_inv[e, q]
            grad_loc_e_25 = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_scalar_26 = np.ascontiguousarray(grad_loc_e_25.T.copy())
            # Dot: generic contraction (last axis of A · first axis of B)
            dot_27 = contract_last_first(const_np_arr_24, grad_scalar_26, np.float64)
            # Product: const * trial
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_28 = mul_scalar(const_val_23, dot_27, np.float64)
            # Addition
            res_29 = binary_add_generic(res_22, res_28, np.float64)
            const_val_30 = jit_const_7.item()
            J_inv_q = J_inv[e, q]
            grad_loc_e_31 = np.ascontiguousarray(g_p[e, q]) @ np.ascontiguousarray(J_inv_q.copy())
            grad_scalar_32 = np.ascontiguousarray(grad_loc_e_31.T.copy())
            const_np_arr_33 = jit_const_4
            # Dot: scalar Grad(basis) · matrix(value/const) → vector basis
            dot_34 = contract_last_first(transpose_matrix(const_np_arr_33, np.float64), grad_scalar_32, np.float64)
            # Product: const * trial
            # Product: scalar * Vector/Tensor → Vector/Tensor
            res_35 = mul_scalar(const_val_30, dot_34, np.float64)
            # Addition
            res_36 = binary_add_generic(res_29, res_35, np.float64)
            # Dot plan: basis-basis mass contraction
            dot_37 = dot_mass_test_trial(res_18, res_36, np.float64)
            Ke += dot_37 * w_q

        K_values[e] = Ke
        F_values[e] = Fe
        J_values[e] = J

    return K_values, F_values, J_values


def get_kernel(analytic_map):
    pass
    return kernel
