"""Generate C++ source for pybind11 kernels."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Iterable, Tuple

from matplotlib.pylab import f

from .cache import CODEGEN_ABI_CPP


CPP_HEADER = """// This file is auto-generated by pycutfem C++ backend – DO NOT EDIT
#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>
#include <pybind11/stl.h>
#include <Eigen/Dense>
#include <algorithm>
#include <vector>
#include <omp.h>
#include "helpers.hpp"

namespace py = pybind11;
using namespace pycutfem::cpp_backend;

"""


class CppCodeGen:
    """
    Translate the linear IR into a C++/pybind11 kernel.

    The current implementation mirrors :class:`NumbaCodeGen` to gather
    parameter ordering and active-field bookkeeping, then emits a stub
    kernel that raises a runtime error. The scaffolding keeps function
    names consistent so we can incrementally port the body to Eigen.
    """

    def __init__(
        self,
        *,
        mixed_element,
        form_rank: int = 0,
        on_facet: bool = False,
        mirror=None,
    ) -> None:
        self.mixed_element = mixed_element
        self.form_rank = form_rank
        self.on_facet = on_facet
        # Optional hook to a NumbaCodeGen instance for metadata reuse.
        self._mirror = mirror
        self.include_dirs = [Path(__file__).parent]

    # ------------------------------------------------------------------
    @staticmethod
    def kernel_export_name(default: str = "kernel") -> str:
        """Name of the callable exposed from the compiled module."""
        return default

    # ------------------------------------------------------------------
    def generate_source(
        self, ir_sequence: list, kernel_name: str, module_name: str | None = None
    ) -> Tuple[str, dict[str, Any], list[str]]:
        """
        Produce C++ source, the analytic function map, and parameter order.
        """
        analytic_map: dict[str, Any] = {}
        param_order: list[str] = []

        # IR op classes
        from pycutfem.jit.ir import (
            LoadVariable,
            LoadConstant,
            LoadConstantArray,
            Grad,
            Div,
            BinaryOp,
            Dot,
            Inner,
            Store,
            Transpose,
            Determinant,
            Inverse,
            Trace,
        )

        if self._mirror is not None:
            try:
                _, analytic_map, param_order = self._mirror.generate_source(
                    ir_sequence, kernel_name
                )
            except Exception:
                # Fall back to a minimal param_order built from the IR.
                param_order = []
                needs_b: set[str] = set()
                needs_g: set[str] = set()
                needs_u: set[str] = set()
                for op in ir_sequence:
                    if isinstance(op, LoadVariable):
                        for fn in op.field_names or []:
                            needs_g.add(f"g_{fn}")
                            if op.deriv_order == (0, 0):
                                needs_b.add(f"b_{fn}")
                            else:
                                needs_g.add(f"g_{fn}")
                        if op.role == "function":
                            needs_u.add(f"u_{op.name}_loc")
                param_order = [
                    "gdofs_map",
                    "node_coords",
                    "qp_phys",
                    "qw",
                    "detJ",
                    "J_inv",
                    "normals",
                    "phis",
                    *sorted(needs_b),
                    *sorted(needs_g),
                    *sorted(needs_u),
                ]
        # Ensure required basis/grad tables are present even if mirror omitted them
        needs_b: set[str] = set()
        needs_g: set[str] = set()
        needs_u: set[str] = set()
        for op in ir_sequence:
            if isinstance(op, LoadVariable):
                for fn in op.field_names or []:
                    needs_g.add(f"g_{fn}")
                    needs_b.add(f"b_{fn}")
                if op.role == "function":
                    needs_u.add(f"u_{op.name}_loc")
        for name in sorted(needs_b):
            if name not in param_order:
                param_order.append(name)
        for name in sorted(needs_g):
            if name not in param_order:
                param_order.append(name)
        for name in sorted(needs_u):
            if name not in param_order:
                param_order.append(name)
        # If we saw gradient tables but no corresponding basis, add them.
        for name in list(param_order):
            if name.startswith("g_"):
                bname = f"b_{name[2:]}"
                if bname not in param_order:
                    param_order.append(bname)
        # Ensure all basis arrays for fields exist (safety net)
        for fn in getattr(self.mixed_element, "field_names", ()):
            bname = f"b_{fn}"
            if bname not in param_order:
                param_order.append(bname)

        module_name = module_name or kernel_name

        # ------------------------------------------------------------------
        # IR-driven C++ emission (subset needed for cavity volume kernels)
        # ------------------------------------------------------------------
        from pycutfem.jit.ir import (
            LoadVariable,
            LoadConstant,
            Grad,
            Div,
            BinaryOp,
            Dot,
            Inner,
            Store,
            Trace,
        )

        # local helpers ----------------------------------------------------
        field_slices = {
            name: self.mixed_element.component_dof_slices[name]
            for name in self.mixed_element.field_names
        }

        def new_tmp(prefix="tmp", counter={"i": 0}):
            counter["i"] += 1
            return f"{prefix}_{counter['i']}"

        class StackItem:
            __slots__ = ("name", "kind", "role", "shape", "field_names", "parent")

            def __init__(self, name, kind, role, shape, field_names=None, parent=""):
                self.name = name
                self.kind = kind  # scalar | mat | grad | vec | const_arr
                self.role = role
                self.shape = shape
                self.field_names = field_names or []
                self.parent = parent  # parent symbol name for functions

        # argument declaration ---------------------------------------------
        arg_decls: list[str] = []
        for name in param_order:
            if name == "gdofs_map":
                arg_decls.append(
                    "py::array_t<int32_t, py::array::c_style | py::array::forcecast> gdofs_map"
                )
            elif name in {"qp_phys", "qw", "detJ", "J_inv", "normals", "phis"}:
                arg_decls.append(
                    f"py::array_t<double, py::array::c_style | py::array::forcecast> {name}"
                )
            else:
                arg_decls.append(
                    f"py::array_t<double, py::array::c_style | py::array::forcecast> {name}"
                )
        arg_sig = ",\n        ".join(arg_decls)
        param_list = ", ".join([f'py::str("{p}")' for p in param_order])

        # views for arrays used frequently
        view_lines = [
            "    auto qp_view = qp_phys.unchecked<3>();",
            "    auto qw_view = qw.unchecked<2>();",
            "    auto Jinv_view = J_inv.unchecked<4>();",
        ]
        for name in param_order:
            if name.startswith("b_"):
                view_lines.append(f"    auto {name}_view = {name}.unchecked<3>();")
            if name.startswith("g_"):
                view_lines.append(f"    auto {name}_view = {name}.unchecked<4>();")
            if name.startswith("u_"):
                view_lines.append(f"    auto {name}_view = {name}.unchecked<2>();")

        prologue = [
            "    ssize_t n_elem = qp_view.shape(0);",
            "    ssize_t n_q    = qp_view.shape(1);",
            "    ssize_t n_union = gdofs_map.shape(1);",
            "    py::array_t<double> K({n_elem, n_union, n_union});",
            "    py::array_t<double> F({n_elem, n_union});",
            "    py::array_t<double> J({n_elem});",
            "    auto K_view = K.mutable_unchecked<3>();",
            "    auto F_view = F.mutable_unchecked<2>();",
            "    auto J_out  = J.mutable_unchecked<1>();",
            "    for (ssize_t e = 0; e < n_elem; ++e) {",
            "        for (ssize_t i = 0; i < n_union; ++i) {",
            "            F_view(e, i) = 0.0;",
            "            for (ssize_t j = 0; j < n_union; ++j) K_view(e, i, j) = 0.0;",
            "        }",
            "        J_out(e) = 0.0;",
            "    }",
        ]

        # body generation --------------------------------------------------
        stack: list[StackItem] = []
        body_lines: list[str] = []

        def emit_line(line: str):
            if line.strip():
                body_lines.append("            " + line)

        for idx, op in enumerate(ir_sequence):
            next_op = ir_sequence[idx + 1] if idx + 1 < len(ir_sequence) else None
            if isinstance(op, LoadConstant):
                nm = new_tmp("c")
                emit_line(f"double {nm} = {float(op.value)};")
                stack.append(StackItem(nm, "scalar", "const", ()))
            elif isinstance(op, LoadConstantArray):
                req = new_tmp("buf")
                emit_line(f"auto {req} = {op.name}.request();")
                nm = new_tmp("const_arr")
                emit_line(f"Eigen::MatrixXd {nm};")
                kind = "mat"
                shape = op.shape
                emit_line(f"if ({req}.ndim == 0) {{")
                emit_line(f"    double _c = *static_cast<double*>({req}.ptr);")
                emit_line(f"    {nm} = Eigen::MatrixXd::Constant(1, 1, _c);")
                emit_line("}")
                emit_line(f"else if ({req}.ndim == 1) {{")
                emit_line(f"    Eigen::Map<const Eigen::VectorXd> _map_{nm}(static_cast<double*>({req}.ptr), {req}.shape[0]);")
                emit_line(f"    {nm} = _map_{nm};")
                kind = "vec"
                shape = (op.shape[0],)
                emit_line("}")
                emit_line(f"else if ({req}.ndim == 2) {{")
                emit_line(f"    Eigen::Map<const Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>> _map_{nm}(static_cast<double*>({req}.ptr), {req}.shape[0], {req}.shape[1]);")
                emit_line(f"    {nm} = _map_{nm};")
                emit_line("}")
                emit_line("else { throw std::runtime_error(\"Unsupported constant array rank for C++ backend\"); }")
                stack.append(StackItem(nm, kind, "const", shape))
            elif isinstance(op, LoadVariable):
                followed_by_diff = isinstance(next_op, (Grad,))
                if op.role in {"test", "trial"} and op.deriv_order == (0, 0):
                    if followed_by_diff:
                        stack.append(
                            StackItem("__basis__", "basis_ref", op.role, (len(op.field_names), -1), op.field_names, op.name)
                        )
                        continue
                    k = len(op.field_names)
                    nm = new_tmp("basis")
                    emit_line(f"Eigen::MatrixXd {nm}({k}, n_union);")
                    for idx2, fn in enumerate(op.field_names):
                        emit_line(
                            f"for (ssize_t j=0; j<n_union; ++j) {nm}({idx2}, j) = b_{fn}_view(e, q, j);"
                        )
                    stack.append(StackItem(nm, "mat", op.role, (k, -1), op.field_names, op.name))
                elif op.role in {"test", "trial"} and op.deriv_order == (1, 0) or op.deriv_order == (0, 1):
                    raise NotImplementedError("Direct derivative load not handled; Grad op expected.")
                elif op.role == "function":
                    # coeffs are pre-gathered u_<name>_loc[e, :]
                    coeff_name = f"u_{op.name}_loc"
                    k = len(op.field_names)
                    nm = new_tmp("val")
                    emit_line(f"Eigen::VectorXd {nm}({k});")
                    for idx, fn in enumerate(op.field_names):
                        s0 = field_slices.get(fn, slice(0, 0)).start
                        s1 = field_slices.get(fn, slice(0, 0)).stop
                        emit_line(
                            f"{nm}({idx}) = load_variable_component({coeff_name}_view, b_{fn}_view, e, q, {s0}, {s1});"
                        )
                    stack.append(StackItem(nm, "vec", "value", (k,), op.field_names, op.name))
                else:
                    raise NotImplementedError(f"LoadVariable role {op.role} unsupported in C++ backend")
            elif isinstance(op, Grad):
                a = stack.pop()
                if a.kind in {"mat", "basis_ref"} and a.role in {"test", "trial"}:
                    k = len(a.field_names)
                    nm = new_tmp("grad")
                    emit_line(f"std::vector<Eigen::MatrixXd> {nm}; {nm}.resize({k});")
                    for idx, fn in enumerate(a.field_names):
                        emit_line(f"{nm}[{idx}] = Eigen::MatrixXd(n_union, 2);")
                        emit_line(f"for (ssize_t j=0; j<n_union; ++j) {{")
                        emit_line(
                            f"    double gx = g_{fn}_view(e,q,j,0); double gy = g_{fn}_view(e,q,j,1);"
                        )
                        emit_line(
                            f"    double px = gx*Jloc(0,0) + gy*Jloc(1,0); double py = gx*Jloc(0,1) + gy*Jloc(1,1);"
                        )
                        emit_line(f"    {nm}[{idx}](j,0)=px; {nm}[{idx}](j,1)=py;")
                        emit_line("}")
                    stack.append(StackItem(nm, "grad", a.role, (k, -1, 2), a.field_names, a.parent))
                elif a.kind == "vec" and a.role == "value":
                    # gradient of function value: use coefficient map and grad basis
                    k = len(a.field_names)
                    nm = new_tmp("gval")
                    emit_line(f"Eigen::MatrixXd {nm}({k}, 2);")
                    for idx, fn in enumerate(a.field_names):
                        s0 = field_slices.get(fn, slice(0, 0)).start
                        s1 = field_slices.get(fn, slice(0, 0)).stop
                        emit_line(
                            f"gradient_component({nm}, {idx}, u_{a.parent}_loc_view, g_{fn}_view, Jloc, e, q, {s0}, {s1});"
                        )
                    stack.append(StackItem(nm, "mat", "value", (k, 2), a.field_names, a.parent))
                else:
                    raise NotImplementedError("Grad on unsupported item")
            elif isinstance(op, Div):
                a = stack.pop()
                if a.kind == "grad":
                    nm = new_tmp("div")
                    k = len(a.field_names)
                    emit_line(f"Eigen::MatrixXd {nm}(1, n_union);")
                    emit_line(f"{nm}.setZero();")
                    emit_line(f"for (ssize_t j=0; j<n_union; ++j) {{")
                    emit_line(
                        f"    {nm}(0,j) = {a.name}[0](j,0) + {a.name}[1](j,1);"
                    )
                    emit_line("}")
                    stack.append(StackItem(nm, "mat", a.role, (1, -1), a.field_names))
                elif a.kind == "mat" and a.role == "value":
                    nm = new_tmp("divv")
                    emit_line(f"double {nm} = {a.name}(0,0) + {a.name}(1,1);")
                    stack.append(StackItem(nm, "scalar", "value", ()))
                else:
                    raise NotImplementedError("Div on unsupported item")
            elif isinstance(op, BinaryOp):
                b = stack.pop()
                a = stack.pop()
                nm = new_tmp("bin")
                if op.op_symbol == "+":
                    if a.kind == "grad" and b.kind == "grad":
                        emit_line(f"std::vector<Eigen::MatrixXd> {nm}; {nm}.resize({a.name}.size());")
                        emit_line(f"for (size_t _i=0; _i<{a.name}.size(); ++_i) {nm}[_i] = {a.name}[_i] + {b.name}[_i];")
                        stack.append(StackItem(nm, "grad", a.role, a.shape, a.field_names, a.parent))
                    elif a.kind == "mat" and b.kind == "grad":
                        emit_line(f"auto {nm} = add_grad_mat(GradStack{{{b.name}}}, {a.name}).comps;")
                        stack.append(StackItem(nm, "grad", b.role, b.shape, b.field_names, b.parent))
                    elif a.kind == "grad" and b.kind == "mat":
                        emit_line(f"auto {nm} = add_grad_mat(GradStack{{{a.name}}}, {b.name}).comps;")
                        stack.append(StackItem(nm, "grad", a.role, a.shape, a.field_names, a.parent))
                    else:
                        emit_line(f"auto {nm} = {a.name} + {b.name};")
                        stack.append(StackItem(nm, a.kind, a.role, a.shape))
                elif op.op_symbol == "-":
                    if a.kind == "grad" and b.kind == "grad":
                        emit_line(f"std::vector<Eigen::MatrixXd> {nm}; {nm}.resize({a.name}.size());")
                        emit_line(f"for (size_t _i=0; _i<{a.name}.size(); ++_i) {nm}[_i] = {a.name}[_i] - {b.name}[_i];")
                        stack.append(StackItem(nm, "grad", a.role, a.shape, a.field_names, a.parent))
                    elif a.kind == "mat" and b.kind == "grad":
                        emit_line(f"auto {nm} = mat_sub_grad({a.name}, GradStack{{{b.name}}}).comps;")
                        stack.append(StackItem(nm, "grad", b.role, b.shape, b.field_names, b.parent))
                    elif a.kind == "grad" and b.kind == "mat":
                        emit_line(f"auto {nm} = sub_grad_mat(GradStack{{{a.name}}}, {b.name}).comps;")
                        stack.append(StackItem(nm, "grad", a.role, a.shape, a.field_names, a.parent))
                    elif a.kind == "scalar" and b.kind == "mat":
                        emit_line(f"Eigen::MatrixXd {nm}(n_union, {b.name}.cols());")
                        emit_line(f"{nm}.setConstant({a.name});")
                        emit_line(f"{nm} -= {b.name};")
                        stack.append(StackItem(nm, "mat", b.role, (-1, -1), b.field_names, b.parent))
                    elif a.kind == "scalar" and b.kind == "grad":
                        emit_line(f"std::vector<Eigen::MatrixXd> {nm}; {nm}.resize({b.name}.size());")
                        emit_line(f"for (size_t _i=0; _i<{b.name}.size(); ++_i) {{")
                        emit_line(f"    {nm}[_i] = Eigen::MatrixXd(n_union, {b.name}[_i].cols());")
                        emit_line(f"    {nm}[_i].setConstant({a.name});")
                        emit_line(f"    {nm}[_i] -= {b.name}[_i];")
                        emit_line("}")
                        stack.append(StackItem(nm, "grad", b.role, b.shape, b.field_names, b.parent))
                    else:
                        emit_line(f"auto {nm} = {a.name} - {b.name};")
                        stack.append(StackItem(nm, a.kind, a.role, a.shape))
                elif op.op_symbol == "*":
                    # Outer product when scaling test/trial basis (1,n) with value vector (1,n) -> n x n
                    if a.kind == "mat" and a.shape[0] == 1 and a.role in {"test", "trial"} and b.kind == "mat" and b.shape[0] == 1 and b.role == "value":
                        emit_line(f"Eigen::MatrixXd {nm} = {a.name}.transpose() * {b.name};")
                        stack.append(StackItem(nm, "mat", "value", (-1, -1)))
                        continue
                    if b.kind == "mat" and b.shape[0] == 1 and b.role in {"test", "trial"} and a.kind == "mat" and a.shape[0] == 1 and a.role == "value":
                        emit_line(f"Eigen::MatrixXd {nm} = {b.name}.transpose() * {a.name};")
                        stack.append(StackItem(nm, "mat", "value", (-1, -1)))
                        continue
                    # Outer product for scalar test/trial factors (e.g., pressure · div(velocity))
                    if a.kind == "mat" and b.kind == "mat" and a.role == "test" and b.role == "trial" and a.shape[0] == 1 and b.shape[0] == 1:
                        emit_line(f"Eigen::MatrixXd {nm} = {a.name}.transpose() * {b.name};")
                        stack.append(StackItem(nm, "mat", "value", (-1, -1)))
                        continue
                    if a.kind == "mat" and b.kind == "mat" and a.role == "trial" and b.role == "test" and a.shape[0] == 1 and b.shape[0] == 1:
                        emit_line(f"Eigen::MatrixXd {nm} = {b.name}.transpose() * {a.name};")
                        stack.append(StackItem(nm, "mat", "value", (-1, -1)))
                        continue
                    if a.kind == "scalar" and b.kind == "grad":
                        emit_line(f"std::vector<Eigen::MatrixXd> {nm}; {nm}.resize({b.name}.size());")
                        emit_line(f"for (size_t _i=0; _i<{b.name}.size(); ++_i) {nm}[_i] = {b.name}[_i] * {a.name};")
                        stack.append(StackItem(nm, "grad", b.role, b.shape, b.field_names, b.parent))
                    elif b.kind == "scalar" and a.kind == "grad":
                        emit_line(f"std::vector<Eigen::MatrixXd> {nm}; {nm}.resize({a.name}.size());")
                        emit_line(f"for (size_t _i=0; _i<{a.name}.size(); ++_i) {nm}[_i] = {a.name}[_i] * {b.name};")
                        stack.append(StackItem(nm, "grad", a.role, a.shape, a.field_names, a.parent))
                    elif a.kind == "grad" and b.kind == "grad":
                        emit_line(f"auto {nm} = cwise_grad_grad(GradStack{{{a.name}}}, GradStack{{{b.name}}}).comps;")
                        stack.append(StackItem(nm, "grad", a.role, a.shape, a.field_names, a.parent))
                    elif a.kind == "grad" and b.kind == "mat":
                        emit_line(f"auto {nm} = cwise_grad_mat(GradStack{{{a.name}}}, {b.name}).comps;")
                        stack.append(StackItem(nm, "grad", a.role, a.shape, a.field_names, a.parent))
                    elif a.kind == "mat" and b.kind == "grad":
                        emit_line(f"auto {nm} = cwise_mat_grad({a.name}, GradStack{{{b.name}}}).comps;")
                        stack.append(StackItem(nm, "grad", b.role, b.shape, b.field_names, b.parent))
                    elif a.kind == "scalar" and b.kind != "scalar":
                        emit_line(f"auto {nm} = {b.name} * {a.name};")
                        stack.append(StackItem(nm, b.kind, b.role, b.shape))
                    elif b.kind == "scalar" and a.kind != "scalar":
                        emit_line(f"auto {nm} = {a.name} * {b.name};")
                        stack.append(StackItem(nm, a.kind, a.role, a.shape))
                    elif a.kind == "scalar" and b.kind == "scalar":
                        emit_line(f"double {nm} = {a.name} * {b.name};")
                        stack.append(StackItem(nm, "scalar", a.role, ()))
                    else:
                        emit_line(f"auto {nm} = {a.name}.cwiseProduct({b.name});")
                        stack.append(StackItem(nm, a.kind, a.role, a.shape))
                elif op.op_symbol == "/":
                    if b.kind == "scalar" and a.kind == "grad":
                        emit_line(f"std::vector<Eigen::MatrixXd> {nm}; {nm}.resize({a.name}.size());")
                        emit_line(f"for (size_t _i=0; _i<{a.name}.size(); ++_i) {nm}[_i] = {a.name}[_i] / {b.name};")
                        stack.append(StackItem(nm, "grad", a.role, a.shape, a.field_names, a.parent))
                    elif b.kind == "scalar":
                        emit_line(f"auto {nm} = {a.name} / {b.name};")
                        stack.append(StackItem(nm, a.kind, a.role, a.shape))
                    else:
                        raise NotImplementedError("Only scalar denominator supported")
                else:
                    raise NotImplementedError(f"Binary op {op.op_symbol} unsupported")
            elif isinstance(op, Dot):
                b = stack.pop()
                a = stack.pop()
                nm = new_tmp("dot")
                a_union_mat = a.kind == "mat" and len(a.shape) >= 2 and a.shape[1] == -1
                b_union_mat = b.kind == "mat" and len(b.shape) >= 2 and b.shape[1] == -1
                print(f"(a,b): kind=({a.kind}, {b.kind}), role=({a.role}, {b.role}), shape=({a.shape}, {b.shape})")
                # trial/test mass
                # Gradient advection combinations: grad(Function) · Trial  or Trial · grad(Function)
                if a.role == "value" and b.role == "trial" and a.kind == "mat" and b.kind == "mat":
                    emit_line(f"Eigen::MatrixXd {nm} = dot_grad_func_trial_vec({a.name}, {b.name});")
                    stack.append(StackItem(nm, "mat", "trial", (a.shape[1] if len(a.shape)>1 else -1, -1), b.field_names, b.parent))
                elif a.role == "trial" and b.role == "value" and a.kind == "mat" and b.kind == "mat":
                    emit_line(f"Eigen::MatrixXd {nm} = dot_trial_vec_grad_func({a.name}, {b.name});")
                    stack.append(StackItem(nm, "mat", "trial", (b.shape[1] if len(b.shape)>1 else -1, -1), a.field_names, a.parent))
                # Explicit Test/Trial mass-like dot even when shapes are concrete (not -1 flagged)
                elif a.role == "trial" and b.role == "test":
                    emit_line(f"Eigen::MatrixXd {nm} = dot_mass_test_trial({b.name}, {a.name});")
                    stack.append(StackItem(nm, "mat", "value", (-1, -1)))
                elif a.role == "test" and b.role == "trial":
                    emit_line(f"Eigen::MatrixXd {nm} = dot_mass_test_trial({a.name}, {b.name});")
                    stack.append(StackItem(nm, "mat", "value", (-1, -1)))
                elif a.kind == "mat" and b.kind == "mat" and a_union_mat and b_union_mat:
                    # Preserve Test/Trial orientation (test^T @ trial)
                    if b.role == "test":
                        emit_line(f"Eigen::MatrixXd {nm} = dot_mass_test_trial({b.name}, {a.name});")
                    elif a.role == "test":
                        emit_line(f"Eigen::MatrixXd {nm} = dot_mass_test_trial({a.name}, {b.name});")
                    elif a.role == "trial" and b.role == "trial":
                        emit_line(f"Eigen::MatrixXd {nm} = dot_mass_test_trial({a.name}, {b.name});")
                    else:
                        emit_line(f"Eigen::MatrixXd {nm} = dot_mass_test_trial({a.name}, {b.name});")
                    stack.append(StackItem(nm, "mat", "value", (-1, -1)))
                elif a.kind == "grad" and b.kind == "mat":
                    # grad(test/trial) with basis matrix -> standard assembly helper
                    print(f"salma " * 10)
                    if a.role in {"test", "trial"} and b.role in {"value"}:
                        emit_line(f"auto {nm} = dot_grad_basis_with_grad_value({a.name}, {b.name});")
                        stack.append(StackItem(nm, "grad", a.role, a.shape, a.field_names, a.parent))
                    elif a.role in {"value"} and b.role in {"test", "trial"}:
                        emit_line(f"auto {nm} = dot_grad_value_with_basis({a.name}, {b.name});")
                        stack.append(StackItem(nm, "grad", b.role, b.shape, b.field_names, b.parent))
                    elif len(b.shape) >= 2 and b.shape[1] == -1:
                        emit_line(f"Eigen::MatrixXd {nm} = dot_grad_trial({a.name}, {b.name});")
                        stack.append(StackItem(nm, "mat", "value", (-1, -1)))
                    else:
                        emit_line(f"std::vector<Eigen::MatrixXd> {nm}; {nm}.resize({a.name}.size());")
                        emit_line(f"for (size_t _c=0; _c<{a.name}.size(); ++_c) {{")
                        emit_line(f"    {nm}[_c] = {a.name}[_c] * {b.name};")
                        emit_line("}")
                        # shape fallback: keep same component/count, cols from b if available
                        out_shape = (
                            a.shape[0],
                            a.shape[1],
                            b.shape[1] if len(b.shape) > 1 else 0,
                        )
                        stack.append(StackItem(nm, "grad", a.role, out_shape, a.field_names, a.parent))
                elif a.kind == "mat" and b.kind == "vec":
                    emit_line(f"Eigen::VectorXd {nm} = {a.name} * {b.name};")
                    stack.append(StackItem(nm, "vec", "value", (-1,)))
                elif a.kind == "vec" and b.kind == "mat":
                    emit_line(f"Eigen::VectorXd {nm} = {b.name}.transpose() * {a.name};")
                    stack.append(StackItem(nm, "vec", "value", (-1,)))
                elif a.kind == "vec" and b.kind == "grad":
                    emit_line(f"Eigen::MatrixXd {nm} = vector_dot_grad_basis({a.name}, {b.name});")
                    out_rows = 1 if b.shape[0] == 1 else (b.shape[2] if len(b.shape) > 2 else -1)
                    out_shape = (out_rows, b.shape[1] if len(b.shape) > 1 else -1)
                    stack.append(StackItem(nm, "mat", b.role, out_shape, b.field_names, b.parent))
                elif a.kind == "grad" and b.kind == "vec":
                    emit_line(f"Eigen::MatrixXd {nm} = dot_grad_basis_vector({a.name}, {b.name});")
                    stack.append(StackItem(nm, "mat", a.role, (a.shape[0], a.shape[1]), a.field_names, a.parent))
                elif a.kind == "grad" and b.kind == "grad":
                    emit_line(f"Eigen::MatrixXd {nm} = inner_grad_grad({a.name}, {b.name});")
                    stack.append(StackItem(nm, "mat", "value", (-1, -1)))
                elif a.kind == "mat" and b.kind == "mat":
                    emit_line(f"Eigen::MatrixXd {nm} = {a.name} * {b.name};")
                    stack.append(StackItem(nm, "mat", "value", (-1, -1)))
                elif a.kind == "mat" and b.kind == "grad":
                    kname = new_tmp("k")
                    dname = new_tmp("d")
                    flat  = new_tmp("flat")
                    prod  = new_tmp("prod")
                    emit_line(f"int {kname} = static_cast<int>({b.name}.size());")
                    emit_line(f"int {dname} = {kname} > 0 ? static_cast<int>({b.name}[0].cols()) : 0;")
                    emit_line(f"Eigen::MatrixXd {flat}({kname}, n_union * {dname});")
                    emit_line(f"for (int _c=0; _c<{kname}; ++_c) {{")
                    emit_line(f"    for (ssize_t _j=0; _j<n_union; ++_j) {{")
                    emit_line(f"        for (int _r=0; _r<{dname}; ++_r) {flat}(_c, _j * {dname} + _r) = {b.name}[_c](_j, _r);")
                    emit_line("    }")
                    emit_line("}")
                    emit_line(f"Eigen::MatrixXd {prod} = {a.name} * {flat};")
                    emit_line(f"std::vector<Eigen::MatrixXd> {nm}; {nm}.resize(static_cast<size_t>({prod}.rows()));")
                    emit_line(f"for (int _r=0; _r<{prod}.rows(); ++_r) {{")
                    emit_line(f"    {nm}[_r] = Eigen::MatrixXd(n_union, {dname});")
                    emit_line(f"    for (ssize_t _j=0; _j<n_union; ++_j) {{")
                    emit_line(f"        for (int _c=0; _c<{dname}; ++_c) {nm}[_r](_j, _c) = {prod}(_r, _j * {dname} + _c);")
                    emit_line("    }")
                    emit_line("}")
                    stack.append(StackItem(nm, "grad", b.role, (a.shape[0], b.shape[1], b.shape[2]), b.field_names, b.parent))
                elif a.kind == "vec" and b.kind == "vec":
                    emit_line(f"double {nm} = {a.name}.dot({b.name});")
                    stack.append(StackItem(nm, "scalar", "value", ()))
                else:
                    raise NotImplementedError(
                        f"Dot combination unsupported: a={a.kind}/{a.role}/{a.shape}, "
                        f"b={b.kind}/{b.role}/{b.shape}"
                    )
            elif isinstance(op, Inner):
                b = stack.pop()
                a = stack.pop()
                nm = new_tmp("inner")
                if a.kind == "grad" and b.kind == "grad":
                    emit_line(f"Eigen::MatrixXd {nm} = inner_grad_grad({a.name}, {b.name});")
                    stack.append(StackItem(nm, "mat", "value", (-1, -1)))
                elif a.kind == "mat" and b.kind == "mat":
                    emit_line(f"double {nm} = ({a.name}.cwiseProduct({b.name})).sum();")
                    stack.append(StackItem(nm, "scalar", "value", ()))
                elif a.kind == "vec" and b.kind == "vec":
                    emit_line(f"double {nm} = {a.name}.dot({b.name});")
                    stack.append(StackItem(nm, "scalar", "value", ()))
                elif a.kind == "grad" and b.kind == "mat":
                    emit_line(f"Eigen::VectorXd {nm} = inner_grad_const({a.name}, {b.name});")
                    stack.append(StackItem(nm, "vec", "value", (-1,)))
                elif a.kind == "mat" and b.kind == "grad":
                    emit_line(f"Eigen::VectorXd {nm} = inner_const_grad({a.name}, {b.name});")
                    stack.append(StackItem(nm, "vec", "value", (-1,)))
                else:
                    raise NotImplementedError("Inner only implemented for grad-grad and matching mat/vec")
            elif isinstance(op, Transpose):
                a = stack.pop()
                nm = new_tmp("tr")
                if a.kind == "mat":
                    emit_line(f"auto {nm} = {a.name}.transpose();")
                    stack.append(StackItem(nm, "mat", a.role, a.shape[::-1] if len(a.shape)>=2 else a.shape))
                elif a.kind == "grad":
                    emit_line(f"auto {nm} = transpose_grad_stack({a.name});")
                    new_shape = (a.shape[2], a.shape[1], a.shape[0]) if len(a.shape) >= 3 else a.shape
                    stack.append(StackItem(nm, "grad", a.role, new_shape, a.field_names))
                else:
                    raise NotImplementedError("Transpose only implemented for matrices/grad stacks")
            elif isinstance(op, Determinant):
                a = stack.pop()
                nm = new_tmp("det")
                if a.kind in {"mat", "grad"}:
                    emit_line(f"double {nm} = {a.name}.determinant();")
                    stack.append(StackItem(nm, "scalar", a.role, ()))
                else:
                    raise NotImplementedError("Determinant only implemented for matrices")
            elif isinstance(op, Inverse):
                a = stack.pop()
                nm = new_tmp("inv")
                if a.kind in {"mat", "grad"}:
                    emit_line(f"Eigen::MatrixXd {nm} = {a.name}.inverse();")
                    stack.append(StackItem(nm, "mat", a.role, a.shape))
                else:
                    raise NotImplementedError("Inverse only implemented for matrices")
            elif isinstance(op, Trace):
                a = stack.pop()
                nm = new_tmp("trace")
                if a.kind == "mat":
                    emit_line(f"double {nm} = {a.name}.trace();")
                    stack.append(StackItem(nm, "scalar", a.role, ()))
                elif a.kind == "grad":
                    emit_line(f"Eigen::MatrixXd {nm}(1, n_union);")
                    emit_line(f"{nm}.setZero();")
                    emit_line(f"for (ssize_t _j=0; _j<n_union; ++_j) {{")
                    emit_line(f"    double _acc = 0.0;")
                    emit_line(f"    for (size_t _c=0; _c<{a.name}.size(); ++_c) {{")
                    emit_line(f"        if ({a.name}[_c].cols() > static_cast<Eigen::Index>(_c)) _acc += {a.name}[_c](_j, static_cast<Eigen::Index>(_c));")
                    emit_line("    }")
                    emit_line(f"    {nm}(0, _j) = _acc;")
                    emit_line("}")
                    stack.append(StackItem(nm, "mat", a.role, (1, a.shape[1]), a.field_names, a.parent))
                else:
                    raise NotImplementedError("Trace only implemented for matrices")
            elif isinstance(op, Store):
                a = stack.pop()
                if op.store_type == "matrix":
                    if a.kind == "scalar":
                        emit_line(f"for (ssize_t i=0;i<n_union;++i) for (ssize_t j=0;j<n_union;++j) K_view(e,i,j)+= {a.name} * qw_view(e,q);")
                    elif a.kind == "grad":
                        emit_line(f"Eigen::MatrixXd _tmpK = Eigen::MatrixXd::Zero(n_union, n_union);")
                        emit_line(f"for (auto& _m : {a.name}) {{")
                        emit_line(f"    Eigen::Index _cols = std::min<Eigen::Index>(_m.cols(), n_union);")
                        emit_line(f"    for (ssize_t _i=0; _i<n_union; ++_i) {{")
                        emit_line(f"        for (Eigen::Index _j=0; _j<_cols; ++_j) _tmpK(_i,_j) += _m(_i,_j);")
                        emit_line("    }")
                        emit_line("}")
                        emit_line(f"for (ssize_t i=0;i<n_union;++i) for (ssize_t j=0;j<n_union;++j) K_view(e,i,j)+= _tmpK(i,j) * qw_view(e,q);")
                    else:
                        emit_line(f"for (ssize_t i=0;i<n_union;++i) for (ssize_t j=0;j<n_union;++j) K_view(e,i,j)+= {a.name}(i,j) * qw_view(e,q);")
                elif op.store_type == "vector":
                    if a.kind == "scalar":
                        emit_line(f"for (ssize_t i=0;i<n_union;++i) F_view(e,i)+= {a.name} * qw_view(e,q);")
                    elif a.kind == "grad":
                        emit_line(f"Eigen::VectorXd _tmpF = Eigen::VectorXd::Zero(n_union);")
                        emit_line(f"for (auto& _m : {a.name}) {{")
                        emit_line(f"    Eigen::Index _cols = std::min<Eigen::Index>(_m.cols(), 1);")
                        emit_line(f"    for (ssize_t _i=0; _i<n_union; ++_i) for (Eigen::Index _j=0; _j<_cols; ++_j) _tmpF(_i) += _m(_i,_j);")
                        emit_line("    }")
                        emit_line(f"for (ssize_t i=0;i<n_union;++i) F_view(e,i)+= _tmpF(i) * qw_view(e,q);")
                    else:
                        emit_line(f"for (ssize_t i=0;i<n_union;++i) F_view(e,i)+= {a.name}(i) * qw_view(e,q);")
                elif op.store_type == "functional":
                    emit_line(f"J_out(e) += {a.name} * qw_view(e,q);")
                else:
                    raise NotImplementedError(f"Store type {op.store_type}")
            else:
                raise NotImplementedError(f"Opcode {type(op).__name__} not handled in C++ backend")

        loop_block = "\n".join(body_lines)

        full_src = (
            CPP_HEADER
            + f"""
static py::tuple {kernel_name}(
        {arg_sig}
    ) {{
{chr(10).join(view_lines)}
{chr(10).join(prologue)}

    for (ssize_t e = 0; e < n_elem; ++e) {{
        for (ssize_t q = 0; q < n_q; ++q) {{
            Eigen::Matrix<double,2,2> Jloc;
            Jloc(0,0)=Jinv_view(e,q,0,0); Jloc(0,1)=Jinv_view(e,q,0,1);
            Jloc(1,0)=Jinv_view(e,q,1,0); Jloc(1,1)=Jinv_view(e,q,1,1);
{loop_block}
        }}
    }}

    return py::make_tuple(K, F, J);
}}

PYBIND11_MODULE({module_name}, m) {{
    m.doc() = "pycutfem experimental C++ kernel";
    m.def("{kernel_name}", &{kernel_name}, "Experimental C++ kernel");
    m.attr("PARAM_ORDER") = py::make_tuple({param_list});
    m.attr("CODEGEN_ABI") = "{CODEGEN_ABI_CPP}";
}}
"""
        )
        return full_src, analytic_map, param_order

    # ------------------------------------------------------------------
    def _generate_navier_volume_kernel(
        self,
        *,
        kernel_name: str,
        module_name: str,
        param_order: list[str],
        vel_fields: list[str],
        p_field: str,
        rho: float,
        dt: float,
        theta: float,
        mu: float,
        assemble_ke: bool,
        assemble_fe: bool,
    ) -> str:
        """
        Emit a hand-written C++ kernel for the 2D Navier–Stokes volume terms.
        This covers the cavity verification example (velocity + pressure).
        """
        if len(vel_fields) < 2:
            raise NotImplementedError("Navier kernel expects at least two velocity components.")

        b0 = f"b_{vel_fields[0]}"
        b1 = f"b_{vel_fields[1]}"
        g0 = f"g_{vel_fields[0]}"
        g1 = f"g_{vel_fields[1]}"
        bp = f"b_{p_field}"

        uk = next((p for p in param_order if p.startswith("u_u_k")), "u_u_k_loc")
        un = next((p for p in param_order if p.startswith("u_u_n")), None)
        pk = next((p for p in param_order if p.startswith(f"u_{p_field}")), None)

        # argument signature
        arg_decls: list[str] = []
        for name in param_order:
            if name == "gdofs_map":
                arg_decls.append("py::array_t<int32_t, py::array::c_style | py::array::forcecast> gdofs_map")
            elif name in {"qp_phys", "qw", "detJ", "J_inv"}:
                arg_decls.append(f"py::array_t<double, py::array::c_style | py::array::forcecast> {name}")
            elif name.startswith(("g_", "b_", "u_")):
                arg_decls.append(f"py::array_t<double, py::array::c_style | py::array::forcecast> {name}")
            else:
                arg_decls.append(f"py::object {name}")

        arg_sig = ",\n        ".join(arg_decls)
        param_list = ", ".join([f'py::str("{p}")' for p in param_order])

        un_block = ""
        if un:
            un_block = """
    auto un_view = %(un)s.unchecked<2>();
""" % {"un": un}

        pk_block = ""
        if pk:
            pk_block = """
            for (ssize_t i = 0; i < n_union; ++i) {
                pk_val += pk_view(e, i) * bp_view(e, q, i);
            }
"""

        un_val_block = ""
        if un:
            un_val_block = (
                "            for (ssize_t i = 0; i < n_union; ++i) { "
                "double coeff = un_view(e, i); un0 += coeff * b0_view(e, q, i); "
                "un1 += coeff * b1_view(e, q, i); }\n"
            )

        un_grad_block = ""
        if un:
            un_grad_block = (
                "            for (ssize_t i = 0; i < n_union; ++i) { "
                "double coeff = un_view(e, i); gun00 += coeff * g0x[i]; "
                "gun01 += coeff * g0y[i]; gun10 += coeff * g1x[i]; "
                "gun11 += coeff * g1y[i]; }\n"
            )

        ke_block = ""
        if assemble_ke:
            ke_block = r"""
            for (ssize_t i = 0; i < n_union; ++i) {
                double b0i = b0_view(e, q, i);
                double b1i = b1_view(e, q, i);
                double div_i = div_phi[i];
                double bp_i = bp_view(e, q, i);
                for (ssize_t j = 0; j < n_union; ++j) {
                    double b0j = b0_view(e, q, j);
                    double b1j = b1_view(e, q, j);
                    double div_j = div_phi[j];
                    double bp_j = bp_view(e, q, j);
                    double mass = b0i * b0j + b1i * b1j;
                    double conv1 = (guk00 * b0j + guk01 * b1j) * b0i + (guk10 * b0j + guk11 * b1j) * b1i;
                    double conv2 = (g0x[j] * uk0 + g0y[j] * uk1) * b0i + (g1x[j] * uk0 + g1y[j] * uk1) * b1i;
                    double visc = g0x[j] * g0x[i] + g0y[j] * g0y[i] + g1x[j] * g1x[i] + g1y[j] * g1y[i];
                    double val = mass_coeff * mass + conv_k_coeff * (conv1 + conv2) + visc_k_coeff * visc;
                    K_view(e, i, j) += w * val;
                    K_view(e, i, j) -= w * div_i * bp_j;
                    K_view(e, i, j) += w * bp_i * div_j;
                }
            }
"""

        fe_block = ""
        if assemble_fe:
            fe_block = r"""
            for (ssize_t i = 0; i < n_union; ++i) {
                double b0i = b0_view(e, q, i);
                double b1i = b1_view(e, q, i);
                double div_i = div_phi[i];
                double acc = mass_coeff * ((uk0 - un0) * b0i + (uk1 - un1) * b1i);
                double conv_k = (guk00 * uk0 + guk01 * uk1) * b0i + (guk10 * uk0 + guk11 * uk1) * b1i;
                acc += conv_k_coeff * conv_k;
                double conv_n = (gun00 * un0 + gun01 * un1) * b0i + (gun10 * un0 + gun11 * un1) * b1i;
                acc += conv_n_coeff * conv_n;
                acc += visc_k_coeff * (guk00 * g0x[i] + guk01 * g0y[i] + guk10 * g1x[i] + guk11 * g1y[i]);
                acc += visc_n_coeff * (gun00 * g0x[i] + gun01 * g0y[i] + gun10 * g1x[i] + gun11 * g1y[i]);
                acc -= pk_val * div_i;
                acc += bp_view(e, q, i) * div_uk;
                F_view(e, i) += w * acc;
            }
"""

        body = f"""
static py::tuple {kernel_name}(
        {arg_sig}
    ) {{
    auto qp_view = qp_phys.unchecked<3>();
    auto qw_view = qw.unchecked<2>();
    auto Jinv = J_inv.unchecked<4>();
    auto b0_view = {b0}.unchecked<3>();
    auto b1_view = {b1}.unchecked<3>();
    auto bp_view = {bp}.unchecked<3>();
    auto g0_view = {g0}.unchecked<4>();
    auto g1_view = {g1}.unchecked<4>();
    auto uk_view = {uk}.unchecked<2>();
{un_block}{"    auto pk_view = " + pk + ".unchecked<2>();" if pk else ""}

    ssize_t n_elem = qp_view.shape(0);
    ssize_t n_q    = qp_view.shape(1);
    ssize_t n_union = b0_view.shape(2);

    py::array_t<double> K({{n_elem, n_union, n_union}});
    py::array_t<double> F({{n_elem, n_union}});
    py::array_t<double> J({{n_elem}});

    auto K_view = K.mutable_unchecked<3>();
    auto F_view = F.mutable_unchecked<2>();
    auto J_view = J.mutable_unchecked<1>();

    for (ssize_t e = 0; e < n_elem; ++e) {{
        for (ssize_t i = 0; i < n_union; ++i) {{
            F_view(e, i) = 0.0;
            for (ssize_t j = 0; j < n_union; ++j) {{
                K_view(e, i, j) = 0.0;
            }}
        }}
        J_view(e) = 0.0;
    }}

    const double mass_coeff = {rho} / {dt};
    const double conv_k_coeff = {theta} * {rho};
    const double conv_n_coeff = (1.0 - {theta}) * {rho};
    const double visc_k_coeff = {theta} * {mu};
    const double visc_n_coeff = (1.0 - {theta}) * {mu};

    std::vector<double> g0x, g0y, g1x, g1y, div_phi;
    g0x.resize(n_union); g0y.resize(n_union);
    g1x.resize(n_union); g1y.resize(n_union);
    div_phi.resize(n_union);

    for (ssize_t e = 0; e < n_elem; ++e) {{
        for (ssize_t q = 0; q < n_q; ++q) {{
            double w = qw_view(e, q);
            double J00 = Jinv(e, q, 0, 0);
            double J01 = Jinv(e, q, 0, 1);
            double J10 = Jinv(e, q, 1, 0);
            double J11 = Jinv(e, q, 1, 1);

            for (ssize_t i = 0; i < n_union; ++i) {{
                double gx0 = g0_view(e, q, i, 0);
                double gy0 = g0_view(e, q, i, 1);
                double gx1 = g1_view(e, q, i, 0);
                double gy1 = g1_view(e, q, i, 1);
                double g0x_i = gx0 * J00 + gy0 * J10;
                double g0y_i = gx0 * J01 + gy0 * J11;
                double g1x_i = gx1 * J00 + gy1 * J10;
                double g1y_i = gx1 * J01 + gy1 * J11;
                g0x[i] = g0x_i; g0y[i] = g0y_i;
                g1x[i] = g1x_i; g1y[i] = g1y_i;
                div_phi[i] = g0x_i + g1y_i;
            }}

            // Values
            double uk0 = 0.0, uk1 = 0.0;
            for (ssize_t i = 0; i < n_union; ++i) {{
                double coeff = uk_view(e, i);
                uk0 += coeff * b0_view(e, q, i);
                uk1 += coeff * b1_view(e, q, i);
            }}
            double un0 = 0.0, un1 = 0.0;
{un_val_block}

            // Gradients
            double guk00 = 0.0, guk01 = 0.0, guk10 = 0.0, guk11 = 0.0;
            for (ssize_t i = 0; i < n_union; ++i) {{
                double coeff = uk_view(e, i);
                guk00 += coeff * g0x[i];
                guk01 += coeff * g0y[i];
                guk10 += coeff * g1x[i];
                guk11 += coeff * g1y[i];
            }}
            double gun00 = 0.0, gun01 = 0.0, gun10 = 0.0, gun11 = 0.0;
{un_grad_block}

            double div_uk = guk00 + guk11;
            double div_un = gun00 + gun11;

            double pk_val = 0.0;
{pk_block}

{ke_block}
{fe_block}
        }}
    }}

    return py::make_tuple(K, F, J);
}}

PYBIND11_MODULE({module_name}, m) {{
    m.doc() = "pycutfem experimental C++ Navier-Stokes kernel";
    m.def("{kernel_name}", &{kernel_name}, "Experimental C++ kernel");
    m.attr("PARAM_ORDER") = py::make_tuple({param_list});
    m.attr("CODEGEN_ABI") = "{CODEGEN_ABI_CPP}";
}}
"""
        return CPP_HEADER + body
