from pycutfem.utils.meshgen import structured_triangles, structured_quad
nodes_tri, tri, edges_tri, elements_corner_tri = structured_triangles(1,1, nx_quads=1, ny_quads=1, poly_order=11)
print("Triangles nodes:", nodes_tri)
print("Triangles elements:", tri)
print(f"number of triangles: {tri.shape[0]}")
print("number of triangle edges:", edges_tri.shape[0])
print("Triangles edges:", edges_tri)
print("Triangles corners:", elements_corner_tri)
# nodes_quad, quads, edges_quad = structured_quad(1,1, nx=1, ny=1, poly_order=5)
# print("Quads nodes:", nodes_quad)
# print("Quads elements:", quads)
# print("Quads edges:", edges_quad)