import os
from pathlib import Path

import numpy as np
import pytest
from numpy.testing import assert_allclose

from pycutfem.core.mesh import Mesh
from pycutfem.core.topology import Node
from pycutfem.core.dofhandler import DofHandler
from pycutfem.core.levelset import LevelSetGridFunction
from pycutfem.fem.mixedelement import MixedElement
from pycutfem.ufl.expressions import Constant
from pycutfem.ufl.forms import Equation, assemble_form
from pycutfem.ufl.measures import dInterface, dx


def _assemble_scalar(form, dof_handler, *, backend: str = "jit") -> float:
    hook = {type(form.integrand): {"name": "scalar"}}
    res = assemble_form(Equation(None, form), dof_handler=dof_handler, bcs=[], backend=backend, assembler_hooks=hook)
    val = res["scalar"]
    if isinstance(val, np.ndarray):
        return float(val.reshape(-1)[0])
    return float(val)


def _latest_phi_file(dump_dir: Path) -> Path | None:
    candidates = sorted(dump_dir.glob("phi_*_*.npz"))
    return candidates[-1] if candidates else None


def test_replay_turek_levelset_dump_partition_and_interface_length():
    """
    Optional debug/replay test.

    Usage:
      PYCUTFEM_LEVELSET_DUMP_DIR=/path/to/levelset_dumps python -m pytest -q tests/ufl/test_turek_levelset_dump_replay.py

    The dump files are generated by `examples/turek_fsi_fully_eulerian.py` when:
      PYCUTFEM_DUMP_LEVELSET=1
    """
    dump_dir = os.getenv("PYCUTFEM_LEVELSET_DUMP_DIR", "").strip()
    if not dump_dir:
        pytest.skip("Set PYCUTFEM_LEVELSET_DUMP_DIR to replay a dumped Turek level set.")

    dump_dir_p = Path(dump_dir)
    mesh_file = dump_dir_p / "mesh.npz"
    if not mesh_file.exists():
        pytest.skip(f"Missing mesh dump file: {mesh_file}")

    phi_file = os.getenv("PYCUTFEM_LEVELSET_DUMP_STEP_FILE", "").strip()
    if phi_file:
        phi_path = Path(phi_file)
    else:
        phi_path = _latest_phi_file(dump_dir_p)
        if phi_path is None:
            pytest.skip(f"No phi_*.npz files found in {dump_dir_p}")

    mesh_npz = np.load(mesh_file, allow_pickle=True)
    nodes = np.asarray(mesh_npz["nodes"], dtype=float)
    elements = np.asarray(mesh_npz["elements"], dtype=np.int64)
    edges = np.asarray(mesh_npz["edges"], dtype=np.int64)
    corners = np.asarray(mesh_npz["corners"], dtype=np.int64)
    element_type = str(mesh_npz["element_type"])
    poly_order = int(mesh_npz["poly_order"])
    phi_poly_order = int(mesh_npz.get("phi_poly_order", poly_order))

    phi_npz = np.load(phi_path, allow_pickle=True)
    phi_vals = np.asarray(phi_npz["phi"], dtype=float)

    node_objs = [Node(int(i), float(x), float(y)) for i, (x, y) in enumerate(nodes)]
    mesh = Mesh(
        nodes=node_objs,
        element_connectivity=elements,
        edges_connectivity=edges,
        elements_corner_nodes=corners,
        element_type=element_type,
        poly_order=poly_order,
    )

    me_phi = MixedElement(mesh, field_specs={"phi_beam": phi_poly_order})
    dh_phi = DofHandler(me_phi, method="cg")
    ls = LevelSetGridFunction(dh_phi, field="phi_beam")
    ls.set_from_array(phi_vals)

    mesh.classify_elements(ls, tol=1e-10)
    mesh.classify_edges(ls, tol=1e-10)
    mesh.build_interface_segments(ls, tol=1e-10)

    if "cut_elems" in phi_npz and "interface_edges" in phi_npz:
        assert int(mesh.element_bitset("cut").cardinality()) == int(phi_npz["cut_elems"])
        assert int(mesh.edge_bitset("interface").cardinality()) == int(phi_npz["interface_edges"])

    # Basic sanity: interface extraction should produce finite values.
    assert np.isfinite(mesh.nodes_x_y_pos).all()

    me = MixedElement(mesh, field_specs={"u": 1})
    dh = DofHandler(me, method="cg")

    inside = mesh.element_bitset("inside")
    outside = mesh.element_bitset("outside")
    cut = mesh.element_bitset("cut")

    q = int(os.getenv("PYCUTFEM_LEVELSET_DUMP_REPLAY_Q", "6") or "6")
    dx_neg = dx(defined_on=inside | cut, level_set=ls, metadata={"side": "-", "q": q})
    dx_pos = dx(defined_on=outside | cut, level_set=ls, metadata={"side": "+", "q": q})
    A_neg = _assemble_scalar(Constant(1.0) * dx_neg, dh, backend=os.getenv("PYCUTFEM_LEVELSET_DUMP_REPLAY_BACKEND", "jit"))
    A_pos = _assemble_scalar(Constant(1.0) * dx_pos, dh, backend=os.getenv("PYCUTFEM_LEVELSET_DUMP_REPLAY_BACKEND", "jit"))
    total = float(np.sum(np.asarray(mesh.areas_list, dtype=float)))
    assert_allclose(A_neg + A_pos, total, rtol=2e-6, atol=max(1e-9, 2e-6 * total))

    L_ifc = _assemble_scalar(
        Constant(1.0) * dInterface(level_set=ls, metadata={"q": q + 2}),
        dh,
        backend=os.getenv("PYCUTFEM_LEVELSET_DUMP_REPLAY_BACKEND", "jit"),
    )
    assert np.isfinite(L_ifc)
    assert L_ifc >= 0.0
