#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
LOG_DIR="${ROOT_DIR}/examples/NIRB/logs"
mkdir -p "${LOG_DIR}"

SESSION_NAME="${1:-nirb_example2_local_fpi}"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
LOG_FILE="${LOG_DIR}/${SESSION_NAME}_${TIMESTAMP}.log"
OUTPUT_DIR="${2:-examples/NIRB/artifacts/example2_snapshot_matrix_re301_exact_${TIMESTAMP}}"
END_TIME="${END_TIME:-6.008}"
VTK_EVERY="${VTK_EVERY:-1}"
MAX_COUPLING_ITERS="${MAX_COUPLING_ITERS:-12}"
MAX_NEWTON_ITER="${MAX_NEWTON_ITER:-20}"
COUPLING_ABS_TOL="${COUPLING_ABS_TOL:-5e-3}"
COUPLING_REL_TOL="${COUPLING_REL_TOL:-5e-3}"
LS_FAIL_ACCEPT_FACTOR="${LS_FAIL_ACCEPT_FACTOR:-0}"

cd "${ROOT_DIR}"

CMD=(
  "conda" "run" "--no-capture-output" "-n" "fenicsx"
  "python" "-u"
  "examples/NIRB/run_example2_local.py"
  "--output-dir" "${OUTPUT_DIR}"
  "--mesh-source" "reference"
  "--poly-order" "1"
  "--pressure-order" "1"
  "--reynolds" "301"
  "--dt" "0.008"
  "--end-time" "${END_TIME}"
  "--max-coupling-iters" "${MAX_COUPLING_ITERS}"
  "--coupling-abs-tol" "${COUPLING_ABS_TOL}"
  "--coupling-rel-tol" "${COUPLING_REL_TOL}"
  "--load-transfer" "reaction"
  "--force-update" "iqnils"
  "--force-relaxation" "0.5"
  "--force-history" "3"
  "--force-regularization" "1e-10"
  "--newton-tol" "1e-6"
  "--max-newton-iter" "${MAX_NEWTON_ITER}"
  "--bossak-alpha" "-0.3"
  "--dynamic-tau" "1.0"
  "--pressure-gauge" "1e-5"
  "--fluid-operator" "exact"
  "--backend" "cpp"
  "--linear-backend" "petsc"
  "--snapshot-mode" "all"
  "--save-vtk"
  "--vtk-every" "${VTK_EVERY}"
  "--monitor-interface-loads"
  "--verbose"
)

tmux new-session -d -s "${SESSION_NAME}" "cd '${ROOT_DIR}' && export PYCUTFEM_LS_FAIL_ACCEPT_FACTOR='${LS_FAIL_ACCEPT_FACTOR}' && ${CMD[*]} 2>&1 | tee '${LOG_FILE}'"

echo "session=${SESSION_NAME}"
echo "log=${LOG_FILE}"
echo "output_dir=${OUTPUT_DIR}"
echo "attach: tmux attach -t ${SESSION_NAME}"
