#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
LOG_DIR="${ROOT_DIR}/examples/NIRB/logs"
mkdir -p "${LOG_DIR}"

SESSION_NAME="${1:-nirb_example2_local_fpi}"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
LOG_FILE="${LOG_DIR}/${SESSION_NAME}_${TIMESTAMP}.log"
OUTPUT_DIR="${2:-examples/NIRB/artifacts/example2_snapshot_matrix_re301_exact_${TIMESTAMP}}"
END_TIME="${END_TIME:-6.008}"
VTK_EVERY="${VTK_EVERY:-1}"
CHECKPOINT_EVERY="${CHECKPOINT_EVERY:-1}"
STEP_HISTORY_EVERY="${STEP_HISTORY_EVERY:-1}"
QUAD_ORDER="${QUAD_ORDER:-1}"
MAX_COUPLING_ITERS="${MAX_COUPLING_ITERS:-50}"
MAX_NEWTON_ITER="${MAX_NEWTON_ITER:-20}"
COUPLING_ABS_TOL="${COUPLING_ABS_TOL:-5e-3}"
COUPLING_REL_TOL="${COUPLING_REL_TOL:-5e-3}"
FORCE_UPDATE="${FORCE_UPDATE:-iqnils}"
FORCE_RELAXATION="${FORCE_RELAXATION:-0.5}"
FORCE_HISTORY="${FORCE_HISTORY:-3}"
FORCE_REGULARIZATION="${FORCE_REGULARIZATION:-0.0}"
STEP_RETRIES="${STEP_RETRIES:-0}"
LS_FAIL_ACCEPT_FACTOR="${LS_FAIL_ACCEPT_FACTOR:-0}"
RESTART_FROM="${RESTART_FROM:-}"
EXACT_FLUID_GLOBALIZATION="${EXACT_FLUID_GLOBALIZATION:-line_search}"
EXACT_FLUID_LINE_SEARCH="${EXACT_FLUID_LINE_SEARCH:-0}"
EXACT_FLUID_LS_FAIL_HARD="${EXACT_FLUID_LS_FAIL_HARD:-1}"
EXACT_FLUID_MIXED_RES_FACTOR="${EXACT_FLUID_MIXED_RES_FACTOR:-0}"
EXACT_FLUID_ACCEPT_MAXITER="${EXACT_FLUID_ACCEPT_MAXITER:-1}"
EXACT_FLUID_BACKEND="${EXACT_FLUID_BACKEND:-local}"
EXACT_STRUCTURE_BACKEND="${EXACT_STRUCTURE_BACKEND:-local}"
SOLID_SYSTEM_BACKEND="${SOLID_SYSTEM_BACKEND:-symbolic}"
MESH_EXTENSION_SOLVER="${MESH_EXTENSION_SOLVER:-direct}"
LOCAL_STRUCTURE_LINEAR_BACKEND="${LOCAL_STRUCTURE_LINEAR_BACKEND:-sparseqr}"
OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}"
MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"
NUMBA_NUM_THREADS="${NUMBA_NUM_THREADS:-1}"

cd "${ROOT_DIR}"

CMD=(
  "conda" "run" "--no-capture-output" "-n" "fenicsx"
  "python" "-u"
  "examples/NIRB/run_example2_local.py"
  "--output-dir" "${OUTPUT_DIR}"
  "--mesh-source" "reference"
  "--poly-order" "1"
  "--pressure-order" "1"
  "--quad-order" "${QUAD_ORDER}"
  "--reynolds" "301"
  "--dt" "0.008"
  "--end-time" "${END_TIME}"
  "--max-coupling-iters" "${MAX_COUPLING_ITERS}"
  "--coupling-abs-tol" "${COUPLING_ABS_TOL}"
  "--coupling-rel-tol" "${COUPLING_REL_TOL}"
  "--load-transfer" "reaction"
  "--force-update" "${FORCE_UPDATE}"
  "--force-relaxation" "${FORCE_RELAXATION}"
  "--force-history" "${FORCE_HISTORY}"
  "--force-regularization" "${FORCE_REGULARIZATION}"
  "--step-retries" "${STEP_RETRIES}"
  "--newton-tol" "1e-6"
  "--max-newton-iter" "${MAX_NEWTON_ITER}"
  "--bossak-alpha" "-0.3"
  "--dynamic-tau" "1.0"
  "--pressure-gauge" "1e-5"
  "--fluid-operator" "exact"
  "--backend" "cpp"
  "--linear-backend" "amgcl"
  "--snapshot-mode" "all"
  "--save-vtk"
  "--vtk-every" "${VTK_EVERY}"
  "--checkpoint-every" "${CHECKPOINT_EVERY}"
  "--step-history-every" "${STEP_HISTORY_EVERY}"
  "--monitor-interface-loads"
  "--verbose"
)

if [[ -n "${RESTART_FROM}" ]]; then
  CMD+=("--restart-from" "${RESTART_FROM}")
fi

tmux new-session -d -s "${SESSION_NAME}" "cd '${ROOT_DIR}' && export OMP_NUM_THREADS='${OMP_NUM_THREADS}' && export OPENBLAS_NUM_THREADS='${OPENBLAS_NUM_THREADS}' && export MKL_NUM_THREADS='${MKL_NUM_THREADS}' && export NUMBA_NUM_THREADS='${NUMBA_NUM_THREADS}' && export PYCUTFEM_LS_FAIL_ACCEPT_FACTOR='${LS_FAIL_ACCEPT_FACTOR}' && export PYCUTFEM_EX2_EXACT_FLUID_GLOBALIZATION='${EXACT_FLUID_GLOBALIZATION}' && export PYCUTFEM_EX2_EXACT_FLUID_LINE_SEARCH='${EXACT_FLUID_LINE_SEARCH}' && export PYCUTFEM_EX2_EXACT_FLUID_LS_FAIL_HARD='${EXACT_FLUID_LS_FAIL_HARD}' && export PYCUTFEM_EX2_EXACT_FLUID_MIXED_RES_FACTOR='${EXACT_FLUID_MIXED_RES_FACTOR}' && export PYCUTFEM_EX2_EXACT_FLUID_ACCEPT_MAXITER='${EXACT_FLUID_ACCEPT_MAXITER}' && export PYCUTFEM_EX2_EXACT_FLUID_BACKEND='${EXACT_FLUID_BACKEND}' && export PYCUTFEM_EX2_EXACT_STRUCTURE_BACKEND='${EXACT_STRUCTURE_BACKEND}' && export PYCUTFEM_EX2_SOLID_SYSTEM_BACKEND='${SOLID_SYSTEM_BACKEND}' && export PYCUTFEM_EX2_MESH_EXTENSION_SOLVER='${MESH_EXTENSION_SOLVER}' && export PYCUTFEM_EX2_LOCAL_STRUCTURE_LINEAR_BACKEND='${LOCAL_STRUCTURE_LINEAR_BACKEND}' && ${CMD[*]} 2>&1 | tee '${LOG_FILE}'"

echo "session=${SESSION_NAME}"
echo "log=${LOG_FILE}"
echo "output_dir=${OUTPUT_DIR}"
echo "attach: tmux attach -t ${SESSION_NAME}"
